/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import * as operations from "../operations/index.js";
import { NewlineError } from "./newline-error.js";

/**
 * A Synthetic Account is not updated if a required parameter is missing
 *
 * @remarks
 */
export type UpdateSyntheticAccountBadRequestErrorData = {
  errors?: Array<operations.UpdateSyntheticAccountError> | undefined;
  /**
   * HTTP Status Code
   */
  status?: number | undefined;
};

/**
 * A Synthetic Account is not updated if a required parameter is missing
 *
 * @remarks
 */
export class UpdateSyntheticAccountBadRequestError extends NewlineError {
  errors?: Array<operations.UpdateSyntheticAccountError> | undefined;
  /**
   * HTTP Status Code
   */
  status?: number | undefined;

  /** The original data that was passed to this error instance. */
  data$: UpdateSyntheticAccountBadRequestErrorData;

  constructor(
    err: UpdateSyntheticAccountBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.errors != null) this.errors = err.errors;
    if (err.status != null) this.status = err.status;

    this.name = "UpdateSyntheticAccountBadRequestError";
  }
}

/** @internal */
export const UpdateSyntheticAccountBadRequestError$inboundSchema: z.ZodMiniType<
  UpdateSyntheticAccountBadRequestError,
  unknown
> = z.pipe(
  z.object({
    errors: types.optional(
      z.array(
        z.lazy(() => operations.UpdateSyntheticAccountError$inboundSchema),
      ),
    ),
    status: types.optional(types.number()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new UpdateSyntheticAccountBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
