// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/models/operations"
)

// PutVirtualReferenceNumbersUIDLockUnprocessableEntityError - The Virtual Reference Number could not be locked
type PutVirtualReferenceNumbersUIDLockUnprocessableEntityError struct {
	Errors []operations.PutVirtualReferenceNumbersUIDLockUnprocessableEntityError `json:"errors,omitempty"`
	// HTTP Status Code
	Status   *int64                  `json:"status,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &PutVirtualReferenceNumbersUIDLockUnprocessableEntityError{}

func (e *PutVirtualReferenceNumbersUIDLockUnprocessableEntityError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// PutVirtualReferenceNumbersUIDLockNotFoundError - The Virtual Reference Number is not found
type PutVirtualReferenceNumbersUIDLockNotFoundError struct {
	Errors []operations.PutVirtualReferenceNumbersUIDLockNotFoundError `json:"errors,omitempty"`
	// HTTP Status Code
	Status   *int64                  `json:"status,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &PutVirtualReferenceNumbersUIDLockNotFoundError{}

func (e *PutVirtualReferenceNumbersUIDLockNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
