// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"fmt"
	"log"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/operations"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathPostCombinedTransfers(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "post_/combined_transfers-ach_transfer_to_new_account[0]":
			dir.HandlerFunc("post_/combined_transfers", testPostCombinedTransfersPostCombinedTransfersAchTransferToNewAccount0)(w, req)
		case "post_/combined_transfers-ach_transfer_to_existing_account[0]":
			dir.HandlerFunc("post_/combined_transfers", testPostCombinedTransfersPostCombinedTransfersAchTransferToExistingAccount0)(w, req)
		case "post_/combined_transfers-instant_payment_transfer_to_new_account[0]":
			dir.HandlerFunc("post_/combined_transfers", testPostCombinedTransfersPostCombinedTransfersInstantPaymentTransferToNewAccount0)(w, req)
		case "post_/combined_transfers-instant_payment_transfer_to_existing_account[0]":
			dir.HandlerFunc("post_/combined_transfers", testPostCombinedTransfersPostCombinedTransfersInstantPaymentTransferToExistingAccount0)(w, req)
		case "post_/combined_transfers-wire_transfer_to_new_account[0]":
			dir.HandlerFunc("post_/combined_transfers", testPostCombinedTransfersPostCombinedTransfersWireTransferToNewAccount0)(w, req)
		case "post_/combined_transfers-wire_transfer_to_existing_account[0]":
			dir.HandlerFunc("post_/combined_transfers", testPostCombinedTransfersPostCombinedTransfersWireTransferToExistingAccount0)(w, req)
		case "post_/combined_transfers-queued[0]":
			dir.HandlerFunc("post_/combined_transfers", testPostCombinedTransfersPostCombinedTransfersQueued0)(w, req)
		default:
			http.Error(w, fmt.Sprintf("Unknown test: %s[%d]", test, count), http.StatusBadRequest)
		}
	}
}

func testPostCombinedTransfersPostCombinedTransfersAchTransferToNewAccount0(w http.ResponseWriter, req *http.Request) {
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.PostCombinedTransfersResponseBody = &operations.PostCombinedTransfersResponseBody{
		CreatedAt: types.String("2025-03-27T09:23:07.890Z"),
		Errors: []operations.PostCombinedTransfersError{
			operations.PostCombinedTransfersError{
				Code:       types.Int64(33005),
				Title:      types.String("Could not continue Combined Transfer"),
				Detail:     types.String("An exception occurred while continuing a Combined Transfer"),
				OccurredAt: types.String("2025-03-27T09:23:07.890Z"),
			},
		},
		ExternalUID: types.String("YrfDrfVRgpPgnhF5"),
		Status:      operations.PostCombinedTransfersStatusPending.ToPointer(),
		UID:         types.String("dYTG8WAWAh5UyvY7"),
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_, _ = w.Write(respBodyBytes)
}

func testPostCombinedTransfersPostCombinedTransfersAchTransferToExistingAccount0(w http.ResponseWriter, req *http.Request) {
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.PostCombinedTransfersResponseBody = &operations.PostCombinedTransfersResponseBody{
		CreatedAt: types.String("2025-03-27T09:23:07.890Z"),
		Errors: []operations.PostCombinedTransfersError{
			operations.PostCombinedTransfersError{
				Code:       types.Int64(33005),
				Title:      types.String("Could not continue Combined Transfer"),
				Detail:     types.String("An exception occurred while continuing a Combined Transfer"),
				OccurredAt: types.String("2025-03-27T09:23:07.890Z"),
			},
		},
		ExternalUID: types.String("YrfDrfVRgpPgnhF5"),
		Status:      operations.PostCombinedTransfersStatusPending.ToPointer(),
		UID:         types.String("dYTG8WAWAh5UyvY7"),
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_, _ = w.Write(respBodyBytes)
}

func testPostCombinedTransfersPostCombinedTransfersInstantPaymentTransferToNewAccount0(w http.ResponseWriter, req *http.Request) {
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.PostCombinedTransfersResponseBody = &operations.PostCombinedTransfersResponseBody{
		CreatedAt: types.String("2025-03-27T09:23:07.890Z"),
		Errors: []operations.PostCombinedTransfersError{
			operations.PostCombinedTransfersError{
				Code:       types.Int64(33005),
				Title:      types.String("Could not continue Combined Transfer"),
				Detail:     types.String("An exception occurred while continuing a Combined Transfer"),
				OccurredAt: types.String("2025-03-27T09:23:07.890Z"),
			},
		},
		ExternalUID: types.String("YrfDrfVRgpPgnhF5"),
		Status:      operations.PostCombinedTransfersStatusPending.ToPointer(),
		UID:         types.String("dYTG8WAWAh5UyvY7"),
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_, _ = w.Write(respBodyBytes)
}

func testPostCombinedTransfersPostCombinedTransfersInstantPaymentTransferToExistingAccount0(w http.ResponseWriter, req *http.Request) {
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.PostCombinedTransfersResponseBody = &operations.PostCombinedTransfersResponseBody{
		CreatedAt: types.String("2025-03-27T09:23:07.890Z"),
		Errors: []operations.PostCombinedTransfersError{
			operations.PostCombinedTransfersError{
				Code:       types.Int64(33005),
				Title:      types.String("Could not continue Combined Transfer"),
				Detail:     types.String("An exception occurred while continuing a Combined Transfer"),
				OccurredAt: types.String("2025-03-27T09:23:07.890Z"),
			},
		},
		ExternalUID: types.String("YrfDrfVRgpPgnhF5"),
		Status:      operations.PostCombinedTransfersStatusPending.ToPointer(),
		UID:         types.String("dYTG8WAWAh5UyvY7"),
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_, _ = w.Write(respBodyBytes)
}

func testPostCombinedTransfersPostCombinedTransfersWireTransferToNewAccount0(w http.ResponseWriter, req *http.Request) {
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.PostCombinedTransfersResponseBody = &operations.PostCombinedTransfersResponseBody{
		CreatedAt: types.String("2025-03-27T09:23:07.890Z"),
		Errors: []operations.PostCombinedTransfersError{
			operations.PostCombinedTransfersError{
				Code:       types.Int64(33005),
				Title:      types.String("Could not continue Combined Transfer"),
				Detail:     types.String("An exception occurred while continuing a Combined Transfer"),
				OccurredAt: types.String("2025-03-27T09:23:07.890Z"),
			},
		},
		ExternalUID: types.String("YrfDrfVRgpPgnhF5"),
		Status:      operations.PostCombinedTransfersStatusPending.ToPointer(),
		UID:         types.String("dYTG8WAWAh5UyvY7"),
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_, _ = w.Write(respBodyBytes)
}

func testPostCombinedTransfersPostCombinedTransfersWireTransferToExistingAccount0(w http.ResponseWriter, req *http.Request) {
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.PostCombinedTransfersResponseBody = &operations.PostCombinedTransfersResponseBody{
		CreatedAt: types.String("2025-03-27T09:23:07.890Z"),
		Errors: []operations.PostCombinedTransfersError{
			operations.PostCombinedTransfersError{
				Code:       types.Int64(33005),
				Title:      types.String("Could not continue Combined Transfer"),
				Detail:     types.String("An exception occurred while continuing a Combined Transfer"),
				OccurredAt: types.String("2025-03-27T09:23:07.890Z"),
			},
		},
		ExternalUID: types.String("YrfDrfVRgpPgnhF5"),
		Status:      operations.PostCombinedTransfersStatusPending.ToPointer(),
		UID:         types.String("dYTG8WAWAh5UyvY7"),
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_, _ = w.Write(respBodyBytes)
}

func testPostCombinedTransfersPostCombinedTransfersQueued0(w http.ResponseWriter, req *http.Request) {
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.PostCombinedTransfersResponseBody = &operations.PostCombinedTransfersResponseBody{
		CreatedAt:        types.String("2025-03-27T09:23:07.890Z"),
		ExternalUID:      types.String("YrfDrfVRgpPgnhF5"),
		Status:           operations.PostCombinedTransfersStatusQueued.ToPointer(),
		SyntheticAccount: &operations.PostCombinedTransfersSyntheticAccountResponse{},
		Transfer:         &operations.PostCombinedTransfersTransferResponse{},
		UID:              types.String("iLCATodsXhKPpPRv"),
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_, _ = w.Write(respBodyBytes)
}
