// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"fmt"
	"log"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/operations"
	"mockserver/internal/sdk/optionalnullable"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathPutSyntheticAccountsUID(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "updateSyntheticAccount-general_synthetic_account[0]":
			dir.HandlerFunc("updateSyntheticAccount", testUpdateSyntheticAccountUpdateSyntheticAccountGeneralSyntheticAccount0)(w, req)
		case "updateSyntheticAccount-instant_payment_synthetic_account[0]":
			dir.HandlerFunc("updateSyntheticAccount", testUpdateSyntheticAccountUpdateSyntheticAccountInstantPaymentSyntheticAccount0)(w, req)
		case "updateSyntheticAccount-wire_synthetic_account[0]":
			dir.HandlerFunc("updateSyntheticAccount", testUpdateSyntheticAccountUpdateSyntheticAccountWireSyntheticAccount0)(w, req)
		case "updateSyntheticAccount-ach_account[0]":
			dir.HandlerFunc("updateSyntheticAccount", testUpdateSyntheticAccountUpdateSyntheticAccountAchAccount0)(w, req)
		default:
			http.Error(w, fmt.Sprintf("Unknown test: %s[%d]", test, count), http.StatusBadRequest)
		}
	}
}

func testUpdateSyntheticAccountUpdateSyntheticAccountGeneralSyntheticAccount0(w http.ResponseWriter, req *http.Request) {
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.UpdateSyntheticAccountResponseBody = &operations.UpdateSyntheticAccountResponseBody{
		UID:                     types.String("exMDShw6yM3NHLYV"),
		ExternalUID:             types.String("60689018-94e9-4870-970a-cc22f52c9c65"),
		Name:                    types.String("Spinach Fund"),
		PoolUID:                 types.String("wTSMX1GubP21ev2h"),
		SyntheticAccountTypeUID: types.String("fRMwt6H14ovFUz1s"),
		CustodialAccountUids: []string{
			"4uJMJjNd5wjzPaCj",
			"3fRiyDdbSVv9nKW2",
		},
		SyntheticAccountCategory: operations.UpdateSyntheticAccountSyntheticAccountCategoryGeneral.ToPointer(),
		Status:                   operations.UpdateSyntheticAccountStatusActive.ToPointer(),
		Liability:                types.Bool(true),
		NetUsdBalance:            optionalnullable.From(types.String("0")),
		NetUsdPendingBalance:     optionalnullable.From(types.String("0")),
		NetUsdAvailableBalance:   optionalnullable.From(types.String("0")),
		AssetBalances: []*operations.UpdateSyntheticAccountAssetBalance{
			&operations.UpdateSyntheticAccountAssetBalance{
				AssetQuantity:        types.String("769.65"),
				AssetType:            types.String("USD"),
				CurrentUsdValue:      types.String("769.65"),
				CustodialAccountUID:  types.String("4uJMJjNd5wjzPaCj"),
				CustodialAccountName: types.String("Second Checking"),
				Debit:                types.Bool(false),
			},
		},
		MasterAccount:         types.Bool(false),
		RoutingNumber:         optionalnullable.From(types.String("123456789")),
		AccountNumberLastFour: optionalnullable.From(types.String("7890")),
		OpenedAt:              types.MustNewTimeFromString("2018-03-08T19:07:18.049Z"),
		ClosedAt:              nil,
		AccountNumber:         optionalnullable.From(types.String("1234567890")),
		Wire: &operations.UpdateSyntheticAccountWireResponse{
			CounterpartyAddress: optionalnullable.From(&operations.UpdateSyntheticAccountWireCounterpartyAddressResponse{
				Line1:   optionalnullable.From(types.String("234 Xyz Rd")),
				Line2:   optionalnullable.From(types.String("APT 5")),
				Line3:   optionalnullable.From(types.String("Boston, MA 02110")),
				Country: optionalnullable.From(types.String("US")),
			}),
			CounterpartyName: types.String("Marge's Roofing Inc"),
			CounterpartyBankAddress: optionalnullable.From(&operations.UpdateSyntheticAccountCounterpartyBankAddressResponse{
				Line1:   optionalnullable.From(types.String("123 Abc St.")),
				Line2:   optionalnullable.From(types.String("Boring, Oregon 97009")),
				Line3:   nil,
				Country: nil,
			}),
			CounterpartyBankName: optionalnullable.From(types.String("East West Regional Bank")),
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}

func testUpdateSyntheticAccountUpdateSyntheticAccountInstantPaymentSyntheticAccount0(w http.ResponseWriter, req *http.Request) {
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.UpdateSyntheticAccountResponseBody = &operations.UpdateSyntheticAccountResponseBody{
		UID:                     types.String("nbDrqhrFAjqUdxBG"),
		ExternalUID:             types.String("f03fd9ff-a0a1-4e3c-981f-4d845836a2ce"),
		Name:                    types.String("Instant Payments Account"),
		PoolUID:                 types.String("wTSMX1GubP21ev2h"),
		SyntheticAccountTypeUID: types.String("fRMwt6H14ovFUz1s"),
		CustodialAccountUids: []string{
			"DcMfBTHj94dsi471",
		},
		SyntheticAccountCategory: operations.UpdateSyntheticAccountSyntheticAccountCategoryInstantPaymentExternal.ToPointer(),
		Status:                   operations.UpdateSyntheticAccountStatusActive.ToPointer(),
		Liability:                types.Bool(false),
		NetUsdBalance:            nil,
		NetUsdPendingBalance:     nil,
		NetUsdAvailableBalance:   nil,
		AssetBalances: []*operations.UpdateSyntheticAccountAssetBalance{
			&operations.UpdateSyntheticAccountAssetBalance{
				AssetQuantity:        types.String("12.23"),
				AssetType:            types.String("USD"),
				CurrentUsdValue:      types.String("122.12"),
				CustodialAccountUID:  types.String("wZgfnLrLJcCAscnH"),
				CustodialAccountName: types.String("First Checking"),
				Debit:                types.Bool(true),
			},
		},
		MasterAccount:         types.Bool(false),
		RoutingNumber:         optionalnullable.From(types.String("123456789")),
		AccountNumberLastFour: optionalnullable.From(types.String("9012")),
		OpenedAt:              types.MustNewTimeFromString("2022-02-22T23:14:27.012Z"),
		ClosedAt:              nil,
		AccountNumber:         nil,
		InstantPayment: &operations.UpdateSyntheticAccountInstantPaymentResponse{
			CounterpartyAddress: &operations.UpdateSyntheticAccountInstantPaymentCounterpartyAddressResponse{
				StreetNumber: "242",
				Street1:      "Marble St",
				City:         types.String("Marblehead"),
				State:        types.String("MA"),
				PostalCode:   types.String("21945"),
				Country:      types.String("US"),
			},
			CounterpartyName: types.String("Paloma's Premium Polymers"),
			Email:            optionalnullable.From(types.String("paloma@premiumpolymers.co")),
			Phone:            optionalnullable.From(types.String("5555551212")),
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}

func testUpdateSyntheticAccountUpdateSyntheticAccountWireSyntheticAccount0(w http.ResponseWriter, req *http.Request) {
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.UpdateSyntheticAccountResponseBody = &operations.UpdateSyntheticAccountResponseBody{
		UID:                     types.String("exMDShw6yM3NHLYV"),
		ExternalUID:             types.String("60689018-94e9-4870-970a-cc22f52c9c65"),
		Name:                    types.String("Wire Account"),
		PoolUID:                 types.String("wTSMX1GubP21ev2h"),
		SyntheticAccountTypeUID: types.String("VMwzNGctNAbSmHXJ"),
		CustodialAccountUids: []string{
			"NPeYkNMDVBWnKVXJ",
		},
		SyntheticAccountCategory: operations.UpdateSyntheticAccountSyntheticAccountCategoryWireExternal.ToPointer(),
		Status:                   operations.UpdateSyntheticAccountStatusActive.ToPointer(),
		Liability:                types.Bool(false),
		NetUsdBalance:            nil,
		NetUsdPendingBalance:     nil,
		NetUsdAvailableBalance:   nil,
		AssetBalances: []*operations.UpdateSyntheticAccountAssetBalance{
			&operations.UpdateSyntheticAccountAssetBalance{
				AssetQuantity:        types.String("12.23"),
				AssetType:            types.String("USD"),
				CurrentUsdValue:      types.String("122.12"),
				CustodialAccountUID:  types.String("wZgfnLrLJcCAscnH"),
				CustodialAccountName: types.String("First Checking"),
				Debit:                types.Bool(true),
			},
		},
		MasterAccount:         types.Bool(false),
		RoutingNumber:         optionalnullable.From(types.String("123456789")),
		AccountNumberLastFour: optionalnullable.From(types.String("9012")),
		OpenedAt:              types.MustNewTimeFromString("2018-03-08T19:07:18.049Z"),
		ClosedAt:              nil,
		AccountNumber:         nil,
		Wire: &operations.UpdateSyntheticAccountWireResponse{
			CounterpartyAddress: optionalnullable.From(&operations.UpdateSyntheticAccountWireCounterpartyAddressResponse{
				Line1:   optionalnullable.From(types.String("333 Swamp St")),
				Line2:   optionalnullable.From(types.String("Bagdad, FL 32530")),
				Line3:   nil,
				Country: optionalnullable.From(types.String("US")),
			}),
			CounterpartyName: types.String("Aunt Sandy"),
			CounterpartyBankAddress: optionalnullable.From(&operations.UpdateSyntheticAccountCounterpartyBankAddressResponse{
				Line1:   optionalnullable.From(types.String("334 Swamp St")),
				Line2:   optionalnullable.From(types.String("Bagdad, FL 32530")),
				Line3:   nil,
				Country: optionalnullable.From(types.String("US")),
			}),
			CounterpartyBankName: optionalnullable.From(types.String("First Beach Bank")),
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}

func testUpdateSyntheticAccountUpdateSyntheticAccountAchAccount0(w http.ResponseWriter, req *http.Request) {
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.UpdateSyntheticAccountResponseBody = &operations.UpdateSyntheticAccountResponseBody{
		UID:                     types.String("uu2XSYPAB57iX5wi"),
		ExternalUID:             types.String("g13fd9ff-a0a1-4a3c-782f-1b8458f6a2ce"),
		Name:                    types.String("ACH Account"),
		PoolUID:                 types.String("wTSMX1GubP21ev2h"),
		SyntheticAccountTypeUID: types.String("9gdN9noL2L1nj9R8"),
		CustodialAccountUids: []string{
			"zH9WRBskMKiyu3D9",
		},
		SyntheticAccountCategory: operations.UpdateSyntheticAccountSyntheticAccountCategoryAchExternal.ToPointer(),
		Status:                   operations.UpdateSyntheticAccountStatusActive.ToPointer(),
		Liability:                types.Bool(false),
		NetUsdBalance:            nil,
		NetUsdPendingBalance:     nil,
		NetUsdAvailableBalance:   nil,
		AssetBalances: []*operations.UpdateSyntheticAccountAssetBalance{
			&operations.UpdateSyntheticAccountAssetBalance{
				AssetQuantity:        types.String("12.23"),
				AssetType:            types.String("USD"),
				CurrentUsdValue:      types.String("122.12"),
				CustodialAccountUID:  types.String("wZgfnLrLJcCAscnH"),
				CustodialAccountName: types.String("First Checking"),
				Debit:                types.Bool(true),
			},
		},
		MasterAccount:         types.Bool(false),
		RoutingNumber:         optionalnullable.From(types.String("123456789")),
		AccountNumberLastFour: optionalnullable.From(types.String("7890")),
		OpenedAt:              types.MustNewTimeFromString("2021-05-12T23:14:27.012Z"),
		ClosedAt:              nil,
		AccountNumber:         nil,
		Ach: &operations.UpdateSyntheticAccountAchResponse{
			AccountType:      operations.UpdateSyntheticAccountAccountTypeResponseChecking.ToPointer(),
			CounterpartyName: types.String("Arnold Arnoldson"),
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}
