// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"fmt"
	"log"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/operations"
	"mockserver/internal/sdk/optionalnullable"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathGetTransactions(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "get_/transactions-transactions[0]":
			dir.HandlerFunc("get_/transactions", testGetTransactionsGetTransactionsTransactions0)(w, req)
		case "get_/transactions-transactions_with_denials[0]":
			dir.HandlerFunc("get_/transactions", testGetTransactionsGetTransactionsTransactionsWithDenials0)(w, req)
		default:
			http.Error(w, fmt.Sprintf("Unknown test: %s[%d]", test, count), http.StatusBadRequest)
		}
	}
}

func testGetTransactionsGetTransactionsTransactions0(w http.ResponseWriter, req *http.Request) {
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.GetTransactionsResponseBody = &operations.GetTransactionsResponseBody{
		TotalCount: types.Int64(24),
		Count:      types.Int64(8),
		Limit:      types.Int64(8),
		Offset:     types.Int64(1),
		Data: []operations.GetTransactionsData{
			operations.GetTransactionsData{
				UID:           types.String("SMwKC1osz77DTEiu"),
				ID:            types.Int64(27),
				AdjustmentUID: nil,
				CustomerUID:   types.String("Trzqy9t6j6tFGoG3"),
				CreatedAt:     types.MustNewTimeFromString("2019-10-15T15:53:13.591Z"),
				CustodialAccountUids: []string{
					"Gw4gr1T81YrvLT6M",
					"66gso857LyQWC6XN",
				},
				Description:                    types.String("Transfer from \"Bank ABC\" to \"Emergency Cupcake Funds\""),
				DestinationSyntheticAccountUID: types.String("15gTLPAEzHxtSrU6"),
				InitialActionAt:                types.MustNewTimeFromString("2019-10-15T15:53:13.586Z"),
				NetAsset:                       operations.GetTransactionsNetAssetPositive.ToPointer(),
				ReturnUID:                      nil,
				SettledAt:                      types.MustNewTimeFromString("2019-10-16T12:51:12.673Z"),
				SettledIndex:                   optionalnullable.From(types.Int64(8)),
				SourceSyntheticAccountUID:      types.String("rJuYjZuLei2TZji9"),
				StatementPostedAt:              optionalnullable.From(types.MustNewTimeFromString("2019-10-17T00:01:53.682Z")),
				Status:                         operations.GetTransactionsDataStatusSettled.ToPointer(),
				TransactionBatchUID:            optionalnullable.From(types.String("3")),
				TransactionEventUids: []string{
					"MB2yqBrm3c4bUbou",
				},
				TransferUID:               optionalnullable.From(types.String("1qVSAEjsV55vDZxX")),
				Type:                      operations.GetTransactionsDataTypeAch.ToPointer(),
				UsDollarAmount:            types.String("5.21"),
				VirtualReferenceNumberUID: types.String("<id>"),
				Ach: &operations.GetTransactionsAch{
					OriginatorName:           types.String("Mr. Original"),
					CompanyID:                types.String("ABC654"),
					CompanyDiscretionaryData: types.String("Shhhh"),
					Prenote:                  types.Bool(false),
					SecCode:                  operations.GetTransactionsSecCodeCcd.ToPointer(),
					PaymentType:              operations.GetTransactionsPaymentTypeS.ToPointer(),
					EntryDescription:         types.String("Excellent entry"),
					ServiceProcessing:        operations.GetTransactionsServiceProcessingStandard.ToPointer(),
					EffectiveEntryDate:       types.String("2023-12-12"),
					IDNumber:                 types.String("543-DEF"),
					AchReturnCode:            types.String("<value>"),
					AchReturnReason:          types.String("<value>"),
					NocCode:                  types.String("C04"),
					NocReason:                types.String("Bank account name change"),
					TransferTraceID:          types.String("A1Z2b3y4c5x6DW78"),
					OriginatorRoutingNumber:  types.String("123456789"),
					CounterpartyName:         types.String("Receiver Account Name"),
					Iat: &operations.GetTransactionsIat{
						ForeignExchangeIndicator:          types.String("FF"),
						ForeignExchangeReferenceIndicator: types.String("3"),
						ForeignExchangeReference:          types.String("<value>"),
						IsoDestinationCountryCode:         types.String("US"),
						IsoOriginatingCurrencyCode:        types.String("USD"),
						IsoDestinationCurrencyCode:        types.String("USD"),
						TransactionCode:                   types.String("22"),
						TransactionTypeCode:               types.String("MIS"),
						ForeignPaymentAmount:              types.String("<value>"),
						ForeignTraceNumber:                types.String("<value>"),
						OriginatorStreetAddress:           types.String("410 TERRY AVENUE NORTH"),
						OriginatorCityStateProvince:       types.String("SEATTLE*WA"),
						OriginatorCountryPostalCode:       types.String("US*98109"),
						OdfiName:                          types.String("BANK OF AMERICA NA"),
						OdfiIdentificationNumberQualifier: types.String("01"),
						OdfiID:                            types.String("121000358"),
						OdfiBranchCountryCode:             types.String("US"),
						RdfiName:                          types.String("FIFTH THIRD BANK NATIONAL ASSOCIA"),
						RdfiIdentificationNumberQualifier: types.String("01"),
						RdfiID:                            types.String("071919133"),
						RdfiBranchCountryCode:             types.String("US"),
						CounterpartyStreetAddress:         types.String("228 S BURNS"),
						CounterpartyCityStateProvince:     types.String("INDEPEDENCE*KS"),
						CounterpartyCountryPostalCode:     types.String("US*67301"),
						PaymentRelatedInformation1:        types.String("NTE*ADD*FCS003348198932 PAYMENT-NUM  351380\\\\NTE*ADD*601 POP GOODS AND SERVICES"),
						PaymentRelatedInformation2:        types.String("<value>"),
						ForeignCorrespondentBanks: []operations.GetTransactionsForeignCorrespondentBank{
							operations.GetTransactionsForeignCorrespondentBank{
								Name:              types.String("BANK OF AMERICA CANADA"),
								IDNumberQualifier: types.String("01"),
								IDNumber:          types.String("121000358"),
								BranchCountryCode: types.String("CA"),
							},
						},
					},
				},
			},
			operations.GetTransactionsData{
				UID:           types.String("SMwKC1osz77DTEiu"),
				ID:            types.Int64(40),
				AdjustmentUID: nil,
				CustomerUID:   types.String("Trzqy9t6j6tFGoG3"),
				CreatedAt:     types.MustNewTimeFromString("2023-07-17T07:07:07.707Z"),
				CustodialAccountUids: []string{
					"Gw4gr1T81YrvLT6M",
					"66gso857LyQWC6XN",
				},
				Description:                    types.String("ACH return debited from 15gTLPAEzHxtSrU6"),
				DestinationSyntheticAccountUID: types.String("rJuYjZuLei2TZji9"),
				InitialActionAt:                types.MustNewTimeFromString("2023-07-17T07:07:07.707Z"),
				NetAsset:                       operations.GetTransactionsNetAssetNegative.ToPointer(),
				ReturnUID:                      optionalnullable.From(types.String("9ZZ87saSFLkkDG7z")),
				SettledAt:                      types.MustNewTimeFromString("2023-07-17T09:07:07.707Z"),
				SettledIndex:                   optionalnullable.From(types.Int64(8)),
				SourceSyntheticAccountUID:      types.String("15gTLPAEzHxtSrU6"),
				StatementPostedAt:              optionalnullable.From(types.MustNewTimeFromString("2019-10-17T00:01:53.682Z")),
				Status:                         operations.GetTransactionsDataStatusSettled.ToPointer(),
				TransactionBatchUID:            optionalnullable.From(types.String("3")),
				TransactionEventUids: []string{
					"MB2yqBrm3c4bUbou",
				},
				TransferUID:               optionalnullable.From(types.String("1qVSAEjsV55vDZxX")),
				Type:                      operations.GetTransactionsDataTypeInitiatedAchReturn.ToPointer(),
				UsDollarAmount:            types.String("5.21"),
				VirtualReferenceNumberUID: types.String("<id>"),
				Ach: &operations.GetTransactionsAch{
					OriginatorName:           types.String("Mr. Original"),
					CompanyID:                types.String("ABC654ZY12"),
					CompanyDiscretionaryData: types.String("Shhhh"),
					Prenote:                  types.Bool(false),
					SecCode:                  operations.GetTransactionsSecCodeCcd.ToPointer(),
					PaymentType:              operations.GetTransactionsPaymentTypeS.ToPointer(),
					EntryDescription:         types.String("Excellent entry"),
					ServiceProcessing:        operations.GetTransactionsServiceProcessingStandard.ToPointer(),
					EffectiveEntryDate:       types.String("2023-12-12"),
					IDNumber:                 types.String("543-DEF"),
					AchReturnCode:            types.String("R02"),
					AchReturnReason:          types.String("Account closed"),
					NocCode:                  types.String("<value>"),
					NocReason:                types.String("<value>"),
					TransferTraceID:          types.String("A1Z2b3y4c5x6DW78"),
					OriginatorRoutingNumber:  types.String("123456789"),
					CounterpartyName:         types.String("Marge's Roofing Inc"),
				},
			},
			operations.GetTransactionsData{
				UID:           types.String("67r1gjrkgvYBR6EX"),
				ID:            types.Int64(41),
				AdjustmentUID: nil,
				CustomerUID:   types.String("o1gSDeWvEt45Yuaa"),
				CreatedAt:     types.MustNewTimeFromString("2023-07-17T07:07:07.707Z"),
				CustodialAccountUids: []string{
					"Jz1wjmm1cMyMkqmp",
				},
				Description:                    types.String("Wire return debited from pA7zLNS3BtSADfDh"),
				DestinationSyntheticAccountUID: types.String("PK3hKtXsfsJ2pfGR"),
				InitialActionAt:                types.MustNewTimeFromString("2023-07-17T07:07:07.707Z"),
				NetAsset:                       operations.GetTransactionsNetAssetNegative.ToPointer(),
				ReturnUID:                      optionalnullable.From(types.String("9ZZ87saSFLkkDG7z")),
				SettledAt:                      types.MustNewTimeFromString("2023-07-17T09:07:07.707Z"),
				SettledIndex:                   optionalnullable.From(types.Int64(8)),
				SourceSyntheticAccountUID:      types.String("pA7zLNS3BtSADfDh"),
				StatementPostedAt:              nil,
				Status:                         operations.GetTransactionsDataStatusPending.ToPointer(),
				TransactionBatchUID:            nil,
				TransactionEventUids:           []string{},
				TransferUID:                    nil,
				Type:                           operations.GetTransactionsDataTypeInitiatedWireReturn.ToPointer(),
				UsDollarAmount:                 types.String("5595.00"),
				VirtualReferenceNumberUID:      types.String("<id>"),
				Wire: &operations.GetTransactionsWire{
					CounterpartyName: "Ultimate Window Installers,",
					CounterpartyBankAddress: optionalnullable.From(&operations.GetTransactionsWireCounterpartyBankAddress{
						Line1: types.String("101 Common St"),
						Line2: types.String("Boring, Oregon 97009"),
						Line3: types.String("Coxsackie NY 12051 US"),
					}),
					CounterpartyBankName:          optionalnullable.From(types.String("ACME Bank")),
					CounterpartyBankRoutingNumber: types.String("123456789"),
					IntermediaryBankAddress: &operations.GetTransactionsIntermediaryBankAddress{
						Line1: optionalnullable.From(types.String("202 Another St")),
						Line2: optionalnullable.From(types.String("Calcium, NY 13616")),
						Line3: nil,
					},
					IntermediaryBankName:          types.String("General Bank of Calcium"),
					IntermediaryBankRoutingNumber: types.String("987654321"),
					Chips:                         nil,
					Imad:                          optionalnullable.From(types.String("20240510NHXPVPQY232293")),
					Uetr:                          nil,
				},
			},
			operations.GetTransactionsData{
				UID:           types.String("7PpuQuEz9FR8VeQt"),
				ID:            types.Int64(39),
				AdjustmentUID: nil,
				CustomerUID:   types.String("szaxXExVVScwKqPT"),
				CreatedAt:     types.MustNewTimeFromString("2023-07-17T07:07:07.707Z"),
				CustodialAccountUids: []string{
					"s5DQw78BKi5ye7CX",
					"EffzWWZztHo4B3XM",
				},
				Description:                    types.String("Sent RTP ID 20231004043000096P1BAAAA00041250796 to Rupert's Roofers of Raleigh"),
				DestinationSyntheticAccountUID: types.String("smfVbCVA4iqHUkUX"),
				InitialActionAt:                types.MustNewTimeFromString("2023-07-17T07:07:07.707Z"),
				NetAsset:                       operations.GetTransactionsNetAssetNegative.ToPointer(),
				ReturnUID:                      nil,
				SettledAt:                      types.MustNewTimeFromString("2023-07-17T09:07:07.707Z"),
				SettledIndex:                   optionalnullable.From(types.Int64(10)),
				SourceSyntheticAccountUID:      types.String("H2uQrLRNAfQr3WLn"),
				StatementPostedAt:              optionalnullable.From(types.MustNewTimeFromString("2019-10-17T00:01:53.682Z")),
				Status:                         operations.GetTransactionsDataStatusSettled.ToPointer(),
				TransactionBatchUID:            optionalnullable.From(types.String("3")),
				TransactionEventUids: []string{
					"TzqSj2r6NN5MMYu9",
				},
				TransferUID:               nil,
				Type:                      operations.GetTransactionsDataTypeInstantPayment.ToPointer(),
				UsDollarAmount:            types.String("13500.45"),
				VirtualReferenceNumberUID: types.String("rdPjBZeKfpGZgaT1"),
				InstantPayment: &operations.GetTransactionsInstantPayment{
					NetworkTransactionID:              types.String("20231004043000096P1BAAAA00041250796"),
					Network:                           types.String("fednow"),
					FailureCode:                       types.String("ERR100"),
					FailureReason:                     types.String("Account number invalid or missing"),
					CounterpartyName:                  types.String("Marge's Roofing Inc"),
					CounterpartyBankName:              types.String("East West Regional Bank"),
					CounterpartyBankRoutingNumber:     types.String("123456789"),
					CounterpartyAccountNumberLastFour: types.String("3345"),
					PaymentID:                         types.String("BayleeStacy"),
					OriginalEndToEndID:                optionalnullable.From(types.String("null,")),
					TransmitterName:                   types.String("Rupert's Roofers of Raleigh"),
					InitiatingPartyName:               types.String("Rupert's Roofers of Raleigh"),
					CounterpartyBankAddress: optionalnullable.From(&operations.GetTransactionsInstantPaymentCounterpartyBankAddress{
						StreetNumber: "789",
						Street1:      "Bank Blvd.",
						Street2:      types.String("Suite 4A"),
						City:         types.String("Raleigh"),
						State:        types.String("NC"),
						PostalCode:   types.String("27602"),
						Country:      types.String("US"),
					}),
				},
			},
			operations.GetTransactionsData{
				UID:           types.String("67r1gjrkgvYBR6EX"),
				ID:            types.Int64(32),
				AdjustmentUID: nil,
				CustomerUID:   types.String("Trzqy9t6j6tFGoG3"),
				CreatedAt:     types.MustNewTimeFromString("2019-11-15T15:53:13.591Z"),
				CustodialAccountUids: []string{
					"Jz1wjmm1cMyMkqmp",
					"kchtGUEurq3U4Q3b",
				},
				Description:                    types.String("Transfer from \"Home Savings\" to \"Ultimate Window Installers Inc.\""),
				DestinationSyntheticAccountUID: types.String("BUuRwEKGHkNEbDoF"),
				InitialActionAt:                types.MustNewTimeFromString("2019-11-15T15:53:13.586Z"),
				NetAsset:                       operations.GetTransactionsNetAssetPositive.ToPointer(),
				ReturnUID:                      nil,
				SettledAt:                      types.MustNewTimeFromString("2019-11-17T12:51:12.673Z"),
				SettledIndex:                   optionalnullable.From(types.Int64(8)),
				SourceSyntheticAccountUID:      types.String("pA7zLNS3BtSADfDh"),
				StatementPostedAt:              optionalnullable.From(types.MustNewTimeFromString("2019-10-17T00:01:53.682Z")),
				Status:                         operations.GetTransactionsDataStatusSettled.ToPointer(),
				TransactionBatchUID:            optionalnullable.From(types.String("3")),
				TransactionEventUids: []string{
					"C2xRgpfdyqgbRoJs",
				},
				TransferUID:               optionalnullable.From(types.String("LEbStJ7MFSniq18h")),
				Type:                      operations.GetTransactionsDataTypeWire.ToPointer(),
				UsDollarAmount:            types.String("5595.00"),
				VirtualReferenceNumberUID: types.String("<id>"),
				Authorization: &operations.GetTransactionsAuthorization{
					AuthorizationFinalizedAt: types.MustNewTimeFromString("2019-11-15T20:37:09.904Z"),
					AuthorizationRequiredBy:  types.MustNewTimeFromString("2019-11-16T15:53:13.586Z"),
					AuthorizationStatus:      operations.GetTransactionsAuthorizationStatusClientApproved.ToPointer(),
					DeniedMemo:               types.String("denied memo"),
					DeniedReason:             types.String("vrn_archived"),
				},
				Wire: &operations.GetTransactionsWire{
					CounterpartyName: "Ultimate Window Installers",
					CounterpartyBankAddress: optionalnullable.From(&operations.GetTransactionsWireCounterpartyBankAddress{
						Line1: types.String("101 Common St"),
						Line2: types.String("Boring, Oregon 97009"),
						Line3: types.String("Coxsackie NY 12051 US"),
					}),
					CounterpartyBankName:          optionalnullable.From(types.String("ACME Bank")),
					CounterpartyBankRoutingNumber: types.String("123456789"),
					IntermediaryBankAddress: &operations.GetTransactionsIntermediaryBankAddress{
						Line1: optionalnullable.From(types.String("202 Another St")),
						Line2: optionalnullable.From(types.String("Calcium, NY 13616")),
						Line3: nil,
					},
					IntermediaryBankName:            types.String("General Bank of Calcium"),
					IntermediaryBankRoutingNumber:   types.String("987654321"),
					Chips:                           optionalnullable.From(types.String("1234567")),
					Imad:                            nil,
					Uetr:                            nil,
					BankToBankInfo:                  optionalnullable.From(types.String("/DAS/REF:55555ZZ000ZZ")),
					OriginatorAccountNumberLastFour: optionalnullable.From(types.String("1234")),
				},
			},
			operations.GetTransactionsData{
				UID:           types.String("YBHNH3BgykqrjLgz"),
				ID:            types.Int64(33),
				AdjustmentUID: nil,
				CustomerUID:   types.String("KrWPzr5PMQYJXpuY"),
				CreatedAt:     types.MustNewTimeFromString("2019-12-14T03:21:53.301Z"),
				CustodialAccountUids: []string{
					"HbkmGjUZJsnRUnrB",
					"Gw4gr1T81YrvLT6M",
					"e3sEiUHmfEpt4NHM",
				},
				Description:                    types.String("Transfer from \"Clothing Branding installation\" to \"deposit architect hack\""),
				DestinationSyntheticAccountUID: types.String("exMDShw6yM3NHLYV"),
				InitialActionAt:                types.MustNewTimeFromString("2019-12-14T03:21:53.295Z"),
				NetAsset:                       operations.GetTransactionsNetAssetNeutral.ToPointer(),
				ReturnUID:                      nil,
				SettledAt:                      types.MustNewTimeFromString("2019-12-17T00:01:53.682Z"),
				SettledIndex:                   optionalnullable.From(types.Int64(9)),
				SourceSyntheticAccountUID:      types.String("4XkJnsfHsuqrxmeX"),
				StatementPostedAt:              optionalnullable.From(types.MustNewTimeFromString("2019-10-17T00:01:53.682Z")),
				Status:                         operations.GetTransactionsDataStatusSettled.ToPointer(),
				TransactionBatchUID:            optionalnullable.From(types.String("3")),
				TransactionEventUids: []string{
					"26FR8BBPDG2AXXny",
					"wRmMXSfZZr3igDnc",
				},
				TransferUID:               optionalnullable.From(types.String("Q9qAuwpBQqhqv2Fy")),
				Type:                      operations.GetTransactionsDataTypeBookTransfer.ToPointer(),
				UsDollarAmount:            types.String("12.34"),
				VirtualReferenceNumberUID: types.String("<id>"),
			},
			operations.GetTransactionsData{
				UID:           types.String("pvNS1sN5Y5chbRdy"),
				ID:            types.Int64(37),
				AdjustmentUID: optionalnullable.From(types.String("AP8tE12ewjXFq6eL")),
				CustomerUID:   types.String("pRWHTjprnfdSzKW6"),
				CreatedAt:     types.MustNewTimeFromString("2021-10-14T03:21:53.301Z"),
				CustodialAccountUids: []string{
					"n6XxSDyFZbNiV9JM",
				},
				Description:                    types.String("Credit for Loyalty Rewards"),
				DestinationSyntheticAccountUID: types.String("smfVbCVA4iqHUkUX"),
				InitialActionAt:                types.MustNewTimeFromString("2021-10-14T03:21:53.297Z"),
				NetAsset:                       operations.GetTransactionsNetAssetNegative.ToPointer(),
				ReturnUID:                      nil,
				SettledAt:                      types.MustNewTimeFromString("2021-10-17T00:01:53.682Z"),
				SettledIndex:                   optionalnullable.From(types.Int64(10)),
				SourceSyntheticAccountUID:      types.String("P2uQrLRNAfQr3WLn"),
				Status:                         operations.GetTransactionsDataStatusSettled.ToPointer(),
				TransactionEventUids: []string{
					"azEYV4F1gm7VB5NE",
				},
				TransferUID:               nil,
				Type:                      operations.GetTransactionsDataTypeCredit.ToPointer(),
				UsDollarAmount:            types.String("2.50"),
				VirtualReferenceNumberUID: types.String("<id>"),
			},
			operations.GetTransactionsData{
				UID:           types.String("7PpuQuEz9FR8VeQt"),
				ID:            types.Int64(38),
				AdjustmentUID: nil,
				CustomerUID:   types.String("pRWHTjprnfdSzKW6"),
				CreatedAt:     types.MustNewTimeFromString("2021-10-14T03:21:53.301Z"),
				CustodialAccountUids: []string{
					"n6XxSDyFZbNiV9JM",
				},
				Description:                    types.String("302 - BOB'S WIDGETS SPRINGFIELD, VA"),
				DestinationSyntheticAccountUID: types.String("smfVbCVA4iqHUkUX"),
				InitialActionAt:                types.MustNewTimeFromString("2021-10-14T03:21:53.297Z"),
				NetAsset:                       operations.GetTransactionsNetAssetNegative.ToPointer(),
				ReturnUID:                      nil,
				SettledAt:                      types.MustNewTimeFromString("2021-10-17T00:01:53.682Z"),
				SettledIndex:                   optionalnullable.From(types.Int64(10)),
				SourceSyntheticAccountUID:      types.String("P2uQrLRNAfQr3WLn"),
				Status:                         operations.GetTransactionsDataStatusSettled.ToPointer(),
				TransactionEventUids: []string{
					"5rxwPFs76WEb8Apu",
				},
				TransferUID:               nil,
				Type:                      operations.GetTransactionsDataTypeCardPurchase.ToPointer(),
				UsDollarAmount:            types.String("3.50"),
				VirtualReferenceNumberUID: types.String("<id>"),
			},
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}

func testGetTransactionsGetTransactionsTransactionsWithDenials0(w http.ResponseWriter, req *http.Request) {
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.GetTransactionsResponseBody = &operations.GetTransactionsResponseBody{
		TotalCount: types.Int64(24),
		Count:      types.Int64(7),
		Limit:      types.Int64(7),
		Offset:     types.Int64(0),
		Data: []operations.GetTransactionsData{
			operations.GetTransactionsData{
				UID:           types.String("1PpuQuEz9FR8VeQt"),
				ID:            types.Int64(30),
				AdjustmentUID: optionalnullable.From(types.String("AP8tE12ewjXFq6eL")),
				CreatedAt:     types.MustNewTimeFromString("2022-06-03T03:21:53.301Z"),
				CustodialAccountUids: []string{
					"a8XxSDyFZbNiV9JM",
				},
				Description:                    types.String("302 - BOB'S WIDGETS SPRINGFIELD, VA"),
				DestinationSyntheticAccountUID: types.String("amfVbCVA4iqHUkUX"),
				InitialActionAt:                types.MustNewTimeFromString("2022-06-03T03:21:53.297Z"),
				NetAsset:                       operations.GetTransactionsNetAssetNeutral.ToPointer(),
				SettledAt:                      types.MustNewTimeFromString("2019-10-17T00:01:53.682Z"),
				SettledIndex:                   nil,
				SourceSyntheticAccountUID:      types.String("A2uQrLRNAfQr3WLn"),
				Status:                         operations.GetTransactionsDataStatusDenied.ToPointer(),
				TransactionEventUids: []string{
					"[\"MB2yqBrm3c4bUbou\",\"qCEEyGQw73Ajn3WZ\"]",
				},
				TransferUID:    nil,
				Type:           operations.GetTransactionsDataTypeCardPurchase.ToPointer(),
				UsDollarAmount: types.String("0"),
			},
			operations.GetTransactionsData{
				UID:           types.String("2PpuQuEz9FR8VeQt"),
				ID:            types.Int64(31),
				AdjustmentUID: optionalnullable.From(types.String("BP8tE12ewjXFq6eL")),
				CreatedAt:     types.MustNewTimeFromString("2022-06-04T03:21:53.301Z"),
				CustodialAccountUids: []string{
					"b8XxSDyFZbNiV9JM",
				},
				Description:                    types.String("302 - BOB'S WIDGETS SPRINGFIELD, VA"),
				DestinationSyntheticAccountUID: types.String("bmfVbCVA4iqHUkUX"),
				InitialActionAt:                types.MustNewTimeFromString("2022-06-04T03:21:53.297Z"),
				NetAsset:                       operations.GetTransactionsNetAssetNeutral.ToPointer(),
				SettledAt:                      types.MustNewTimeFromString("2019-10-17T00:01:53.682Z"),
				SettledIndex:                   nil,
				SourceSyntheticAccountUID:      types.String("B2uQrLRNAfQr3WLn"),
				Status:                         operations.GetTransactionsDataStatusDenied.ToPointer(),
				TransactionEventUids: []string{
					"[\"MB2yqBrm3c4bUbou\",\"qCEEyGQw73Ajn3WZ\"]",
				},
				TransferUID:    nil,
				Type:           operations.GetTransactionsDataTypeCardPurchase.ToPointer(),
				UsDollarAmount: types.String("0"),
			},
			operations.GetTransactionsData{
				UID:           types.String("3PpuQuEz9FR8VeQt"),
				ID:            types.Int64(32),
				AdjustmentUID: optionalnullable.From(types.String("CP8tE12ewjXFq6eL")),
				CreatedAt:     types.MustNewTimeFromString("2021-10-05T03:21:53.301Z"),
				CustodialAccountUids: []string{
					"c6XxSDyFZbNiV9JM",
				},
				Description:                    types.String("302 - BOB'S WIDGETS SPRINGFIELD, VA"),
				DestinationSyntheticAccountUID: types.String("smfVbCVA4iqHUkUX"),
				InitialActionAt:                types.MustNewTimeFromString("2021-10-05T03:21:53.297Z"),
				NetAsset:                       operations.GetTransactionsNetAssetPositive.ToPointer(),
				SettledAt:                      types.MustNewTimeFromString("2019-10-17T00:01:53.682Z"),
				SettledIndex:                   nil,
				SourceSyntheticAccountUID:      types.String("C2uQrLRNAfQr3WLn"),
				Status:                         operations.GetTransactionsDataStatusDenied.ToPointer(),
				TransactionEventUids: []string{
					"[\"MB2yqBrm3c4bUbou\",\"qCEEyGQw73Ajn3WZ\"]",
				},
				TransferUID:    nil,
				Type:           operations.GetTransactionsDataTypeCardPurchase.ToPointer(),
				UsDollarAmount: types.String("3.50"),
			},
			operations.GetTransactionsData{
				UID:           types.String("4PpuQuEz9FR8VeQt"),
				ID:            types.Int64(33),
				AdjustmentUID: optionalnullable.From(types.String("DT8tE12ewjXFq6eL")),
				CreatedAt:     types.MustNewTimeFromString("2022-06-06T03:21:53.301Z"),
				CustodialAccountUids: []string{
					"d8XxSDyFZbNiV9JM",
				},
				Description:                    types.String("302 - BOB'S WIDGETS SPRINGFIELD, VA"),
				DestinationSyntheticAccountUID: types.String("smfVbCVA4iqHUkUX"),
				InitialActionAt:                types.MustNewTimeFromString("2022-06-06T03:21:53.297Z"),
				NetAsset:                       operations.GetTransactionsNetAssetPositive.ToPointer(),
				SettledAt:                      types.MustNewTimeFromString("2019-10-17T00:01:53.682Z"),
				SettledIndex:                   nil,
				SourceSyntheticAccountUID:      types.String("D2uQrLRNAfQr3WLn"),
				Status:                         operations.GetTransactionsDataStatusDenied.ToPointer(),
				TransactionEventUids: []string{
					"[\"MB2yqBrm3c4bUbou\",\"qCEEyGQw73Ajn3WZ\"]",
				},
				TransferUID:    nil,
				Type:           operations.GetTransactionsDataTypeCardPurchase.ToPointer(),
				UsDollarAmount: types.String("13.50"),
			},
			operations.GetTransactionsData{
				UID:           types.String("5PpuQuEz9FR8VeQt"),
				ID:            types.Int64(34),
				AdjustmentUID: optionalnullable.From(types.String("EP8tE12ewjXFq6eL")),
				CreatedAt:     types.MustNewTimeFromString("2022-06-07T03:21:53.301Z"),
				CustodialAccountUids: []string{
					"e8XxSDyFZbNiV9JM",
				},
				Description:                    types.String("302 - BOB'S WIDGETS SPRINGFIELD, VA"),
				DestinationSyntheticAccountUID: types.String("smfVbCVA4iqHUkUX"),
				InitialActionAt:                types.MustNewTimeFromString("2022-06-07T03:21:53.297Z"),
				NetAsset:                       operations.GetTransactionsNetAssetPositive.ToPointer(),
				SettledAt:                      types.MustNewTimeFromString("2019-10-17T00:01:53.682Z"),
				SettledIndex:                   nil,
				SourceSyntheticAccountUID:      types.String("E2uQrLRNAfQr3WLn"),
				Status:                         operations.GetTransactionsDataStatusDenied.ToPointer(),
				TransactionEventUids: []string{
					"[\"MB2yqBrm3c4bUbou\",\"qCEEyGQw73Ajn3WZ\"]",
				},
				TransferUID:    nil,
				Type:           operations.GetTransactionsDataTypeCardPurchase.ToPointer(),
				UsDollarAmount: types.String("22.80"),
			},
			operations.GetTransactionsData{
				UID:           types.String("6PpuQuEz9FR8VeQt"),
				ID:            types.Int64(35),
				AdjustmentUID: optionalnullable.From(types.String("FP8tE12ewjXFq6eL")),
				CreatedAt:     types.MustNewTimeFromString("2022-06-08T03:21:53.301Z"),
				CustodialAccountUids: []string{
					"f8XxSDyFZbNiV9JM",
				},
				Description:                    types.String("302 - BOB'S WIDGETS SPRINGFIELD, VA"),
				DestinationSyntheticAccountUID: types.String("fmfVbCVA4iqHUkUX"),
				InitialActionAt:                types.MustNewTimeFromString("2022-06-08T03:21:53.297Z"),
				NetAsset:                       operations.GetTransactionsNetAssetPositive.ToPointer(),
				SettledAt:                      types.MustNewTimeFromString("2019-10-17T00:01:53.682Z"),
				SettledIndex:                   nil,
				SourceSyntheticAccountUID:      types.String("F2uQrLRNAfQr3WLn"),
				Status:                         operations.GetTransactionsDataStatusDenied.ToPointer(),
				TransactionEventUids: []string{
					"[\"MB2yqBrm3c4bUbou\",\"qCEEyGQw73Ajn3WZ\"]",
				},
				TransferUID:    nil,
				Type:           operations.GetTransactionsDataTypeCardPurchase.ToPointer(),
				UsDollarAmount: types.String("50.50"),
			},
			operations.GetTransactionsData{
				UID:           types.String("YBHNH3BgykqrjLgz"),
				ID:            types.Int64(36),
				AdjustmentUID: nil,
				CreatedAt:     types.MustNewTimeFromString("2019-10-14T03:21:53.301Z"),
				CustodialAccountUids: []string{
					"HbkmGjUZJsnRUnrB",
					"Gw4gr1T81YrvLT6M",
					"e3sEiUHmfEpt4NHM",
				},
				Description:                    types.String("Transfer from \"Clothing Branding installation\" to \"deposit architect hack\""),
				DestinationSyntheticAccountUID: types.String("exMDShw6yM3NHLYV"),
				InitialActionAt:                types.MustNewTimeFromString("2019-10-14T03:21:53.295Z"),
				NetAsset:                       operations.GetTransactionsNetAssetPositive.ToPointer(),
				SettledAt:                      types.MustNewTimeFromString("2019-10-17T00:01:53.682Z"),
				SettledIndex:                   optionalnullable.From(types.Int64(9)),
				SourceSyntheticAccountUID:      types.String("4XkJnsfHsuqrxmeX"),
				Status:                         operations.GetTransactionsDataStatusSettled.ToPointer(),
				TransactionEventUids: []string{
					"26FR8BBPDG2AXXny",
					"wRmMXSfZZr3igDnc",
				},
				TransferUID:    optionalnullable.From(types.String("Q9qAuwpBQqhqv2Fy")),
				Type:           operations.GetTransactionsDataTypeBookTransfer.ToPointer(),
				UsDollarAmount: types.String("12.34"),
			},
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}
