// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"fmt"
	"log"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/operations"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathPostReturns(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "post_/returns-ach[0]":
			dir.HandlerFunc("post_/returns", testPostReturnsPostReturnsAch0)(w, req)
		case "post_/returns-wire[0]":
			dir.HandlerFunc("post_/returns", testPostReturnsPostReturnsWire0)(w, req)
		case "post_/returns-created_return[0]":
			dir.HandlerFunc("post_/returns", testPostReturnsPostReturnsCreatedReturn0)(w, req)
		default:
			http.Error(w, fmt.Sprintf("Unknown test: %s[%d]", test, count), http.StatusBadRequest)
		}
	}
}

func testPostReturnsPostReturnsAch0(w http.ResponseWriter, req *http.Request) {
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.PostReturnsResponseBody = &operations.PostReturnsResponseBody{
		CreatedAt:              types.String("1711187420247"),
		ExternalUID:            types.String("YrfDrfVRgpPgnhF5"),
		OriginalTransactionUID: types.String("nwXnpBbX3A5sTki3"),
		CustomerUID:            types.String("Trzqy9t6j6tFGoG3"),
		RequestorType:          operations.PostReturnsRequestorTypeResponseCustomer.ToPointer(),
		ReturnReason:           types.String("Insufficient Funds"),
		ReturnTransactionUID:   types.String("SMwKC1osz77DTEiu"),
		Status:                 operations.PostReturnsStatusPending.ToPointer(),
		UID:                    types.String("dYTG8WAWAh5UyvY7"),
		Ach: &operations.PostReturnsAchResponse{
			AchReturnCode: operations.PostReturnsAchReturnCodeResponseR02.ToPointer(),
			AddendaInfo:   types.String("TXN0055BADD1E cancelled"),
		},
		Wire: &operations.PostReturnsWireResponse{
			WireInstructions: types.String("ORDER 5555555555"),
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_, _ = w.Write(respBodyBytes)
}

func testPostReturnsPostReturnsWire0(w http.ResponseWriter, req *http.Request) {
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.PostReturnsResponseBody = &operations.PostReturnsResponseBody{
		CreatedAt:              types.String("1711187420247"),
		ExternalUID:            types.String("YrfDrfVRgpPgnhF5"),
		OriginalTransactionUID: types.String("nwXnpBbX3A5sTki3"),
		CustomerUID:            types.String("Trzqy9t6j6tFGoG3"),
		RequestorType:          operations.PostReturnsRequestorTypeResponseCustomer.ToPointer(),
		ReturnReason:           types.String("Insufficient Funds"),
		ReturnTransactionUID:   types.String("SMwKC1osz77DTEiu"),
		Status:                 operations.PostReturnsStatusPending.ToPointer(),
		UID:                    types.String("dYTG8WAWAh5UyvY7"),
		Ach: &operations.PostReturnsAchResponse{
			AchReturnCode: operations.PostReturnsAchReturnCodeResponseR02.ToPointer(),
			AddendaInfo:   types.String("TXN0055BADD1E cancelled"),
		},
		Wire: &operations.PostReturnsWireResponse{
			WireInstructions: types.String("ORDER 5555555555"),
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_, _ = w.Write(respBodyBytes)
}

func testPostReturnsPostReturnsCreatedReturn0(w http.ResponseWriter, req *http.Request) {
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.PostReturnsResponseBody = &operations.PostReturnsResponseBody{
		CreatedAt:              types.String("2024-05-01T00:00:00.000Z"),
		ExternalUID:            types.String("null,"),
		OriginalTransactionUID: types.String("nwXnpBbX3A5sTki3"),
		CustomerUID:            types.String("Trzqy9t6j6tFGoG3"),
		RequestorType:          operations.PostReturnsRequestorTypeResponseCustomer.ToPointer(),
		ReturnReason:           types.String("RLYGR8CO RMA Z452208-13"),
		ReturnTransactionUID:   types.String("upKspzfHgAh47pHf"),
		Status:                 operations.PostReturnsStatusSettled.ToPointer(),
		UID:                    types.String("9ZZ87saSFLkkDG7z"),
		Ach: &operations.PostReturnsAchResponse{
			AchReturnCode: operations.PostReturnsAchReturnCodeResponseR02.ToPointer(),
			AddendaInfo:   types.String("TXN0055BADD1E cancelled"),
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_, _ = w.Write(respBodyBytes)
}
