// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"fmt"
	"log"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/operations"
	"mockserver/internal/sdk/optionalnullable"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathGetTransfers(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "listTransfers-transactions[0]":
			dir.HandlerFunc("listTransfers", testListTransfersListTransfersTransactions0)(w, req)
		default:
			http.Error(w, fmt.Sprintf("Unknown test: %s[%d]", test, count), http.StatusBadRequest)
		}
	}
}

func testListTransfersListTransfersTransactions0(w http.ResponseWriter, req *http.Request) {
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.ListTransfersResponseBody = &operations.ListTransfersResponseBody{
		TotalCount: types.Int64(3),
		Count:      types.Int64(3),
		Limit:      types.Int64(3),
		Offset:     types.Int64(1),
		Data: []operations.ListTransfersData{
			operations.ListTransfersData{
				SourceSyntheticAccountUID:      types.String("4XkJnsfHsuqrxmeX"),
				DestinationSyntheticAccountUID: types.String("exMDShw6yM3NHLYV"),
				InitiatingCustomerUID:          types.String("iDtmSA52zRhgN4iy"),
				DestinationCustomerUID:         types.String("iDtmSA52zRhgN4iy"),
				Status:                         operations.ListTransfersStatusPending.ToPointer(),
				InitiatorType:                  operations.ListTransfersInitiatorTypeTransmitter.ToPointer(),
				CreatedAt:                      types.MustNewTimeFromString("2019-10-14T03:21:53.301Z"),
				UID:                            types.String("EhrQZJNjCd79LLYq"),
				ExternalUID:                    types.String("partner-generated-id"),
				TransactionUids:                []string{},
				UsdTransferAmount:              types.String("33.12"),
				Wire: &operations.ListTransfersWire{
					IntermediaryBankAddress: &operations.ListTransfersIntermediaryBankAddress{
						Line1:   optionalnullable.From(types.String("345 Def Ave")),
						Line2:   optionalnullable.From(types.String("San Francisco")),
						Line3:   optionalnullable.From(types.String("CA 94016")),
						Country: optionalnullable.From(types.String("US")),
					},
					IntermediaryBankName:          types.String("Fidelity Fiduciary Bank"),
					IntermediaryBankRoutingNumber: types.String("923456789"),
					WireTransmitter: &operations.ListTransfersWireTransmitter{
						Name:                  "Top Tier Tacos",
						TransmitterIdentifier: "123456789",
						Line1:                 types.String("123 Abc St."),
						Country:               "US",
					},
				},
			},
			operations.ListTransfersData{
				SourceSyntheticAccountUID:      types.String("ABv3vs5yVypxpGgF"),
				DestinationSyntheticAccountUID: types.String("RRbw63TF4o1vg2RQ"),
				InitiatingCustomerUID:          types.String("oBugADTMCMEU4sfE"),
				DestinationCustomerUID:         types.String("22PBwMT88qCQWMSg"),
				Status:                         operations.ListTransfersStatusSettled.ToPointer(),
				InitiatorType:                  operations.ListTransfersInitiatorTypeTransmitter.ToPointer(),
				CreatedAt:                      types.MustNewTimeFromString("2019-10-14T03:21:53.301Z"),
				UID:                            types.String("VeYqeb1iHqBR4LEi"),
				ExternalUID:                    types.String("partner-created-id"),
				TransactionUids: []string{
					"d8WUMmm4dZfMpLeh",
				},
				UsdTransferAmount: types.String("32.13"),
				InstantPayment: &operations.ListTransfersInstantPayment{
					InstantPaymentTransmitter: &operations.ListTransfersInstantPaymentTransmitter{
						Name:                  "Royalty Asset Management",
						TransmitterIdentifier: "123456789",
						StreetNumber:          "123",
						Street1:               "Abc St.",
						City:                  types.String("Boring"),
						State:                 types.String("OR"),
						PostalCode:            types.String("97009"),
						Country:               nil,
					},
				},
			},
			operations.ListTransfersData{
				SourceSyntheticAccountUID:      types.String("4XkJnsfHsuqrxmeX"),
				DestinationSyntheticAccountUID: types.String("exMDShw6yM3NHLYV"),
				InitiatingCustomerUID:          types.String("iDtmSA52zRhgN4iy"),
				DestinationCustomerUID:         types.String("iDtmSA52zRhgN4iy"),
				Status:                         operations.ListTransfersStatusPending.ToPointer(),
				InitiatorType:                  operations.ListTransfersInitiatorTypeCustomer.ToPointer(),
				CreatedAt:                      types.MustNewTimeFromString("2019-10-14T03:21:53.301Z"),
				UID:                            types.String("EhrQZJNjCd79LLYq"),
				ExternalUID:                    types.String("partner-generated-id"),
				TransactionUids:                []string{},
				Ach: &operations.ListTransfersAch{
					OriginatorName:           types.String("Mr. Hyyt Meiser"),
					CompanyID:                types.String("HJK867"),
					CompanyDiscretionaryData: types.String("Some data"),
					Prenote:                  types.Bool(false),
					SecCode:                  operations.ListTransfersSecCodeCcd.ToPointer(),
					PaymentType:              operations.ListTransfersPaymentTypeS.ToPointer(),
					EntryDescription:         types.String("ACH Entry"),
					ServiceProcessing:        operations.ListTransfersServiceProcessingStandard.ToPointer(),
					EffectiveEntryDate:       types.String("2023-12-21"),
					IDNumber:                 types.String("4270465600"),
				},
			},
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}
