// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"fmt"
	"log"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/operations"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathGetPools(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "listPools-pool_list[0]":
			dir.HandlerFunc("listPools", testListPoolsListPoolsPoolList0)(w, req)
		default:
			http.Error(w, fmt.Sprintf("Unknown test: %s[%d]", test, count), http.StatusBadRequest)
		}
	}
}

func testListPoolsListPoolsPoolList0(w http.ResponseWriter, req *http.Request) {
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.ListPoolsResponseBody = &operations.ListPoolsResponseBody{
		TotalCount: types.Int64(4),
		Count:      types.Int64(2),
		Limit:      types.Int64(2),
		Offset:     types.Int64(0),
		Data: []operations.ListPoolsData{
			operations.ListPoolsData{
				UID:              types.String("wTSMX1GubP21ev2h"),
				Name:             "multi-byte success",
				OwnerCustomerUID: "uKxmLxUEiSj5h4M3",
				CustomerUids: []string{
					"uKxmLxUEiSj5h4M3",
					"ivxTYrJtwrMC4f6w",
				},
			},
			operations.ListPoolsData{
				UID:              types.String("7UvkHn3Ss9AbWe2c"),
				Name:             "Fundamental Frozen",
				OwnerCustomerUID: "y9reyPMNEWuuYSC1",
				CustomerUids: []string{
					"y9reyPMNEWuuYSC1",
					"6TbfhQFQteurvK3Y",
				},
			},
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}
