// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"fmt"
	"log"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/operations"
	"mockserver/internal/sdk/optionalnullable"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathPostCustomers(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "createCustomer-primary[0]":
			dir.HandlerFunc("createCustomer", testCreateCustomerCreateCustomerPrimary0)(w, req)
		case "createCustomer-secondary[0]":
			dir.HandlerFunc("createCustomer", testCreateCustomerCreateCustomerSecondary0)(w, req)
		case "createCustomer-primary-empty[0]":
			dir.HandlerFunc("createCustomer", testCreateCustomerCreateCustomerPrimaryEmpty0)(w, req)
		case "createCustomer-empty_customer[0]":
			dir.HandlerFunc("createCustomer", testCreateCustomerCreateCustomerEmptyCustomer0)(w, req)
		default:
			http.Error(w, fmt.Sprintf("Unknown test: %s[%d]", test, count), http.StatusBadRequest)
		}
	}
}

func testCreateCustomerCreateCustomerPrimary0(w http.ResponseWriter, req *http.Request) {
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.CreateCustomerResponseBody = &operations.CreateCustomerResponseBody{
		UID:            types.String("EhrQZJNjCd79LLYq"),
		ExternalUID:    types.String("partner-generated-id"),
		ActivatedAt:    types.MustNewTimeFromString("2019-10-15T03:21:53.301Z"),
		CreatedAt:      types.MustNewTimeFromString("2019-10-14T03:21:53.301Z"),
		CustomerType:   operations.CreateCustomerCustomerTypeResponsePrimary.ToPointer(),
		Email:          types.String("olive.oyl@newline53.com"),
		ClientVerified: types.Bool(false),
		LockReason:     nil,
		LockedAt:       nil,
		PiiConfirmedAt: types.MustNewTimeFromString("2020-10-14T03:21:53.301Z"),
		PoolUids: []string{
			"HiuQZJNjCd79LLYq, NoPJB9g9ZQTh5qMv",
		},
		PrimaryCustomerUID: nil,
		ProfileResponses: []operations.CreateCustomerProfileResponse{
			operations.CreateCustomerProfileResponse{
				ProfileRequirement:    types.String("Please provide your approximate annual income in USD."),
				ProfileResponse:       types.String("Profile response"),
				ProfileRequirementUID: types.String("ptRLF7nQvy8VoqM1"),
			},
		},
		ProgramUID:            types.String("kaxHFJnWvJxRJZxr"),
		SecondaryCustomerUids: nil,
		TotalBalance:          types.String("12345.67"),
		ArchivedAt:            nil,
		Details: &operations.CreateCustomerDetailsOutput{
			FirstName:    optionalnullable.From(types.String("Olive")),
			MiddleName:   optionalnullable.From(types.String("Olivia")),
			LastName:     optionalnullable.From(types.String("Oyl")),
			Suffix:       optionalnullable.From(types.String("Jr.")),
			Phone:        optionalnullable.From(types.String("5555551212")),
			BusinessName: optionalnullable.From(types.String("Oliver's Olive Emporium")),
			SsnLastFour:  optionalnullable.From(types.String("3333")),
			Dob:          optionalnullable.From(types.MustNewDateFromString("1919-12-08")),
			Address: &operations.CreateCustomerAddressResponse{
				Street1:    types.String("123 Abc St."),
				Street2:    optionalnullable.From(types.String("Suite 4A")),
				City:       types.String("Chicago"),
				State:      types.String("IL"),
				PostalCode: types.String("60301"),
			},
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_, _ = w.Write(respBodyBytes)
}

func testCreateCustomerCreateCustomerSecondary0(w http.ResponseWriter, req *http.Request) {
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.CreateCustomerResponseBody = &operations.CreateCustomerResponseBody{
		UID:            types.String("EhrQZJNjCd79LLYq"),
		ExternalUID:    types.String("partner-generated-id"),
		ActivatedAt:    types.MustNewTimeFromString("2019-10-15T03:21:53.301Z"),
		CreatedAt:      types.MustNewTimeFromString("2019-10-14T03:21:53.301Z"),
		CustomerType:   operations.CreateCustomerCustomerTypeResponsePrimary.ToPointer(),
		Email:          types.String("olive.oyl@newline53.com"),
		ClientVerified: types.Bool(false),
		LockReason:     nil,
		LockedAt:       nil,
		PiiConfirmedAt: types.MustNewTimeFromString("2020-10-14T03:21:53.301Z"),
		PoolUids: []string{
			"HiuQZJNjCd79LLYq, NoPJB9g9ZQTh5qMv",
		},
		PrimaryCustomerUID: nil,
		ProfileResponses: []operations.CreateCustomerProfileResponse{
			operations.CreateCustomerProfileResponse{
				ProfileRequirement:    types.String("Please provide your approximate annual income in USD."),
				ProfileResponse:       types.String("Profile response"),
				ProfileRequirementUID: types.String("ptRLF7nQvy8VoqM1"),
			},
		},
		ProgramUID:            types.String("kaxHFJnWvJxRJZxr"),
		SecondaryCustomerUids: nil,
		TotalBalance:          types.String("12345.67"),
		ArchivedAt:            nil,
		Details: &operations.CreateCustomerDetailsOutput{
			FirstName:    optionalnullable.From(types.String("Olive")),
			MiddleName:   optionalnullable.From(types.String("Olivia")),
			LastName:     optionalnullable.From(types.String("Oyl")),
			Suffix:       optionalnullable.From(types.String("Jr.")),
			Phone:        optionalnullable.From(types.String("5555551212")),
			BusinessName: optionalnullable.From(types.String("Oliver's Olive Emporium")),
			SsnLastFour:  optionalnullable.From(types.String("3333")),
			Dob:          optionalnullable.From(types.MustNewDateFromString("1919-12-08")),
			Address: &operations.CreateCustomerAddressResponse{
				Street1:    types.String("123 Abc St."),
				Street2:    optionalnullable.From(types.String("Suite 4A")),
				City:       types.String("Chicago"),
				State:      types.String("IL"),
				PostalCode: types.String("60301"),
			},
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_, _ = w.Write(respBodyBytes)
}

func testCreateCustomerCreateCustomerPrimaryEmpty0(w http.ResponseWriter, req *http.Request) {
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.CreateCustomerResponseBody = &operations.CreateCustomerResponseBody{
		UID:            types.String("EhrQZJNjCd79LLYq"),
		ExternalUID:    types.String("partner-generated-id"),
		ActivatedAt:    types.MustNewTimeFromString("2019-10-15T03:21:53.301Z"),
		CreatedAt:      types.MustNewTimeFromString("2019-10-14T03:21:53.301Z"),
		CustomerType:   operations.CreateCustomerCustomerTypeResponsePrimary.ToPointer(),
		Email:          types.String("olive.oyl@newline53.com"),
		ClientVerified: types.Bool(false),
		LockReason:     nil,
		LockedAt:       nil,
		PiiConfirmedAt: types.MustNewTimeFromString("2020-10-14T03:21:53.301Z"),
		PoolUids: []string{
			"HiuQZJNjCd79LLYq, NoPJB9g9ZQTh5qMv",
		},
		PrimaryCustomerUID: nil,
		ProfileResponses: []operations.CreateCustomerProfileResponse{
			operations.CreateCustomerProfileResponse{
				ProfileRequirement:    types.String("Please provide your approximate annual income in USD."),
				ProfileResponse:       types.String("Profile response"),
				ProfileRequirementUID: types.String("ptRLF7nQvy8VoqM1"),
			},
		},
		ProgramUID:            types.String("kaxHFJnWvJxRJZxr"),
		SecondaryCustomerUids: nil,
		TotalBalance:          types.String("12345.67"),
		ArchivedAt:            nil,
		Details: &operations.CreateCustomerDetailsOutput{
			FirstName:    optionalnullable.From(types.String("Olive")),
			MiddleName:   optionalnullable.From(types.String("Olivia")),
			LastName:     optionalnullable.From(types.String("Oyl")),
			Suffix:       optionalnullable.From(types.String("Jr.")),
			Phone:        optionalnullable.From(types.String("5555551212")),
			BusinessName: optionalnullable.From(types.String("Oliver's Olive Emporium")),
			SsnLastFour:  optionalnullable.From(types.String("3333")),
			Dob:          optionalnullable.From(types.MustNewDateFromString("1919-12-08")),
			Address: &operations.CreateCustomerAddressResponse{
				Street1:    types.String("123 Abc St."),
				Street2:    optionalnullable.From(types.String("Suite 4A")),
				City:       types.String("Chicago"),
				State:      types.String("IL"),
				PostalCode: types.String("60301"),
			},
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_, _ = w.Write(respBodyBytes)
}

func testCreateCustomerCreateCustomerEmptyCustomer0(w http.ResponseWriter, req *http.Request) {
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.CreateCustomerResponseBody = &operations.CreateCustomerResponseBody{
		UID:            types.String("uKxmLxUEiSj5h4M3"),
		ExternalUID:    types.String("0396a8f6-37d5-4386-bb63-86987ac88132"),
		ActivatedAt:    types.MustNewTimeFromString("2019-10-16T03:21:53.301Z"),
		CreatedAt:      types.MustNewTimeFromString("2019-10-15T03:21:53.301Z"),
		CustomerType:   operations.CreateCustomerCustomerTypeResponsePrimary.ToPointer(),
		Email:          types.String("Cletus_Borer@hotmail.com"),
		ClientVerified: types.Bool(false),
		KycStatus:      nil,
		LockReason:     nil,
		LockedAt:       nil,
		PoolUids: []string{
			"1rNd8vRVa4GX84vi",
		},
		PrimaryCustomerUID:    nil,
		ProgramUID:            types.String("Sw9DjTGJq5L1ctZN"),
		SecondaryCustomerUids: optionalnullable.From(types.Pointer([]string{})),
		Status:                operations.CreateCustomerStatusInitiated.ToPointer(),
		TotalBalance:          types.String("0"),
		ArchivedAt:            nil,
		Details: &operations.CreateCustomerDetailsOutput{
			FirstName:  nil,
			MiddleName: nil,
			LastName:   nil,
			Suffix:     nil,
			Phone:      nil,
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_, _ = w.Write(respBodyBytes)
}
