// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"fmt"
	"log"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/operations"
	"mockserver/internal/sdk/optionalnullable"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathGetCustodialLineItems(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "get_/custodial_line_items-custodialLineItems[0]":
			dir.HandlerFunc("get_/custodial_line_items", testGetCustodialLineItemsGetCustodialLineItemsCustodialLineItems0)(w, req)
		default:
			http.Error(w, fmt.Sprintf("Unknown test: %s[%d]", test, count), http.StatusBadRequest)
		}
	}
}

func testGetCustodialLineItemsGetCustodialLineItemsCustodialLineItems0(w http.ResponseWriter, req *http.Request) {
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.GetCustodialLineItemsResponseBody = &operations.GetCustodialLineItemsResponseBody{
		TotalCount: types.Int64(6),
		Count:      types.Int64(2),
		Limit:      types.Int64(2),
		Offset:     types.Int64(0),
		Data: []operations.GetCustodialLineItemsData{
			operations.GetCustodialLineItemsData{
				UID:                    types.String("y4r8oTATb23MdGDF"),
				SettledIndex:           types.Int64(1),
				TransactionUID:         types.String("SMwKC1osz77DTEiu"),
				TransactionEventUID:    types.String("MB2yqBrm3c4bUbou"),
				CustodialAccountUID:    types.String("Gw4gr1T81YrvLT6M"),
				DebitCardUID:           types.String("6rVmYmv9VyTawrre"),
				Status:                 operations.GetCustodialLineItemsDataStatusSettled.ToPointer(),
				UsDollarAmount:         types.String("5.21"),
				RunningUsDollarBalance: optionalnullable.From(types.String("34.21")),
				RunningAssetBalance:    optionalnullable.From(types.String("34.21")),
				AssetQuantity:          types.String("5.21"),
				AssetType:              types.String("USD"),
				ClosingPrice:           types.String("5.00"),
				Type:                   types.String("transaction category 8348"),
				Description:            types.String("Deposit from Bank ABC 123"),
				CreatedAt:              types.MustNewTimeFromString("2019-10-15T15:53:13.591Z"),
				OccurredAt:             types.MustNewTimeFromString("2019-10-15T12:09:01Z"),
				SettledAt:              types.MustNewTimeFromString("2019-10-16T12:51:12.673Z"),
			},
			operations.GetCustodialLineItemsData{
				UID:                    types.String("m9bED9iicUUk8YAc"),
				SettledIndex:           types.Int64(2),
				TransactionUID:         types.String("SMwKC1osz77DTEiu"),
				TransactionEventUID:    types.String("MB2yqBrm3c4bUbou"),
				CustodialAccountUID:    types.String("66gso857LyQWC6XN"),
				DebitCardUID:           types.String("6rVmYmv9VyTawrre"),
				Status:                 operations.GetCustodialLineItemsDataStatusSettled.ToPointer(),
				UsDollarAmount:         types.String("-5.21"),
				RunningUsDollarBalance: optionalnullable.From(types.String("92.31")),
				RunningAssetBalance:    optionalnullable.From(types.String("78.90")),
				AssetQuantity:          types.String("-0.32"),
				AssetType:              types.String("EUR"),
				ClosingPrice:           types.String("5.00"),
				Type:                   types.String("transaction category 8348"),
				Description:            types.String("Deposit to Newline 999"),
				CreatedAt:              types.MustNewTimeFromString("2019-10-15T15:53:13.591Z"),
				OccurredAt:             types.MustNewTimeFromString("2019-10-15T12:09:01Z"),
				SettledAt:              types.MustNewTimeFromString("2019-10-16T12:51:12.673Z"),
			},
			operations.GetCustodialLineItemsData{
				UID:                    types.String("RoT4hmcD1HqyiYs5"),
				SettledIndex:           types.Int64(3),
				TransactionUID:         types.String("MrK36MpkgoJk25uF"),
				TransactionEventUID:    types.String("MB2yqBrm3c4bUbou"),
				CustodialAccountUID:    types.String("WfBSdeYee9G1kkJY"),
				DebitCardUID:           types.String("BB2gKYabEpJPoKWw"),
				Status:                 operations.GetCustodialLineItemsDataStatusSettled.ToPointer(),
				UsDollarAmount:         types.String("-3.50"),
				RunningUsDollarBalance: optionalnullable.From(types.String("88.64")),
				RunningAssetBalance:    optionalnullable.From(types.String("88.64")),
				AssetQuantity:          types.String("-3.50"),
				AssetType:              types.String("USD"),
				ClosingPrice:           types.String("3.35"),
				Type:                   types.String("Retail Purchase"),
				Description:            types.String("Debit to Newline 998 - BOB'S WIDGETS"),
				CreatedAt:              types.MustNewTimeFromString("2021-10-15T15:53:13.591Z"),
				OccurredAt:             types.MustNewTimeFromString("2021-10-15T12:09:01Z"),
				SettledAt:              types.MustNewTimeFromString("2021-10-16T12:51:12.673Z"),
			},
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}
