// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"fmt"
	"log"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/operations"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathGetProducts(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "listProducts[0]":
			dir.HandlerFunc("listProducts", testListProductsListProducts0)(w, req)
		default:
			http.Error(w, fmt.Sprintf("Unknown test: %s[%d]", test, count), http.StatusBadRequest)
		}
	}
}

func testListProductsListProducts0(w http.ResponseWriter, req *http.Request) {
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.ListProductsResponseBody = &operations.ListProductsResponseBody{
		TotalCount: types.Int64(1),
		Count:      types.Int64(1),
		Limit:      types.Int64(100),
		Offset:     types.Int64(0),
		Data: []operations.ListProductsData{
			operations.ListProductsData{
				UID:                      types.String("f9VncZny4ejhcPF4"),
				Name:                     types.String("Checking"),
				Description:              types.String("Supports checking accounts"),
				ProductCompliancePlanUID: types.String("Vxf1pY1KHbiJYo1e"),
				CompliancePlanName:       types.String("Compliance requirements for checking"),
				CustomerTypes: []string{
					"primary",
					"sole_proprietor",
				},
				PrerequisiteProductUids: []string{
					"DaB7Mjj73Nz2JpHF",
					"x2z691J9HPCWAugv",
				},
				ProfileRequirements: []operations.ListProductsProfileRequirement{
					operations.ListProductsProfileRequirement{
						ProfileRequirementUID: types.String("ptRLF7nQvy8VoqM1"),
						ProfileRequirement:    types.String("Please provide your approximate annual income in USD."),
						Category:              types.String("default"),
						Required:              types.Bool(true),
						ResponseValues: []string{
							"yes",
							"no",
						},
					},
				},
				ProgramUID: types.String("W74Jrkxk8bVtvNNj"),
				RequiredFields: []operations.ListProductsRequiredField{
					operations.ListProductsRequiredField{
						CustomerType: types.String("primary"),
						Fields: []string{
							"city",
							"dob",
							"email",
							"first_name",
							"last_name",
							"phone",
							"postal_code",
							"ssn",
							"state",
							"street1",
						},
					},
					operations.ListProductsRequiredField{
						CustomerType: types.String("sole_proprietor"),
						Fields: []string{
							"business_name",
							"city",
							"dob",
							"email",
							"first_name",
							"last_name",
							"phone",
							"postal_code",
							"ssn",
							"state",
							"street1",
						},
					},
				},
			},
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}
