// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"fmt"
	"log"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/operations"
	"mockserver/internal/sdk/optionalnullable"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathPostTransfers(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "createTransfer-ach[0]":
			dir.HandlerFunc("createTransfer", testCreateTransferCreateTransferAch0)(w, req)
		case "createTransfer-instant_payment[0]":
			dir.HandlerFunc("createTransfer", testCreateTransferCreateTransferInstantPayment0)(w, req)
		case "createTransfer-wire[0]":
			dir.HandlerFunc("createTransfer", testCreateTransferCreateTransferWire0)(w, req)
		case "createTransfer-ach_transfer[0]":
			dir.HandlerFunc("createTransfer", testCreateTransferCreateTransferAchTransfer0)(w, req)
		case "createTransfer-instant_payment_transfer[0]":
			dir.HandlerFunc("createTransfer", testCreateTransferCreateTransferInstantPaymentTransfer0)(w, req)
		case "createTransfer-wire_transfer[0]":
			dir.HandlerFunc("createTransfer", testCreateTransferCreateTransferWireTransfer0)(w, req)
		default:
			http.Error(w, fmt.Sprintf("Unknown test: %s[%d]", test, count), http.StatusBadRequest)
		}
	}
}

func testCreateTransferCreateTransferAch0(w http.ResponseWriter, req *http.Request) {
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.CreateTransferResponseBody = &operations.CreateTransferResponseBody{
		SourceSyntheticAccountUID:      types.String("4XkJnsfHsuqrxmeX"),
		DestinationSyntheticAccountUID: types.String("exMDShw6yM3NHLYV"),
		InitiatingCustomerUID:          types.String("iDtmSA52zRhgN4iy"),
		DestinationCustomerUID:         types.String("iDtmSA52zRhgN4iy"),
		Status:                         operations.CreateTransferStatusPending.ToPointer(),
		InitiatorType:                  operations.CreateTransferInitiatorTypeResponseCustomer.ToPointer(),
		CreatedAt:                      types.MustNewTimeFromString("2019-10-14T03:21:53.301Z"),
		QueuedUntil:                    types.MustNewTimeFromString("2019-10-14T03:31:53.301Z"),
		UID:                            types.String("EhrQZJNjCd79LLYq"),
		ExternalUID:                    types.String("partner-generated-id"),
		TransactionUids: []string{
			"Ym4RSchXQmmr6KfK",
			"vmxGSMb1vFLoyc1B",
		},
		UsdTransferAmount: types.String("34.12"),
		Ach: &operations.CreateTransferAchResponse{
			OriginatorName:           types.String("J. Fred Muggs"),
			CompanyID:                types.String("ABC-123456"),
			CompanyDiscretionaryData: types.String("ABC.123"),
			Prenote:                  types.Bool(false),
			SecCode:                  operations.CreateTransferSecCodeResponseCie.ToPointer(),
			PaymentType:              operations.CreateTransferPaymentTypeResponseSt.ToPointer(),
			EntryDescription:         types.String("ACH Entry"),
			ServiceProcessing:        operations.CreateTransferServiceProcessingResponseSameday.ToPointer(),
			EffectiveEntryDate:       types.String("2023-12-01"),
			IDNumber:                 types.String("4270465600"),
			TransferTraceID:          types.String("A1Z2b3y4c5x6DW78"),
		},
		InstantPayment: &operations.CreateTransferInstantPaymentResponse{
			Memo: optionalnullable.From(types.String("For the 6-5-23 shipment of pineapple popsicles")),
		},
		Wire: &operations.CreateTransferWireResponse{
			IntermediaryBankAddress: &operations.CreateTransferIntermediaryBankAddressResponse{
				Line1:   optionalnullable.From(types.String("345 Def Ave")),
				Line2:   optionalnullable.From(types.String("San Francisco")),
				Line3:   optionalnullable.From(types.String("CA 94016")),
				Country: optionalnullable.From(types.String("US")),
			},
			IntermediaryBankName:          types.String("Fidelity Fiduciary Bank"),
			IntermediaryBankRoutingNumber: types.String("923456789"),
			WireTransmitter: &operations.CreateTransferWireTransmitterResponse{
				Name:                  "Marge's Roofing Inc",
				TransmitterIdentifier: "123456789012ABC",
				Line1:                 types.String("123 Abc St."),
				Line2:                 optionalnullable.From(types.String("Boring, Oregon 97009")),
				Line3:                 nil,
				Country:               "US",
			},
			WireInstructions: types.String("Send ASAP"),
		},
		Cancellation: &operations.CreateTransferCancellation{
			AuthorizedRepresentativeName: types.String("Swee'Pea"),
			CancellationReason:           types.String("Transfer submitted by accident"),
			CancellationRequestedAt:      types.MustNewTimeFromString("2024-02-06T22:25:28.013Z"),
			CancellationSucceededAt:      types.MustNewTimeFromString("2024-02-06T22:25:39.618Z"),
			CancellationFailedAt:         types.MustNewTimeFromString("2024-02-06T22:25:39.618Z"),
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_, _ = w.Write(respBodyBytes)
}

func testCreateTransferCreateTransferInstantPayment0(w http.ResponseWriter, req *http.Request) {
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.CreateTransferResponseBody = &operations.CreateTransferResponseBody{
		SourceSyntheticAccountUID:      types.String("4XkJnsfHsuqrxmeX"),
		DestinationSyntheticAccountUID: types.String("exMDShw6yM3NHLYV"),
		InitiatingCustomerUID:          types.String("iDtmSA52zRhgN4iy"),
		DestinationCustomerUID:         types.String("iDtmSA52zRhgN4iy"),
		Status:                         operations.CreateTransferStatusPending.ToPointer(),
		InitiatorType:                  operations.CreateTransferInitiatorTypeResponseCustomer.ToPointer(),
		CreatedAt:                      types.MustNewTimeFromString("2019-10-14T03:21:53.301Z"),
		QueuedUntil:                    types.MustNewTimeFromString("2019-10-14T03:31:53.301Z"),
		UID:                            types.String("EhrQZJNjCd79LLYq"),
		ExternalUID:                    types.String("partner-generated-id"),
		TransactionUids: []string{
			"Ym4RSchXQmmr6KfK",
			"vmxGSMb1vFLoyc1B",
		},
		UsdTransferAmount: types.String("34.12"),
		Ach: &operations.CreateTransferAchResponse{
			OriginatorName:           types.String("J. Fred Muggs"),
			CompanyID:                types.String("ABC-123456"),
			CompanyDiscretionaryData: types.String("ABC.123"),
			Prenote:                  types.Bool(false),
			SecCode:                  operations.CreateTransferSecCodeResponseCie.ToPointer(),
			PaymentType:              operations.CreateTransferPaymentTypeResponseSt.ToPointer(),
			EntryDescription:         types.String("ACH Entry"),
			ServiceProcessing:        operations.CreateTransferServiceProcessingResponseSameday.ToPointer(),
			EffectiveEntryDate:       types.String("2023-12-01"),
			IDNumber:                 types.String("4270465600"),
			TransferTraceID:          types.String("A1Z2b3y4c5x6DW78"),
		},
		InstantPayment: &operations.CreateTransferInstantPaymentResponse{
			Memo: optionalnullable.From(types.String("For the 6-5-23 shipment of pineapple popsicles")),
		},
		Wire: &operations.CreateTransferWireResponse{
			IntermediaryBankAddress: &operations.CreateTransferIntermediaryBankAddressResponse{
				Line1:   optionalnullable.From(types.String("345 Def Ave")),
				Line2:   optionalnullable.From(types.String("San Francisco")),
				Line3:   optionalnullable.From(types.String("CA 94016")),
				Country: optionalnullable.From(types.String("US")),
			},
			IntermediaryBankName:          types.String("Fidelity Fiduciary Bank"),
			IntermediaryBankRoutingNumber: types.String("923456789"),
			WireTransmitter: &operations.CreateTransferWireTransmitterResponse{
				Name:                  "Marge's Roofing Inc",
				TransmitterIdentifier: "123456789012ABC",
				Line1:                 types.String("123 Abc St."),
				Line2:                 optionalnullable.From(types.String("Boring, Oregon 97009")),
				Line3:                 nil,
				Country:               "US",
			},
			WireInstructions: types.String("Send ASAP"),
		},
		Cancellation: &operations.CreateTransferCancellation{
			AuthorizedRepresentativeName: types.String("Swee'Pea"),
			CancellationReason:           types.String("Transfer submitted by accident"),
			CancellationRequestedAt:      types.MustNewTimeFromString("2024-02-06T22:25:28.013Z"),
			CancellationSucceededAt:      types.MustNewTimeFromString("2024-02-06T22:25:39.618Z"),
			CancellationFailedAt:         types.MustNewTimeFromString("2024-02-06T22:25:39.618Z"),
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_, _ = w.Write(respBodyBytes)
}

func testCreateTransferCreateTransferWire0(w http.ResponseWriter, req *http.Request) {
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.CreateTransferResponseBody = &operations.CreateTransferResponseBody{
		SourceSyntheticAccountUID:      types.String("4XkJnsfHsuqrxmeX"),
		DestinationSyntheticAccountUID: types.String("exMDShw6yM3NHLYV"),
		InitiatingCustomerUID:          types.String("iDtmSA52zRhgN4iy"),
		DestinationCustomerUID:         types.String("iDtmSA52zRhgN4iy"),
		Status:                         operations.CreateTransferStatusPending.ToPointer(),
		InitiatorType:                  operations.CreateTransferInitiatorTypeResponseCustomer.ToPointer(),
		CreatedAt:                      types.MustNewTimeFromString("2019-10-14T03:21:53.301Z"),
		QueuedUntil:                    types.MustNewTimeFromString("2019-10-14T03:31:53.301Z"),
		UID:                            types.String("EhrQZJNjCd79LLYq"),
		ExternalUID:                    types.String("partner-generated-id"),
		TransactionUids: []string{
			"Ym4RSchXQmmr6KfK",
			"vmxGSMb1vFLoyc1B",
		},
		UsdTransferAmount: types.String("34.12"),
		Ach: &operations.CreateTransferAchResponse{
			OriginatorName:           types.String("J. Fred Muggs"),
			CompanyID:                types.String("ABC-123456"),
			CompanyDiscretionaryData: types.String("ABC.123"),
			Prenote:                  types.Bool(false),
			SecCode:                  operations.CreateTransferSecCodeResponseCie.ToPointer(),
			PaymentType:              operations.CreateTransferPaymentTypeResponseSt.ToPointer(),
			EntryDescription:         types.String("ACH Entry"),
			ServiceProcessing:        operations.CreateTransferServiceProcessingResponseSameday.ToPointer(),
			EffectiveEntryDate:       types.String("2023-12-01"),
			IDNumber:                 types.String("4270465600"),
			TransferTraceID:          types.String("A1Z2b3y4c5x6DW78"),
		},
		InstantPayment: &operations.CreateTransferInstantPaymentResponse{
			Memo: optionalnullable.From(types.String("For the 6-5-23 shipment of pineapple popsicles")),
		},
		Wire: &operations.CreateTransferWireResponse{
			IntermediaryBankAddress: &operations.CreateTransferIntermediaryBankAddressResponse{
				Line1:   optionalnullable.From(types.String("345 Def Ave")),
				Line2:   optionalnullable.From(types.String("San Francisco")),
				Line3:   optionalnullable.From(types.String("CA 94016")),
				Country: optionalnullable.From(types.String("US")),
			},
			IntermediaryBankName:          types.String("Fidelity Fiduciary Bank"),
			IntermediaryBankRoutingNumber: types.String("923456789"),
			WireTransmitter: &operations.CreateTransferWireTransmitterResponse{
				Name:                  "Marge's Roofing Inc",
				TransmitterIdentifier: "123456789012ABC",
				Line1:                 types.String("123 Abc St."),
				Line2:                 optionalnullable.From(types.String("Boring, Oregon 97009")),
				Line3:                 nil,
				Country:               "US",
			},
			WireInstructions: types.String("Send ASAP"),
		},
		Cancellation: &operations.CreateTransferCancellation{
			AuthorizedRepresentativeName: types.String("Swee'Pea"),
			CancellationReason:           types.String("Transfer submitted by accident"),
			CancellationRequestedAt:      types.MustNewTimeFromString("2024-02-06T22:25:28.013Z"),
			CancellationSucceededAt:      types.MustNewTimeFromString("2024-02-06T22:25:39.618Z"),
			CancellationFailedAt:         types.MustNewTimeFromString("2024-02-06T22:25:39.618Z"),
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_, _ = w.Write(respBodyBytes)
}

func testCreateTransferCreateTransferAchTransfer0(w http.ResponseWriter, req *http.Request) {
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.CreateTransferResponseBody = &operations.CreateTransferResponseBody{
		SourceSyntheticAccountUID:      types.String("4XkJnsfHsuqrxmeX"),
		DestinationSyntheticAccountUID: types.String("exMDShw6yM3NHLYV"),
		InitiatingCustomerUID:          types.String("iDtmSA52zRhgN4iy"),
		DestinationCustomerUID:         types.String("iDtmSA52zRhgN4iy"),
		Status:                         operations.CreateTransferStatusPending.ToPointer(),
		InitiatorType:                  operations.CreateTransferInitiatorTypeResponseCustomer.ToPointer(),
		CreatedAt:                      types.MustNewTimeFromString("2019-10-14T03:21:53.301Z"),
		UID:                            types.String("EhrQZJNjCd79LLYq"),
		ExternalUID:                    types.String("partner-generated-id"),
		TransactionUids:                []string{},
		Ach: &operations.CreateTransferAchResponse{
			OriginatorName:           types.String("Mr. Hyyt Meiser"),
			CompanyID:                types.String("HJK867"),
			CompanyDiscretionaryData: types.String("Some data"),
			Prenote:                  types.Bool(false),
			SecCode:                  operations.CreateTransferSecCodeResponseCcd.ToPointer(),
			PaymentType:              operations.CreateTransferPaymentTypeResponseS.ToPointer(),
			EntryDescription:         types.String("ACH Entry"),
			ServiceProcessing:        operations.CreateTransferServiceProcessingResponseStandard.ToPointer(),
			EffectiveEntryDate:       types.String("2023-12-21"),
			IDNumber:                 types.String("4270465600"),
			Addenda:                  types.String("Having said that, this"),
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_, _ = w.Write(respBodyBytes)
}

func testCreateTransferCreateTransferInstantPaymentTransfer0(w http.ResponseWriter, req *http.Request) {
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.CreateTransferResponseBody = &operations.CreateTransferResponseBody{
		SourceSyntheticAccountUID:      types.String("ABv3vs5yVypxpGgF"),
		DestinationSyntheticAccountUID: types.String("RRbw63TF4o1vg2RQ"),
		InitiatingCustomerUID:          types.String("oBugADTMCMEU4sfE"),
		DestinationCustomerUID:         types.String("22PBwMT88qCQWMSg"),
		Status:                         operations.CreateTransferStatusSettled.ToPointer(),
		InitiatorType:                  operations.CreateTransferInitiatorTypeResponseTransmitter.ToPointer(),
		CreatedAt:                      types.MustNewTimeFromString("2019-10-14T03:21:53.301Z"),
		UID:                            types.String("VeYqeb1iHqBR4LEi"),
		ExternalUID:                    types.String("partner-created-id"),
		TransactionUids: []string{
			"d8WUMmm4dZfMpLeh",
		},
		UsdTransferAmount: types.String("32.13"),
		InstantPayment: &operations.CreateTransferInstantPaymentResponse{
			Memo: optionalnullable.From(types.String("To unfreeze the prince's assets")),
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_, _ = w.Write(respBodyBytes)
}

func testCreateTransferCreateTransferWireTransfer0(w http.ResponseWriter, req *http.Request) {
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.CreateTransferResponseBody = &operations.CreateTransferResponseBody{
		SourceSyntheticAccountUID:      types.String("4XkJnsfHsuqrxmeX"),
		DestinationSyntheticAccountUID: types.String("exMDShw6yM3NHLYV"),
		InitiatingCustomerUID:          types.String("iDtmSA52zRhgN4iy"),
		DestinationCustomerUID:         types.String("iDtmSA52zRhgN4iy"),
		Status:                         operations.CreateTransferStatusPending.ToPointer(),
		InitiatorType:                  operations.CreateTransferInitiatorTypeResponseTransmitter.ToPointer(),
		CreatedAt:                      types.MustNewTimeFromString("2019-10-14T03:21:53.301Z"),
		UID:                            types.String("EhrQZJNjCd79LLYq"),
		ExternalUID:                    types.String("partner-generated-id"),
		TransactionUids:                []string{},
		UsdTransferAmount:              types.String("33.12"),
		Wire: &operations.CreateTransferWireResponse{
			IntermediaryBankAddress: &operations.CreateTransferIntermediaryBankAddressResponse{
				Line1:   optionalnullable.From(types.String("345 Def Ave")),
				Line2:   optionalnullable.From(types.String("San Francisco")),
				Line3:   optionalnullable.From(types.String("CA 94016")),
				Country: optionalnullable.From(types.String("US")),
			},
			IntermediaryBankName:          types.String("Fidelity Fiduciary Bank"),
			IntermediaryBankRoutingNumber: types.String("923456789"),
			WireTransmitter: &operations.CreateTransferWireTransmitterResponse{
				Name:                  "Top Tier Tacos",
				TransmitterIdentifier: "123456789",
				Line1:                 types.String("123 Abc St."),
				Country:               "US",
			},
			WireInstructions: types.String("Please send ASAP"),
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_, _ = w.Write(respBodyBytes)
}
