// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"fmt"
	"log"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/operations"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathPutTransactionsUIDAuthorize(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "put_/transactions/{uid}/authorize[0]":
			dir.HandlerFunc("put_/transactions/{uid}/authorize", testPutTransactionsUIDAuthorizePutTransactionsUIDAuthorize0)(w, req)
		default:
			http.Error(w, fmt.Sprintf("Unknown test: %s[%d]", test, count), http.StatusBadRequest)
		}
	}
}

func testPutTransactionsUIDAuthorizePutTransactionsUIDAuthorize0(w http.ResponseWriter, req *http.Request) {
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.PutTransactionsUIDAuthorizeResponseBody = &operations.PutTransactionsUIDAuthorizeResponseBody{
		Authorization: &operations.PutTransactionsUIDAuthorizeAuthorization{
			AuthorizationFinalizedAt: types.MustNewTimeFromString("2024-10-09T00:12:53.729Z"),
			AuthorizationRequiredBy:  types.MustNewTimeFromString("2024-10-10T00:18:53.729Z"),
			AuthorizationStatus:      operations.PutTransactionsUIDAuthorizeAuthorizationStatusResponseClientDenied.ToPointer(),
			DeniedMemo:               types.String("denied memo"),
			DeniedReason:             types.String("debit_limit_exceeded"),
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}
