// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"fmt"
	"log"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/operations"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathPostVirtualReferenceNumbers(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "post_/virtual_reference_numbers-create_payload[0]":
			dir.HandlerFunc("post_/virtual_reference_numbers", testPostVirtualReferenceNumbersPostVirtualReferenceNumbersCreatePayload0)(w, req)
		case "post_/virtual_reference_numbers-pending[0]":
			dir.HandlerFunc("post_/virtual_reference_numbers", testPostVirtualReferenceNumbersPostVirtualReferenceNumbersPending0)(w, req)
		default:
			http.Error(w, fmt.Sprintf("Unknown test: %s[%d]", test, count), http.StatusBadRequest)
		}
	}
}

func testPostVirtualReferenceNumbersPostVirtualReferenceNumbersCreatePayload0(w http.ResponseWriter, req *http.Request) {
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.PostVirtualReferenceNumbersResponseBody = &operations.PostVirtualReferenceNumbersResponseBody{
		ArchivedAt:                           types.String("<value>"),
		CreatedAt:                            types.String("2023-10-04T13:23:04.345Z"),
		CustodialAccountUID:                  types.String("tcvYpQ1ip76LaL4a"),
		ExternalUID:                          types.String("partner-generated-id"),
		InstantPaymentRailRegistrationStatus: operations.PostVirtualReferenceNumbersInstantPaymentRailRegistrationStatusRegistered.ToPointer(),
		LockedAt:                             types.String("<value>"),
		LockReason:                           operations.PostVirtualReferenceNumbersLockReasonAdmin.ToPointer(),
		Name:                                 types.String("greenfield1"),
		RoutingNumber:                        types.String("123456789"),
		Status:                               operations.PostVirtualReferenceNumbersStatusActive.ToPointer(),
		SyntheticAccountUID:                  types.String("Dg1EPao8XukUpHG8"),
		UID:                                  types.String("dYTG8WAWAh5UyvY7"),
		VirtualReferenceNumberLastFour:       types.String("3456"),
		VirtualReferenceNumber:               types.String("1234567890123456"),
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_, _ = w.Write(respBodyBytes)
}

func testPostVirtualReferenceNumbersPostVirtualReferenceNumbersPending0(w http.ResponseWriter, req *http.Request) {
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.PostVirtualReferenceNumbersResponseBody = &operations.PostVirtualReferenceNumbersResponseBody{
		ArchivedAt:                           types.String("<value>"),
		CreatedAt:                            types.String("2023-10-04T13:23:04.345Z"),
		CustodialAccountUID:                  types.String("tcvYpQ1ip76LaL4a"),
		ExternalUID:                          types.String("partner-generated-id"),
		InstantPaymentRailRegistrationStatus: operations.PostVirtualReferenceNumbersInstantPaymentRailRegistrationStatusPending.ToPointer(),
		LockedAt:                             types.String("<value>"),
		LockReason:                           operations.PostVirtualReferenceNumbersLockReasonCustomerRequest.ToPointer(),
		Name:                                 types.String("greenfield1"),
		RoutingNumber:                        types.String("123456789"),
		Status:                               operations.PostVirtualReferenceNumbersStatusActive.ToPointer(),
		SyntheticAccountUID:                  types.String("Dg1EPao8XukUpHG8"),
		UID:                                  types.String("dYTG8WAWAh5UyvY7"),
		VirtualReferenceNumberLastFour:       types.String("3456"),
		VirtualReferenceNumber:               types.String("1234567890123456"),
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_, _ = w.Write(respBodyBytes)
}
