/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { NewlineSDK } from "../index.js";
import { createTestHTTPClient } from "./test-client.js";

test("Combinedtransfers Get /Combined Transfers Combined Transfers List", async () => {
  const testHttpClient = createTestHTTPClient(
    "get_/combined_transfers-combined_transfers_list",
  );

  const newlineSDK = new NewlineSDK({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    security: {
      programUid: "NEWLINE_PROGRAM_UID",
      hmacKey: "NEWLINE_HMAC_KEY",
    },
    httpClient: testHttpClient,
  });

  const result = await newlineSDK.combinedTransfers.list({
    createdAtAfter: new Date("2020-01-01T00:00:00Z"),
    createdAtBefore: new Date("2020-01-01T00:00:00Z"),
    externalUid: "client-generated-id",
    status: "completed",
    syntheticAccountExternalUid: "client-generated-id",
    syntheticAccountPoolUid: "wTSMX1GubP21ev2h",
    syntheticAccountUid: "7UvkHn3Ss9AbWe2c",
    transferCustomerUid: "wTSMX1GubP21ev2h",
    transferExternalUid: "client-generated-id",
    transferUid: "7UvkHn3Ss9AbWe2c",
  });
  expect(result).toBeDefined();
});

test("Combinedtransfers Post /Combined Transfers Ach Transfer To New Account", async () => {
  const testHttpClient = createTestHTTPClient(
    "post_/combined_transfers-ach_transfer_to_new_account",
  );

  const newlineSDK = new NewlineSDK({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    security: {
      programUid: "NEWLINE_PROGRAM_UID",
      hmacKey: "NEWLINE_HMAC_KEY",
    },
    httpClient: testHttpClient,
  });

  const result = await newlineSDK.combinedTransfers.create({
    syntheticAccount: {
      externalUid: "abcd12345",
      name: "Spinach Fund",
      poolUid: "axz9sbUgRVu5wqbw",
      syntheticAccountTypeUid: "UyjH72G9KAhmbpNS",
      routingNumber: "04200031",
      accountNumber: "1234567890",
      ach: {
        accountType: "checking",
        counterpartyName: "awesome counterparty",
      },
    },
    transfer: {
      sourceSyntheticAccountUid: "4XkJnsfHsuqrxmeX",
      destinationSyntheticAccountUid: "beHyJNeBU65Xv8LK",
      initiatingCustomerUid: "axz9sbUgRVu5wqbw",
      initiatorType: "customer",
      usdTransferAmount: "12.34",
      ach: {
        originatorName: "J. Fred Muggs",
        secCode: "CIE",
        entryDescription: "ACH Entry",
        serviceProcessing: "SAMEDAY",
        effectiveEntryDate: "2023-12-01",
      },
    },
  });
  expect(result).toBeDefined();
});

test("Combinedtransfers Post /Combined Transfers Ach Transfer To Existing Account", async () => {
  const testHttpClient = createTestHTTPClient(
    "post_/combined_transfers-ach_transfer_to_existing_account",
  );

  const newlineSDK = new NewlineSDK({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    security: {
      programUid: "NEWLINE_PROGRAM_UID",
      hmacKey: "NEWLINE_HMAC_KEY",
    },
    httpClient: testHttpClient,
  });

  const result = await newlineSDK.combinedTransfers.create({
    syntheticAccount: {
      externalUid: "partner-generated-id",
      name: "New Resource Name",
      poolUid: "kaxHFJnWvJxRJZxq",
      syntheticAccountTypeUid: "fRMwt6H14ovFUz1s",
    },
    transfer: {
      sourceSyntheticAccountUid: "4XkJnsfHsuqrxmeX",
      destinationSyntheticAccountUid: "beHyJNeBU65Xv8LK",
      initiatingCustomerUid: "axz9sbUgRVu5wqbw",
      initiatorType: "customer",
      usdTransferAmount: "12.34",
      ach: {
        originatorName: "J. Fred Muggs",
        secCode: "CIE",
        entryDescription: "ACH Entry",
        serviceProcessing: "SAMEDAY",
        effectiveEntryDate: "2023-12-01",
      },
    },
  });
  expect(result).toBeDefined();
});

test("Combinedtransfers Post /Combined Transfers Instant Payment Transfer To New Account", async () => {
  const testHttpClient = createTestHTTPClient(
    "post_/combined_transfers-instant_payment_transfer_to_new_account",
  );

  const newlineSDK = new NewlineSDK({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    security: {
      programUid: "NEWLINE_PROGRAM_UID",
      hmacKey: "NEWLINE_HMAC_KEY",
    },
    httpClient: testHttpClient,
  });

  const result = await newlineSDK.combinedTransfers.create({
    syntheticAccount: {
      externalUid: "abcd12345",
      name: "Spinach Fund",
      poolUid: "axz9sbUgRVu5wqbw",
      syntheticAccountTypeUid: "UyjH72G9KAhmbpNS",
      routingNumber: "04200031",
      accountNumber: "1234567890",
      instantPayment: {
        counterpartyAddress: {
          streetNumber: "123",
          street1: "Main street",
          city: "Brooklyn",
          state: "IA",
          postalCode: "12345-6789",
          country: "US",
        },
        counterpartyName: "awesome counterparty",
        email: "address@domain.com",
        phone: "2121112233",
      },
    },
    transfer: {
      sourceSyntheticAccountUid: "4XkJnsfHsuqrxmeX",
      destinationSyntheticAccountUid: "beHyJNeBU65Xv8LK",
      initiatingCustomerUid: "axz9sbUgRVu5wqbw",
      initiatorType: "customer",
      usdTransferAmount: "12.34",
      instantPayment: {
        instantPaymentTransmitter: {
          name: "Royalty Asset Management",
          transmitterIdentifier: "123456789",
          streetNumber: "123",
          street1: "Abc St.",
          city: "Boring",
          state: "OR",
          postalCode: "97009",
          country: null,
        },
        memo: "To unfreeze the prince's assets",
      },
    },
  });
  expect(result).toBeDefined();
});

test("Combinedtransfers Post /Combined Transfers Instant Payment Transfer To Existing Account", async () => {
  const testHttpClient = createTestHTTPClient(
    "post_/combined_transfers-instant_payment_transfer_to_existing_account",
  );

  const newlineSDK = new NewlineSDK({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    security: {
      programUid: "NEWLINE_PROGRAM_UID",
      hmacKey: "NEWLINE_HMAC_KEY",
    },
    httpClient: testHttpClient,
  });

  const result = await newlineSDK.combinedTransfers.create({
    syntheticAccount: {
      externalUid: "partner-generated-id",
      name: "New Resource Name",
      poolUid: "kaxHFJnWvJxRJZxq",
      syntheticAccountTypeUid: "fRMwt6H14ovFUz1s",
    },
    transfer: {
      sourceSyntheticAccountUid: "4XkJnsfHsuqrxmeX",
      destinationSyntheticAccountUid: "beHyJNeBU65Xv8LK",
      initiatingCustomerUid: "axz9sbUgRVu5wqbw",
      initiatorType: "customer",
      usdTransferAmount: "12.34",
      instantPayment: {
        instantPaymentTransmitter: {
          name: "Royalty Asset Management",
          transmitterIdentifier: "123456789",
          streetNumber: "123",
          street1: "Abc St.",
          city: "Boring",
          state: "OR",
          postalCode: "97009",
          country: null,
        },
        memo: "To unfreeze the prince's assets",
      },
    },
  });
  expect(result).toBeDefined();
});

test("Combinedtransfers Post /Combined Transfers Wire Transfer To New Account", async () => {
  const testHttpClient = createTestHTTPClient(
    "post_/combined_transfers-wire_transfer_to_new_account",
  );

  const newlineSDK = new NewlineSDK({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    security: {
      programUid: "NEWLINE_PROGRAM_UID",
      hmacKey: "NEWLINE_HMAC_KEY",
    },
    httpClient: testHttpClient,
  });

  const result = await newlineSDK.combinedTransfers.create({
    syntheticAccount: {
      externalUid: "abcd12345",
      name: "Spinach Fund",
      poolUid: "axz9sbUgRVu5wqbw",
      syntheticAccountTypeUid: "UyjH72G9KAhmbpNS",
      routingNumber: "04200031",
      accountNumber: "1234567890",
      wire: {
        counterpartyName: "Awesome Counterparty",
        counterpartyBankName: "Biggest Bank Inc",
      },
    },
    transfer: {
      sourceSyntheticAccountUid: "4XkJnsfHsuqrxmeX",
      destinationSyntheticAccountUid: "beHyJNeBU65Xv8LK",
      initiatingCustomerUid: "axz9sbUgRVu5wqbw",
      initiatorType: "customer",
      usdTransferAmount: "12.34",
      wire: {
        intermediaryBankAddress: {
          line1: "123 Main St",
          line2: "Brooklyn NY",
          country: "US",
        },
        intermediaryBankName: "Big Bank Inc",
        intermediaryBankRoutingNumber: "123456789",
        wireTransmitter: {
          name: "Bunker LLC",
          transmitterIdentifier: "1234567890",
          line1: "456 Second St",
          line2: "Queens NY",
          country: "US",
        },
      },
    },
  });
  expect(result).toBeDefined();
});

test("Combinedtransfers Post /Combined Transfers Wire Transfer To Existing Account", async () => {
  const testHttpClient = createTestHTTPClient(
    "post_/combined_transfers-wire_transfer_to_existing_account",
  );

  const newlineSDK = new NewlineSDK({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    security: {
      programUid: "NEWLINE_PROGRAM_UID",
      hmacKey: "NEWLINE_HMAC_KEY",
    },
    httpClient: testHttpClient,
  });

  const result = await newlineSDK.combinedTransfers.create({
    syntheticAccount: {
      externalUid: "partner-generated-id",
      name: "New Resource Name",
      poolUid: "kaxHFJnWvJxRJZxq",
      syntheticAccountTypeUid: "fRMwt6H14ovFUz1s",
    },
    transfer: {
      sourceSyntheticAccountUid: "4XkJnsfHsuqrxmeX",
      destinationSyntheticAccountUid: "beHyJNeBU65Xv8LK",
      initiatingCustomerUid: "axz9sbUgRVu5wqbw",
      initiatorType: "customer",
      usdTransferAmount: "12.34",
      wire: {
        intermediaryBankAddress: {
          line1: "123 Main St",
          line2: "Brooklyn NY",
          country: "US",
        },
        intermediaryBankName: "Big Bank Inc",
        intermediaryBankRoutingNumber: "123456789",
        wireTransmitter: {
          name: "Bunker LLC",
          transmitterIdentifier: "1234567890",
          line1: "456 Second St",
          line2: "Queens NY",
          country: "US",
        },
      },
    },
  });
  expect(result).toBeDefined();
});

test("Combinedtransfers Post /Combined Transfers Queued", async () => {
  const testHttpClient = createTestHTTPClient(
    "post_/combined_transfers-queued",
  );

  const newlineSDK = new NewlineSDK({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    security: {
      programUid: "NEWLINE_PROGRAM_UID",
      hmacKey: "NEWLINE_HMAC_KEY",
    },
    httpClient: testHttpClient,
  });

  const result = await newlineSDK.combinedTransfers.create({
    externalUid: "YrfDrfVRgpPgnhF5",
    syntheticAccount: {
      externalUid: "partner-generated-id",
      name: "New Resource Name",
      poolUid: "kaxHFJnWvJxRJZxq",
      syntheticAccountTypeUid: "fRMwt6H14ovFUz1s",
      routingNumber: "123456789",
      accountNumber: "123456789012",
      externalProcessorToken:
        "processor-sandbox-96d86f35-ef58-4e4a-826f-4870b5d677f2",
      ach: {
        accountType: "checking",
        counterpartyName: "Thelma's Flooring LLC",
      },
      instantPayment: {
        counterpartyAddress: {
          streetNumber: "123abc",
          street1: "Abc St.",
          street2: "Suite 4A",
          city: "Chicago",
          state: "IL",
          postalCode: "60301",
          country: null,
        },
        counterpartyName: "Marge's Roofing Inc",
        email: "payments@veryexcellentbusiness.com",
        phone: "5555551212",
      },
      wire: {
        counterpartyAddress: {
          line1: "234 Xyz Rd",
          line2: "APT 5",
          line3: "Boston, MA 02110",
          country: "US",
        },
        counterpartyName: "Marge's Roofing Inc",
        counterpartyBankAddress: {
          line1: "123 Abc St.",
          line2: "Boring, Oregon 97009",
          line3: null,
          country: null,
        },
        counterpartyBankName: "East West Regional Bank",
      },
    },
    transfer: {
      externalUid: "partner-generated-id",
      sourceSyntheticAccountUid: "4XkJnsfHsuqrxmeX",
      destinationSyntheticAccountUid: "exMDShw6yM3NHLYV",
      initiatingCustomerUid: "iDtmSA52zRhgN4iy",
      destinationCustomerUid: "iDtmSA52zRhgN4iy",
      initiatorType: "customer",
      usdTransferAmount: "12.34",
      ach: {
        originatorName: "J. Fred Muggs",
        companyId: "ABC-123456",
        companyDiscretionaryData: "ABC.123",
        prenote: false,
        secCode: "CIE",
        paymentType: "ST",
        entryDescription: "ACH Entry",
        serviceProcessing: "SAMEDAY",
        effectiveEntryDate: "2023-12-01",
        idNumber: "4270465600",
      },
      instantPayment: {
        instantPaymentTransmitter: {
          name: "Marge's Roofing Inc",
          transmitterIdentifier: "123456789012ABC",
          streetNumber: "123abc",
          street1: "Abc St.",
          city: "Chicago",
          state: "IL",
          postalCode: "60301",
          country: null,
        },
        memo: "For the 6-5-23 shipment of pineapple popsicles",
      },
      wire: {
        intermediaryBankAddress: {
          line1: "345 Def Ave",
          line2: "San Francisco",
          line3: "CA 94016",
          country: "US",
        },
        intermediaryBankName: "Fidelity Fiduciary Bank",
        intermediaryBankRoutingNumber: "923456789",
        wireInstructions: "Send ASAP",
        wireTransmitter: {
          name: "Marge's Roofing Inc",
          transmitterIdentifier: "123456789012ABC",
          line1: "123 Abc St.",
          line2: "Boring, Oregon 97009",
          line3: null,
          country: "US",
        },
      },
    },
  });
  expect(result).toBeDefined();
});

test("Combinedtransfers Get /Combined Transfers/{uid} Queued", async () => {
  const testHttpClient = createTestHTTPClient(
    "get_/combined_transfers/{uid}-queued",
  );

  const newlineSDK = new NewlineSDK({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    security: {
      programUid: "NEWLINE_PROGRAM_UID",
      hmacKey: "NEWLINE_HMAC_KEY",
    },
    httpClient: testHttpClient,
  });

  const result = await newlineSDK.combinedTransfers.get({
    uid: "<id>",
  });
  expect(result).toBeDefined();
});

test("Combinedtransfers Get /Combined Transfers/{uid} Pending", async () => {
  const testHttpClient = createTestHTTPClient(
    "get_/combined_transfers/{uid}-pending",
  );

  const newlineSDK = new NewlineSDK({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    security: {
      programUid: "NEWLINE_PROGRAM_UID",
      hmacKey: "NEWLINE_HMAC_KEY",
    },
    httpClient: testHttpClient,
  });

  const result = await newlineSDK.combinedTransfers.get({
    uid: "<id>",
  });
  expect(result).toBeDefined();
});

test("Combinedtransfers Get /Combined Transfers/{uid} Failed", async () => {
  const testHttpClient = createTestHTTPClient(
    "get_/combined_transfers/{uid}-failed",
  );

  const newlineSDK = new NewlineSDK({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    security: {
      programUid: "NEWLINE_PROGRAM_UID",
      hmacKey: "NEWLINE_HMAC_KEY",
    },
    httpClient: testHttpClient,
  });

  const result = await newlineSDK.combinedTransfers.get({
    uid: "<id>",
  });
  expect(result).toBeDefined();
});

test("Combinedtransfers Get /Combined Transfers/{uid} Completed", async () => {
  const testHttpClient = createTestHTTPClient(
    "get_/combined_transfers/{uid}-completed",
  );

  const newlineSDK = new NewlineSDK({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    security: {
      programUid: "NEWLINE_PROGRAM_UID",
      hmacKey: "NEWLINE_HMAC_KEY",
    },
    httpClient: testHttpClient,
  });

  const result = await newlineSDK.combinedTransfers.get({
    uid: "<id>",
  });
  expect(result).toBeDefined();
});
