/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { NewlineSDK } from "../index.js";
import { createTestHTTPClient } from "./test-client.js";

test("Customerproducts List Customer Products", async () => {
  const testHttpClient = createTestHTTPClient("listCustomerProducts");

  const newlineSDK = new NewlineSDK({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    security: {
      programUid: "NEWLINE_PROGRAM_UID",
      hmacKey: "NEWLINE_HMAC_KEY",
    },
    httpClient: testHttpClient,
  });

  const result = await newlineSDK.customerProducts.list({
    programUid: "pQtTCSXz57fuefzp",
    productUid: "zbJbEa72eKMgbbBv",
    customerUid: "uKxmLxUEiSj5h4M3",
  });
  expect(result).toBeDefined();
});

test("Customerproducts Onboard Customer Product", async () => {
  const testHttpClient = createTestHTTPClient("onboardCustomerProduct");

  const newlineSDK = new NewlineSDK({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    security: {
      programUid: "NEWLINE_PROGRAM_UID",
      hmacKey: "NEWLINE_HMAC_KEY",
    },
    httpClient: testHttpClient,
  });

  const result = await newlineSDK.customerProducts.onboard({
    customerUid: "S62MaHx6WwsqG9vQ",
    productUid: "pQtTCSXz57fuefzp",
  });
  expect(result).toBeDefined();
});

test("Customerproducts Get Customer Product", async () => {
  const testHttpClient = createTestHTTPClient("getCustomerProduct");

  const newlineSDK = new NewlineSDK({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    security: {
      programUid: "NEWLINE_PROGRAM_UID",
      hmacKey: "NEWLINE_HMAC_KEY",
    },
    httpClient: testHttpClient,
  });

  const result = await newlineSDK.customerProducts.get({
    uid: "<id>",
  });
  expect(result).toBeDefined();
});
