/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { syntheticAccountsArchive } from "../funcs/synthetic-accounts-archive.js";
import { syntheticAccountsCreate } from "../funcs/synthetic-accounts-create.js";
import { syntheticAccountsGetAccountType } from "../funcs/synthetic-accounts-get-account-type.js";
import { syntheticAccountsGetClosingBalance } from "../funcs/synthetic-accounts-get-closing-balance.js";
import { syntheticAccountsGet } from "../funcs/synthetic-accounts-get.js";
import { syntheticAccountsListClosingBalances } from "../funcs/synthetic-accounts-list-closing-balances.js";
import { syntheticAccountsListTypes } from "../funcs/synthetic-accounts-list-types.js";
import { syntheticAccountsList } from "../funcs/synthetic-accounts-list.js";
import { syntheticAccountsUpdate } from "../funcs/synthetic-accounts-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class SyntheticAccounts extends ClientSDK {
  /**
   * List Synthetic Account Types
   *
   * @remarks
   * Retrieve a list of Synthetic Account Types available for use in your Program. These types define the behavior and characteristics of Synthetic Accounts.
   */
  async listTypes(
    request?: operations.ListSyntheticAccountTypesRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListSyntheticAccountTypesResponse> {
    return unwrapAsync(syntheticAccountsListTypes(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a Single Synthetic Account Type
   *
   * @remarks
   * Returns a single Synthetic Account Type resource along with supporting details.
   *
   * Enables changes to the Synthetic Account fields, including the Master Synthetic Account. The Master Synthetic Account remains identifiable by the `master_account` flag stored with the Synthetic Account record.
   */
  async getAccountType(
    request: operations.GetSyntheticAccountTypeRequest,
    options?: RequestOptions,
  ): Promise<operations.GetSyntheticAccountTypeResponse> {
    return unwrapAsync(syntheticAccountsGetAccountType(
      this,
      request,
      options,
    ));
  }

  /**
   * List Synthetic Accounts
   *
   * @remarks
   * Retrieve a list of Synthetic Accounts associated with the specified Customer and Pool. This endpoint supports filtering by account type, category, status, and sorting by balance or name.
   */
  async list(
    request?: operations.ListSyntheticAccountsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListSyntheticAccountsResponse> {
    return unwrapAsync(syntheticAccountsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a New Synthetic Account
   *
   * @remarks
   * Create a new Synthetic Account in the Pool with the provided specification.
   *
   * External Synthetic Accounts are counterparty records that represent accounts at external financial institutions. They contain all the necessary information to execute a payment. For specifics about each payment rail's requirements, refer to our [Payment Rails](https://developers.newline53.com/docs/payment-rails) guides.
   */
  async create(
    request: operations.CreateSyntheticAccountRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateSyntheticAccountResponse> {
    return unwrapAsync(syntheticAccountsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a single Synthetic Account
   *
   * @remarks
   * Returns a single Synthetic Account resource along with supporting details and account balances.
   *
   * Note: Newline will suppress the `account_number` value for Synthetic Accounts in the `ach_external`, `wire_external`, and `instant_payments_external` categories. The `account_number_last_four` value will be returned in the response to help identify these Synthetic Accounts.
   */
  async get(
    request: operations.GetSyntheticAccountRequest,
    options?: RequestOptions,
  ): Promise<operations.GetSyntheticAccountResponse> {
    return unwrapAsync(syntheticAccountsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update the Synthetic Account metadata
   *
   * @remarks
   * Enables changes to the Synthetic Account fields, including the Master Synthetic Account. The Master Synthetic Account remains identifiable by the `master_account` flag stored with the Synthetic Account record.
   */
  async update(
    request: operations.UpdateSyntheticAccountRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateSyntheticAccountResponse> {
    return unwrapAsync(syntheticAccountsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Archive a Synthetic Account
   *
   * @remarks
   * In order to archive a Synthetic Account, the account must:
   *
   * - not be a Master Synthetic Account i.e. `master_account` must be false.
   * - have zero balance.
   * - have no pending Transfers.
   *
   * Master Synthetic Accounts are archived when the Program Customer is archived ([DELETE /customers/:uid](https://developers.newline53.com/reference/delete_customers-uid)).
   */
  async archive(
    request: operations.DeleteSyntheticAccountRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteSyntheticAccountResponse | undefined> {
    return unwrapAsync(syntheticAccountsArchive(
      this,
      request,
      options,
    ));
  }

  /**
   * List Synthetic Account Closing Balances
   *
   * @remarks
   * Retrieves a paginated list of Synthetic Account Closing balances, filtered by various parameters.
   */
  async listClosingBalances(
    request?: operations.ListSyntheticAccountClosingBalancesRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListSyntheticAccountClosingBalancesResponse> {
    return unwrapAsync(syntheticAccountsListClosingBalances(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a single Synthetic Account Closing Balance
   */
  async getClosingBalance(
    request: operations.GetSyntheticAccountClosingBalanceRequest,
    options?: RequestOptions,
  ): Promise<operations.GetSyntheticAccountClosingBalanceResponse> {
    return unwrapAsync(syntheticAccountsGetClosingBalance(
      this,
      request,
      options,
    ));
  }
}
