/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { transfersCancel } from "../funcs/transfers-cancel.js";
import { transfersGet } from "../funcs/transfers-get.js";
import { transfersInitiate } from "../funcs/transfers-initiate.js";
import { transfersList } from "../funcs/transfers-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Transfers extends ClientSDK {
  /**
   * List Transfers
   *
   * @remarks
   * Retrieves a list of Transfers filtered by the given parameters. Transfers facilitate the movement of assets between accounts, enabling transactions such as payments and withdrawals.
   */
  async list(
    request?: operations.ListTransfersRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListTransfersResponse> {
    return unwrapAsync(transfersList(
      this,
      request,
      options,
    ));
  }

  /**
   * Initiate a Transfer
   *
   * @remarks
   * Attempt to initiate a Transfer between two Synthetic Accounts. Before the Transfer will be initiated, several checks will be performed to ensure there is sufficient balance in the source account and that the initiating Customer has all the necessary access to both Synthetic Accounts.
   *
   * The Synthetic Accounts allowed in a Transfer request are listed below
   *
   * - between a liability Synthetic Account in the `general` category and a Synthetic Account in the `ach_external`, `wire_external`, or `instant_payments_external` category
   * - between two liability Synthetic Accounts in the `general` category that are also owned by the same Customer.
   *
   * > **Note**
   * > Please note that if utilizing the Transmitter information, the initiator type should be set to transmitter. If not set, the field defaults to customer and any data provided in that field will be ignored.
   */
  async initiate(
    request: operations.CreateTransferRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateTransferResponse> {
    return unwrapAsync(transfersInitiate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a single Transfer
   *
   * @remarks
   * Retrieves a single Transfer resource along with its details, including status, participating accounts, and associated Transactions.
   *
   * Filter parameters are not case sensitive but will only return exact matches.
   */
  async get(
    request: operations.GetTransferRequest,
    options?: RequestOptions,
  ): Promise<operations.GetTransferResponse> {
    return unwrapAsync(transfersGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Cancel a Transfer
   *
   * @remarks
   * Transfers must be canceled by the originating Customer (or Authorized Representative).
   *
   * Transfers can only enter the canceled state if Newline receives a request while the Transfer is in `queued` or `pending states`.
   *
   * A cancellation request during the `pending` state is not guaranteed, as this state may include payment execution. At that stage, a cancel request will result in an error.
   */
  async cancel(
    request: operations.PutTransfersUidCancelRequest,
    options?: RequestOptions,
  ): Promise<operations.PutTransfersUidCancelResponse> {
    return unwrapAsync(transfersCancel(
      this,
      request,
      options,
    ));
  }
}
