// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/optionalnullable"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"time"
)

// CustomerTypeRequest - The type of Customer. Defaults to `primary`.
type CustomerTypeRequest string

const (
	CustomerTypeRequestPrimary        CustomerTypeRequest = "primary"
	CustomerTypeRequestSecondary      CustomerTypeRequest = "secondary"
	CustomerTypeRequestSoleProprietor CustomerTypeRequest = "sole_proprietor"
)

func (e CustomerTypeRequest) ToPointer() *CustomerTypeRequest {
	return &e
}
func (e *CustomerTypeRequest) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "primary":
		fallthrough
	case "secondary":
		fallthrough
	case "sole_proprietor":
		*e = CustomerTypeRequest(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CustomerTypeRequest: %v", v)
	}
}

type CreateCustomerAddressRequest struct {
	// Maximum 35 characters
	Street1 *string `json:"street1"`
	// Maximum 35 characters
	Street2 optionalnullable.OptionalNullable[string] `json:"street2,omitempty"`
	// Maximum 35 characters
	City *string `json:"city"`
	// 2 characters. Must be a valid US state abbreviation.
	State *string `json:"state"`
	// 5-digit string. ZIP+4 is allowed.
	PostalCode *string `json:"postal_code"`
}

func (o *CreateCustomerAddressRequest) GetStreet1() *string {
	if o == nil {
		return nil
	}
	return o.Street1
}

func (o *CreateCustomerAddressRequest) GetStreet2() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Street2
}

func (o *CreateCustomerAddressRequest) GetCity() *string {
	if o == nil {
		return nil
	}
	return o.City
}

func (o *CreateCustomerAddressRequest) GetState() *string {
	if o == nil {
		return nil
	}
	return o.State
}

func (o *CreateCustomerAddressRequest) GetPostalCode() *string {
	if o == nil {
		return nil
	}
	return o.PostalCode
}

// CreateCustomerDetailsRequest - An object containing the supplied identifying information for the Customer
type CreateCustomerDetailsRequest struct {
	// 1-40 characters
	FirstName optionalnullable.OptionalNullable[string] `json:"first_name,omitempty"`
	// 1-40 characters
	MiddleName optionalnullable.OptionalNullable[string] `json:"middle_name,omitempty"`
	// 1-40 characters
	LastName optionalnullable.OptionalNullable[string] `json:"last_name,omitempty"`
	// 1-30 characters
	Suffix optionalnullable.OptionalNullable[string] `json:"suffix,omitempty"`
	// Exactly 10 digits long (no hyphens, parentheses, or spaces)
	Phone optionalnullable.OptionalNullable[string] `json:"phone,omitempty"`
	// Required for customers of type `sole_proprietor` and discarded otherwise. 1-256 alphanumeric characters.
	BusinessName optionalnullable.OptionalNullable[string] `json:"business_name,omitempty"`
	// Follows pattern 'ddd-dd-dddd'. Required for `primary` or `sole_proprietor` customers.
	Ssn optionalnullable.OptionalNullable[string] `json:"ssn,omitempty"`
	// Follows pattern 'YYYY-MM-DD'
	Dob     optionalnullable.OptionalNullable[types.Date] `json:"dob,omitempty"`
	Address *CreateCustomerAddressRequest                 `json:"address,omitempty"`
}

func (c CreateCustomerDetailsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateCustomerDetailsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *CreateCustomerDetailsRequest) GetFirstName() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.FirstName
}

func (o *CreateCustomerDetailsRequest) GetMiddleName() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.MiddleName
}

func (o *CreateCustomerDetailsRequest) GetLastName() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.LastName
}

func (o *CreateCustomerDetailsRequest) GetSuffix() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Suffix
}

func (o *CreateCustomerDetailsRequest) GetPhone() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Phone
}

func (o *CreateCustomerDetailsRequest) GetBusinessName() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.BusinessName
}

func (o *CreateCustomerDetailsRequest) GetSsn() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Ssn
}

func (o *CreateCustomerDetailsRequest) GetDob() optionalnullable.OptionalNullable[types.Date] {
	if o == nil {
		return nil
	}
	return o.Dob
}

func (o *CreateCustomerDetailsRequest) GetAddress() *CreateCustomerAddressRequest {
	if o == nil {
		return nil
	}
	return o.Address
}

type CreateCustomerRequest struct {
	// The type of Customer. Defaults to `primary`.
	//
	CustomerType *CustomerTypeRequest `json:"customer_type,omitempty"`
	// The UID of the Primary Customer with whom this Secondary Customer will be affiliated. Required for and only applicable to requests with customer_type `secondary`. Cannot be updated later from the initial value.
	//
	PrimaryCustomerUID optionalnullable.OptionalNullable[string] `json:"primary_customer_uid,omitempty"`
	// Indicates whether the client has already performed identity verification of the Customer. The client's Program must be configured to accept this value. All Customers in a Program configured for this value must submit true in this field to complete onboarding. This value defaults to `false`.
	//
	ClientVerified optionalnullable.OptionalNullable[bool] `json:"client_verified,omitempty"`
	// An optional Customer identifier supplied by the Partner. If supplied, must be unique among the collection of all Partner's Customers.
	//
	ExternalUID optionalnullable.OptionalNullable[string] `json:"external_uid,omitempty"`
	// Email of the Customer
	Email   optionalnullable.OptionalNullable[string] `json:"email,omitempty"`
	Details *CreateCustomerDetailsRequest             `json:"details,omitempty"`
}

func (o *CreateCustomerRequest) GetCustomerType() *CustomerTypeRequest {
	if o == nil {
		return nil
	}
	return o.CustomerType
}

func (o *CreateCustomerRequest) GetPrimaryCustomerUID() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.PrimaryCustomerUID
}

func (o *CreateCustomerRequest) GetClientVerified() optionalnullable.OptionalNullable[bool] {
	if o == nil {
		return nil
	}
	return o.ClientVerified
}

func (o *CreateCustomerRequest) GetExternalUID() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.ExternalUID
}

func (o *CreateCustomerRequest) GetEmail() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *CreateCustomerRequest) GetDetails() *CreateCustomerDetailsRequest {
	if o == nil {
		return nil
	}
	return o.Details
}

// CreateCustomerCustomerTypeResponse - The type of Customer
type CreateCustomerCustomerTypeResponse string

const (
	CreateCustomerCustomerTypeResponsePrimary        CreateCustomerCustomerTypeResponse = "primary"
	CreateCustomerCustomerTypeResponseSecondary      CreateCustomerCustomerTypeResponse = "secondary"
	CreateCustomerCustomerTypeResponseSoleProprietor CreateCustomerCustomerTypeResponse = "sole_proprietor"
	CreateCustomerCustomerTypeResponseSubLedger      CreateCustomerCustomerTypeResponse = "sub_ledger"
)

func (e CreateCustomerCustomerTypeResponse) ToPointer() *CreateCustomerCustomerTypeResponse {
	return &e
}
func (e *CreateCustomerCustomerTypeResponse) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "primary":
		fallthrough
	case "secondary":
		fallthrough
	case "sole_proprietor":
		fallthrough
	case "sub_ledger":
		*e = CreateCustomerCustomerTypeResponse(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateCustomerCustomerTypeResponse: %v", v)
	}
}

// CreateCustomerKycStatus - A value indicating the state of KYC/AML evaluation.
type CreateCustomerKycStatus string

const (
	CreateCustomerKycStatusManualReview             CreateCustomerKycStatus = "manual_review"
	CreateCustomerKycStatusApproved                 CreateCustomerKycStatus = "approved"
	CreateCustomerKycStatusDenied                   CreateCustomerKycStatus = "denied"
	CreateCustomerKycStatusPendingIDDocuments       CreateCustomerKycStatus = "pending_id_documents"
	CreateCustomerKycStatusPendingPoaDocuments      CreateCustomerKycStatus = "pending_poa_documents"
	CreateCustomerKycStatusPendingIdandpoaDocuments CreateCustomerKycStatus = "pending_idandpoa_documents"
	CreateCustomerKycStatusDocumentsProvided        CreateCustomerKycStatus = "documents_provided"
	CreateCustomerKycStatusDocumentsRejected        CreateCustomerKycStatus = "documents_rejected"
	CreateCustomerKycStatusRetakeImages             CreateCustomerKycStatus = "retake_images"
	CreateCustomerKycStatusPreVerified              CreateCustomerKycStatus = "pre_verified"
)

func (e CreateCustomerKycStatus) ToPointer() *CreateCustomerKycStatus {
	return &e
}
func (e *CreateCustomerKycStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "manual_review":
		fallthrough
	case "approved":
		fallthrough
	case "denied":
		fallthrough
	case "pending_id_documents":
		fallthrough
	case "pending_poa_documents":
		fallthrough
	case "pending_idandpoa_documents":
		fallthrough
	case "documents_provided":
		fallthrough
	case "documents_rejected":
		fallthrough
	case "retake_images":
		fallthrough
	case "pre_verified":
		*e = CreateCustomerKycStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateCustomerKycStatus: %v", v)
	}
}

type CreateCustomerKycStatusReason string

const (
	CreateCustomerKycStatusReasonApproved                                     CreateCustomerKycStatusReason = "Approved"
	CreateCustomerKycStatusReasonValidDocumentsProvided                       CreateCustomerKycStatusReason = "Valid Documents Provided"
	CreateCustomerKycStatusReasonArchivedDueToApplicationInactivity           CreateCustomerKycStatusReason = "Archived due to application inactivity"
	CreateCustomerKycStatusReasonFurtherReviewRequired                        CreateCustomerKycStatusReason = "Further review required"
	CreateCustomerKycStatusReasonMinorAgeLessThan18Years                      CreateCustomerKycStatusReason = "Minor (age < 18 years)"
	CreateCustomerKycStatusReasonInvalidDocumentsSubmittedMultipleTimes       CreateCustomerKycStatusReason = "Invalid Documents submitted multiple times"
	CreateCustomerKycStatusReasonMinimumRequirementsToOpenAnAccountWereNotMet CreateCustomerKycStatusReason = "Minimum requirements to open an account were not met"
	CreateCustomerKycStatusReasonInvalidDocuments                             CreateCustomerKycStatusReason = "Invalid documents"
	CreateCustomerKycStatusReasonIncorrectDocumentProvidedForIDDocument       CreateCustomerKycStatusReason = "Incorrect document provided for ID document"
	CreateCustomerKycStatusReasonExpiredID                                    CreateCustomerKycStatusReason = "Expired ID"
	CreateCustomerKycStatusReasonIllegibleIDDocument                          CreateCustomerKycStatusReason = "Illegible ID document"
	CreateCustomerKycStatusReasonIncorrectDocumentProvidedForPoaDocument      CreateCustomerKycStatusReason = "Incorrect document provided for POA document"
	CreateCustomerKycStatusReasonInvalidPoaProvided                           CreateCustomerKycStatusReason = "Invalid POA provided"
	CreateCustomerKycStatusReasonIllegiblePoaDocument                         CreateCustomerKycStatusReason = "Illegible POA document"
)

func (e CreateCustomerKycStatusReason) ToPointer() *CreateCustomerKycStatusReason {
	return &e
}
func (e *CreateCustomerKycStatusReason) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Approved":
		fallthrough
	case "Valid Documents Provided":
		fallthrough
	case "Archived due to application inactivity":
		fallthrough
	case "Further review required":
		fallthrough
	case "Minor (age < 18 years)":
		fallthrough
	case "Invalid Documents submitted multiple times":
		fallthrough
	case "Minimum requirements to open an account were not met":
		fallthrough
	case "Invalid documents":
		fallthrough
	case "Incorrect document provided for ID document":
		fallthrough
	case "Expired ID":
		fallthrough
	case "Illegible ID document":
		fallthrough
	case "Incorrect document provided for POA document":
		fallthrough
	case "Invalid POA provided":
		fallthrough
	case "Illegible POA document":
		*e = CreateCustomerKycStatusReason(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateCustomerKycStatusReason: %v", v)
	}
}

type CreateCustomerProfileResponse struct {
	// A statement that requires a response in order to onboard a Customer for a Product
	ProfileRequirement *string `json:"profile_requirement,omitempty"`
	// The Customer's response to the Profile Requirement as a single string value.
	ProfileResponse *string `json:"profile_response,omitempty"`
	// A UID referring to the Profile Requirement
	ProfileRequirementUID *string `json:"profile_requirement_uid,omitempty"`
}

func (o *CreateCustomerProfileResponse) GetProfileRequirement() *string {
	if o == nil {
		return nil
	}
	return o.ProfileRequirement
}

func (o *CreateCustomerProfileResponse) GetProfileResponse() *string {
	if o == nil {
		return nil
	}
	return o.ProfileResponse
}

func (o *CreateCustomerProfileResponse) GetProfileRequirementUID() *string {
	if o == nil {
		return nil
	}
	return o.ProfileRequirementUID
}

// CreateCustomerStatus - A value indicating the overall state of this Customer.
type CreateCustomerStatus string

const (
	CreateCustomerStatusInitiated        CreateCustomerStatus = "initiated"
	CreateCustomerStatusQueued           CreateCustomerStatus = "queued"
	CreateCustomerStatusIdentityVerified CreateCustomerStatus = "identity_verified"
	CreateCustomerStatusActive           CreateCustomerStatus = "active"
	CreateCustomerStatusManualReview     CreateCustomerStatus = "manual_review"
	CreateCustomerStatusRejected         CreateCustomerStatus = "rejected"
	CreateCustomerStatusPendingArchival  CreateCustomerStatus = "pending_archival"
	CreateCustomerStatusArchived         CreateCustomerStatus = "archived"
	CreateCustomerStatusUnderReview      CreateCustomerStatus = "under_review"
)

func (e CreateCustomerStatus) ToPointer() *CreateCustomerStatus {
	return &e
}
func (e *CreateCustomerStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "initiated":
		fallthrough
	case "queued":
		fallthrough
	case "identity_verified":
		fallthrough
	case "active":
		fallthrough
	case "manual_review":
		fallthrough
	case "rejected":
		fallthrough
	case "pending_archival":
		fallthrough
	case "archived":
		fallthrough
	case "under_review":
		*e = CreateCustomerStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateCustomerStatus: %v", v)
	}
}

type CreateCustomerAddressResponse struct {
	// Maximum 35 characters
	Street1 *string `json:"street1"`
	// Maximum 35 characters
	Street2 optionalnullable.OptionalNullable[string] `json:"street2,omitempty"`
	// Maximum 35 characters
	City *string `json:"city"`
	// 2 characters. Must be a valid US state abbreviation.
	State *string `json:"state"`
	// 5-digit string. ZIP+4 is allowed.
	PostalCode *string `json:"postal_code"`
}

func (o *CreateCustomerAddressResponse) GetStreet1() *string {
	if o == nil {
		return nil
	}
	return o.Street1
}

func (o *CreateCustomerAddressResponse) GetStreet2() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Street2
}

func (o *CreateCustomerAddressResponse) GetCity() *string {
	if o == nil {
		return nil
	}
	return o.City
}

func (o *CreateCustomerAddressResponse) GetState() *string {
	if o == nil {
		return nil
	}
	return o.State
}

func (o *CreateCustomerAddressResponse) GetPostalCode() *string {
	if o == nil {
		return nil
	}
	return o.PostalCode
}

// CreateCustomerDetailsOutput - An object containing the supplied identifying information for the Customer
type CreateCustomerDetailsOutput struct {
	// 1-40 characters
	FirstName optionalnullable.OptionalNullable[string] `json:"first_name,omitempty"`
	// 1-40 characters
	MiddleName optionalnullable.OptionalNullable[string] `json:"middle_name,omitempty"`
	// 1-40 characters
	LastName optionalnullable.OptionalNullable[string] `json:"last_name,omitempty"`
	// 1-30 characters
	Suffix optionalnullable.OptionalNullable[string] `json:"suffix,omitempty"`
	// Exactly 10 digits long (no hyphens, parentheses, or spaces)
	Phone optionalnullable.OptionalNullable[string] `json:"phone,omitempty"`
	// Required for customers of type `sole_proprietor` and discarded otherwise. 1-256 alphanumeric characters.
	BusinessName optionalnullable.OptionalNullable[string] `json:"business_name,omitempty"`
	SsnLastFour  optionalnullable.OptionalNullable[string] `json:"ssn_last_four,omitempty"`
	// Follows pattern 'YYYY-MM-DD'
	Dob     optionalnullable.OptionalNullable[types.Date] `json:"dob,omitempty"`
	Address *CreateCustomerAddressResponse                `json:"address,omitempty"`
}

func (c CreateCustomerDetailsOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateCustomerDetailsOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *CreateCustomerDetailsOutput) GetFirstName() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.FirstName
}

func (o *CreateCustomerDetailsOutput) GetMiddleName() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.MiddleName
}

func (o *CreateCustomerDetailsOutput) GetLastName() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.LastName
}

func (o *CreateCustomerDetailsOutput) GetSuffix() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Suffix
}

func (o *CreateCustomerDetailsOutput) GetPhone() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Phone
}

func (o *CreateCustomerDetailsOutput) GetBusinessName() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.BusinessName
}

func (o *CreateCustomerDetailsOutput) GetSsnLastFour() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.SsnLastFour
}

func (o *CreateCustomerDetailsOutput) GetDob() optionalnullable.OptionalNullable[types.Date] {
	if o == nil {
		return nil
	}
	return o.Dob
}

func (o *CreateCustomerDetailsOutput) GetAddress() *CreateCustomerAddressResponse {
	if o == nil {
		return nil
	}
	return o.Address
}

// CreateCustomerResponseBody - A newly created Customer is returned
type CreateCustomerResponseBody struct {
	// Newline-generated unique id resource specific to the current endpoint
	UID *string `json:"uid,omitempty"`
	// A unique identifier the Client supplies. It must be unique within the resource type. If the same value is given, no new resource will be created.
	//
	ExternalUID *string `json:"external_uid,omitempty"`
	// The date and time at which this Customer was activated.
	ActivatedAt *time.Time `json:"activated_at,omitempty"`
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	// The type of Customer
	//
	CustomerType *CreateCustomerCustomerTypeResponse `json:"customer_type,omitempty"`
	// Email of the Customer
	Email *string `json:"email,omitempty"`
	// Indicates whether or not the client is responsible for identity verification of this Customer. If true, the `kyc_status` will be "pre_verified".
	ClientVerified *bool `json:"client_verified,omitempty"`
	// A value indicating the state of KYC/AML evaluation.
	//
	KycStatus optionalnullable.OptionalNullable[CreateCustomerKycStatus] `json:"kyc_status,omitempty"`
	// A list of reasons for the current `kyc_status`.
	KycStatusReasons optionalnullable.OptionalNullable[[]CreateCustomerKycStatusReason] `json:"kyc_status_reasons,omitempty"`
	// The lock reason provided by the Client, an admin User, or the system at the time the Customer was locked. This field will be null if and only if the `locked_at` is null.
	//
	LockReason optionalnullable.OptionalNullable[string] `json:"lock_reason,omitempty"`
	// The date and time when the Customer was locked. This field will be null if and only if the `lock_reason` is null.
	//
	LockedAt optionalnullable.OptionalNullable[time.Time] `json:"locked_at,omitempty"`
	// The date and time when the Customer's PII was last confirmed to be accurate
	//
	PiiConfirmedAt *time.Time `json:"pii_confirmed_at,omitempty"`
	// A list of uids referring to Pools belonging to this Customer.
	PoolUids []string `json:"pool_uids,omitempty"`
	// The UID of the primary Customer. Null unless the customer type is `secondary`.
	PrimaryCustomerUID optionalnullable.OptionalNullable[string] `json:"primary_customer_uid,omitempty"`
	// A list of Profile Responses submitted by the Customer
	ProfileResponses []CreateCustomerProfileResponse `json:"profile_responses,omitempty"`
	// A UID referring to the program this customer belongs to
	ProgramUID *string `json:"program_uid,omitempty"`
	// The UIDs of secondary Customers. Null unless the customer type is `primary`.
	SecondaryCustomerUids optionalnullable.OptionalNullable[[]string] `json:"secondary_customer_uids,omitempty"`
	// A value indicating the overall state of this Customer.
	//
	Status *CreateCustomerStatus `json:"status,omitempty"`
	// Total asset owned by the customer in US dollars
	TotalBalance *string `json:"total_balance,omitempty"`
	// If the Customer's status is `archived` this will have the time at which they were archived.
	//
	ArchivedAt optionalnullable.OptionalNullable[time.Time] `json:"archived_at,omitempty"`
	Details    *CreateCustomerDetailsOutput                 `json:"details,omitempty"`
}

func (c CreateCustomerResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateCustomerResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *CreateCustomerResponseBody) GetUID() *string {
	if o == nil {
		return nil
	}
	return o.UID
}

func (o *CreateCustomerResponseBody) GetExternalUID() *string {
	if o == nil {
		return nil
	}
	return o.ExternalUID
}

func (o *CreateCustomerResponseBody) GetActivatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ActivatedAt
}

func (o *CreateCustomerResponseBody) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *CreateCustomerResponseBody) GetCustomerType() *CreateCustomerCustomerTypeResponse {
	if o == nil {
		return nil
	}
	return o.CustomerType
}

func (o *CreateCustomerResponseBody) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *CreateCustomerResponseBody) GetClientVerified() *bool {
	if o == nil {
		return nil
	}
	return o.ClientVerified
}

func (o *CreateCustomerResponseBody) GetKycStatus() optionalnullable.OptionalNullable[CreateCustomerKycStatus] {
	if o == nil {
		return nil
	}
	return o.KycStatus
}

func (o *CreateCustomerResponseBody) GetKycStatusReasons() optionalnullable.OptionalNullable[[]CreateCustomerKycStatusReason] {
	if o == nil {
		return nil
	}
	return o.KycStatusReasons
}

func (o *CreateCustomerResponseBody) GetLockReason() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.LockReason
}

func (o *CreateCustomerResponseBody) GetLockedAt() optionalnullable.OptionalNullable[time.Time] {
	if o == nil {
		return nil
	}
	return o.LockedAt
}

func (o *CreateCustomerResponseBody) GetPiiConfirmedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.PiiConfirmedAt
}

func (o *CreateCustomerResponseBody) GetPoolUids() []string {
	if o == nil {
		return nil
	}
	return o.PoolUids
}

func (o *CreateCustomerResponseBody) GetPrimaryCustomerUID() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.PrimaryCustomerUID
}

func (o *CreateCustomerResponseBody) GetProfileResponses() []CreateCustomerProfileResponse {
	if o == nil {
		return nil
	}
	return o.ProfileResponses
}

func (o *CreateCustomerResponseBody) GetProgramUID() *string {
	if o == nil {
		return nil
	}
	return o.ProgramUID
}

func (o *CreateCustomerResponseBody) GetSecondaryCustomerUids() optionalnullable.OptionalNullable[[]string] {
	if o == nil {
		return nil
	}
	return o.SecondaryCustomerUids
}

func (o *CreateCustomerResponseBody) GetStatus() *CreateCustomerStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *CreateCustomerResponseBody) GetTotalBalance() *string {
	if o == nil {
		return nil
	}
	return o.TotalBalance
}

func (o *CreateCustomerResponseBody) GetArchivedAt() optionalnullable.OptionalNullable[time.Time] {
	if o == nil {
		return nil
	}
	return o.ArchivedAt
}

func (o *CreateCustomerResponseBody) GetDetails() *CreateCustomerDetailsOutput {
	if o == nil {
		return nil
	}
	return o.Details
}

type CreateCustomerResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A newly created Customer is returned
	Object  *CreateCustomerResponseBody
	Headers map[string][]string
}

func (o *CreateCustomerResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateCustomerResponse) GetObject() *CreateCustomerResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *CreateCustomerResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
