// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/optionalnullable"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"time"
)

type DeleteCustomerRequestBody struct {
	ArchiveNote   optionalnullable.OptionalNullable[string] `json:"archive_note,omitempty"`
	CanApplyAgain optionalnullable.OptionalNullable[bool]   `default:"true" json:"can_apply_again"`
	// UID of an active external Synthetic Account to which the Customer's funds should be sent, if any. Required if the Customer has multiple active external Synthetic Accounts.
	//
	DestinationSyntheticAccountUID *string `json:"destination_synthetic_account_uid,omitempty"`
}

func (d DeleteCustomerRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteCustomerRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *DeleteCustomerRequestBody) GetArchiveNote() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.ArchiveNote
}

func (o *DeleteCustomerRequestBody) GetCanApplyAgain() optionalnullable.OptionalNullable[bool] {
	if o == nil {
		return nil
	}
	return o.CanApplyAgain
}

func (o *DeleteCustomerRequestBody) GetDestinationSyntheticAccountUID() *string {
	if o == nil {
		return nil
	}
	return o.DestinationSyntheticAccountUID
}

type DeleteCustomerRequest struct {
	// Newline-generated unique id resource specific to the current endpoint
	UID  string                    `pathParam:"style=simple,explode=false,name=uid"`
	Body DeleteCustomerRequestBody `request:"mediaType=application/json"`
}

func (o *DeleteCustomerRequest) GetUID() string {
	if o == nil {
		return ""
	}
	return o.UID
}

func (o *DeleteCustomerRequest) GetBody() DeleteCustomerRequestBody {
	if o == nil {
		return DeleteCustomerRequestBody{}
	}
	return o.Body
}

// DeleteCustomerCustomerType - The type of Customer
type DeleteCustomerCustomerType string

const (
	DeleteCustomerCustomerTypePrimary        DeleteCustomerCustomerType = "primary"
	DeleteCustomerCustomerTypeSecondary      DeleteCustomerCustomerType = "secondary"
	DeleteCustomerCustomerTypeSoleProprietor DeleteCustomerCustomerType = "sole_proprietor"
	DeleteCustomerCustomerTypeSubLedger      DeleteCustomerCustomerType = "sub_ledger"
)

func (e DeleteCustomerCustomerType) ToPointer() *DeleteCustomerCustomerType {
	return &e
}
func (e *DeleteCustomerCustomerType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "primary":
		fallthrough
	case "secondary":
		fallthrough
	case "sole_proprietor":
		fallthrough
	case "sub_ledger":
		*e = DeleteCustomerCustomerType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DeleteCustomerCustomerType: %v", v)
	}
}

// DeleteCustomerKycStatus - A value indicating the state of KYC/AML evaluation.
type DeleteCustomerKycStatus string

const (
	DeleteCustomerKycStatusManualReview             DeleteCustomerKycStatus = "manual_review"
	DeleteCustomerKycStatusApproved                 DeleteCustomerKycStatus = "approved"
	DeleteCustomerKycStatusDenied                   DeleteCustomerKycStatus = "denied"
	DeleteCustomerKycStatusPendingIDDocuments       DeleteCustomerKycStatus = "pending_id_documents"
	DeleteCustomerKycStatusPendingPoaDocuments      DeleteCustomerKycStatus = "pending_poa_documents"
	DeleteCustomerKycStatusPendingIdandpoaDocuments DeleteCustomerKycStatus = "pending_idandpoa_documents"
	DeleteCustomerKycStatusDocumentsProvided        DeleteCustomerKycStatus = "documents_provided"
	DeleteCustomerKycStatusDocumentsRejected        DeleteCustomerKycStatus = "documents_rejected"
	DeleteCustomerKycStatusRetakeImages             DeleteCustomerKycStatus = "retake_images"
	DeleteCustomerKycStatusPreVerified              DeleteCustomerKycStatus = "pre_verified"
)

func (e DeleteCustomerKycStatus) ToPointer() *DeleteCustomerKycStatus {
	return &e
}
func (e *DeleteCustomerKycStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "manual_review":
		fallthrough
	case "approved":
		fallthrough
	case "denied":
		fallthrough
	case "pending_id_documents":
		fallthrough
	case "pending_poa_documents":
		fallthrough
	case "pending_idandpoa_documents":
		fallthrough
	case "documents_provided":
		fallthrough
	case "documents_rejected":
		fallthrough
	case "retake_images":
		fallthrough
	case "pre_verified":
		*e = DeleteCustomerKycStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DeleteCustomerKycStatus: %v", v)
	}
}

type DeleteCustomerKycStatusReason string

const (
	DeleteCustomerKycStatusReasonApproved                                     DeleteCustomerKycStatusReason = "Approved"
	DeleteCustomerKycStatusReasonValidDocumentsProvided                       DeleteCustomerKycStatusReason = "Valid Documents Provided"
	DeleteCustomerKycStatusReasonArchivedDueToApplicationInactivity           DeleteCustomerKycStatusReason = "Archived due to application inactivity"
	DeleteCustomerKycStatusReasonFurtherReviewRequired                        DeleteCustomerKycStatusReason = "Further review required"
	DeleteCustomerKycStatusReasonMinorAgeLessThan18Years                      DeleteCustomerKycStatusReason = "Minor (age < 18 years)"
	DeleteCustomerKycStatusReasonInvalidDocumentsSubmittedMultipleTimes       DeleteCustomerKycStatusReason = "Invalid Documents submitted multiple times"
	DeleteCustomerKycStatusReasonMinimumRequirementsToOpenAnAccountWereNotMet DeleteCustomerKycStatusReason = "Minimum requirements to open an account were not met"
	DeleteCustomerKycStatusReasonInvalidDocuments                             DeleteCustomerKycStatusReason = "Invalid documents"
	DeleteCustomerKycStatusReasonIncorrectDocumentProvidedForIDDocument       DeleteCustomerKycStatusReason = "Incorrect document provided for ID document"
	DeleteCustomerKycStatusReasonExpiredID                                    DeleteCustomerKycStatusReason = "Expired ID"
	DeleteCustomerKycStatusReasonIllegibleIDDocument                          DeleteCustomerKycStatusReason = "Illegible ID document"
	DeleteCustomerKycStatusReasonIncorrectDocumentProvidedForPoaDocument      DeleteCustomerKycStatusReason = "Incorrect document provided for POA document"
	DeleteCustomerKycStatusReasonInvalidPoaProvided                           DeleteCustomerKycStatusReason = "Invalid POA provided"
	DeleteCustomerKycStatusReasonIllegiblePoaDocument                         DeleteCustomerKycStatusReason = "Illegible POA document"
)

func (e DeleteCustomerKycStatusReason) ToPointer() *DeleteCustomerKycStatusReason {
	return &e
}
func (e *DeleteCustomerKycStatusReason) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Approved":
		fallthrough
	case "Valid Documents Provided":
		fallthrough
	case "Archived due to application inactivity":
		fallthrough
	case "Further review required":
		fallthrough
	case "Minor (age < 18 years)":
		fallthrough
	case "Invalid Documents submitted multiple times":
		fallthrough
	case "Minimum requirements to open an account were not met":
		fallthrough
	case "Invalid documents":
		fallthrough
	case "Incorrect document provided for ID document":
		fallthrough
	case "Expired ID":
		fallthrough
	case "Illegible ID document":
		fallthrough
	case "Incorrect document provided for POA document":
		fallthrough
	case "Invalid POA provided":
		fallthrough
	case "Illegible POA document":
		*e = DeleteCustomerKycStatusReason(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DeleteCustomerKycStatusReason: %v", v)
	}
}

type DeleteCustomerProfileResponse struct {
	// A statement that requires a response in order to onboard a Customer for a Product
	ProfileRequirement *string `json:"profile_requirement,omitempty"`
	// The Customer's response to the Profile Requirement as a single string value.
	ProfileResponse *string `json:"profile_response,omitempty"`
	// A UID referring to the Profile Requirement
	ProfileRequirementUID *string `json:"profile_requirement_uid,omitempty"`
}

func (o *DeleteCustomerProfileResponse) GetProfileRequirement() *string {
	if o == nil {
		return nil
	}
	return o.ProfileRequirement
}

func (o *DeleteCustomerProfileResponse) GetProfileResponse() *string {
	if o == nil {
		return nil
	}
	return o.ProfileResponse
}

func (o *DeleteCustomerProfileResponse) GetProfileRequirementUID() *string {
	if o == nil {
		return nil
	}
	return o.ProfileRequirementUID
}

// DeleteCustomerStatus - A value indicating the overall state of this Customer.
type DeleteCustomerStatus string

const (
	DeleteCustomerStatusInitiated        DeleteCustomerStatus = "initiated"
	DeleteCustomerStatusQueued           DeleteCustomerStatus = "queued"
	DeleteCustomerStatusIdentityVerified DeleteCustomerStatus = "identity_verified"
	DeleteCustomerStatusActive           DeleteCustomerStatus = "active"
	DeleteCustomerStatusManualReview     DeleteCustomerStatus = "manual_review"
	DeleteCustomerStatusRejected         DeleteCustomerStatus = "rejected"
	DeleteCustomerStatusPendingArchival  DeleteCustomerStatus = "pending_archival"
	DeleteCustomerStatusArchived         DeleteCustomerStatus = "archived"
	DeleteCustomerStatusUnderReview      DeleteCustomerStatus = "under_review"
)

func (e DeleteCustomerStatus) ToPointer() *DeleteCustomerStatus {
	return &e
}
func (e *DeleteCustomerStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "initiated":
		fallthrough
	case "queued":
		fallthrough
	case "identity_verified":
		fallthrough
	case "active":
		fallthrough
	case "manual_review":
		fallthrough
	case "rejected":
		fallthrough
	case "pending_archival":
		fallthrough
	case "archived":
		fallthrough
	case "under_review":
		*e = DeleteCustomerStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DeleteCustomerStatus: %v", v)
	}
}

type DeleteCustomerAddress struct {
	// Maximum 35 characters
	Street1 *string `json:"street1"`
	// Maximum 35 characters
	Street2 optionalnullable.OptionalNullable[string] `json:"street2,omitempty"`
	// Maximum 35 characters
	City *string `json:"city"`
	// 2 characters. Must be a valid US state abbreviation.
	State *string `json:"state"`
	// 5-digit string. ZIP+4 is allowed.
	PostalCode *string `json:"postal_code"`
}

func (o *DeleteCustomerAddress) GetStreet1() *string {
	if o == nil {
		return nil
	}
	return o.Street1
}

func (o *DeleteCustomerAddress) GetStreet2() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Street2
}

func (o *DeleteCustomerAddress) GetCity() *string {
	if o == nil {
		return nil
	}
	return o.City
}

func (o *DeleteCustomerAddress) GetState() *string {
	if o == nil {
		return nil
	}
	return o.State
}

func (o *DeleteCustomerAddress) GetPostalCode() *string {
	if o == nil {
		return nil
	}
	return o.PostalCode
}

// DeleteCustomerDetails - An object containing the supplied identifying information for the Customer
type DeleteCustomerDetails struct {
	// 1-40 characters
	FirstName optionalnullable.OptionalNullable[string] `json:"first_name,omitempty"`
	// 1-40 characters
	MiddleName optionalnullable.OptionalNullable[string] `json:"middle_name,omitempty"`
	// 1-40 characters
	LastName optionalnullable.OptionalNullable[string] `json:"last_name,omitempty"`
	// 1-30 characters
	Suffix optionalnullable.OptionalNullable[string] `json:"suffix,omitempty"`
	// Exactly 10 digits long (no hyphens, parentheses, or spaces)
	Phone optionalnullable.OptionalNullable[string] `json:"phone,omitempty"`
	// Required for customers of type `sole_proprietor` and discarded otherwise. 1-256 alphanumeric characters.
	BusinessName optionalnullable.OptionalNullable[string] `json:"business_name,omitempty"`
	SsnLastFour  optionalnullable.OptionalNullable[string] `json:"ssn_last_four,omitempty"`
	// Follows pattern 'YYYY-MM-DD'
	Dob     optionalnullable.OptionalNullable[types.Date] `json:"dob,omitempty"`
	Address *DeleteCustomerAddress                        `json:"address,omitempty"`
}

func (d DeleteCustomerDetails) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteCustomerDetails) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *DeleteCustomerDetails) GetFirstName() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.FirstName
}

func (o *DeleteCustomerDetails) GetMiddleName() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.MiddleName
}

func (o *DeleteCustomerDetails) GetLastName() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.LastName
}

func (o *DeleteCustomerDetails) GetSuffix() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Suffix
}

func (o *DeleteCustomerDetails) GetPhone() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Phone
}

func (o *DeleteCustomerDetails) GetBusinessName() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.BusinessName
}

func (o *DeleteCustomerDetails) GetSsnLastFour() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.SsnLastFour
}

func (o *DeleteCustomerDetails) GetDob() optionalnullable.OptionalNullable[types.Date] {
	if o == nil {
		return nil
	}
	return o.Dob
}

func (o *DeleteCustomerDetails) GetAddress() *DeleteCustomerAddress {
	if o == nil {
		return nil
	}
	return o.Address
}

// DeleteCustomerResponseBody - Customer has begun the archive process.
type DeleteCustomerResponseBody struct {
	// Newline-generated unique id resource specific to the current endpoint
	UID *string `json:"uid,omitempty"`
	// A unique identifier the Client supplies. It must be unique within the resource type. If the same value is given, no new resource will be created.
	//
	ExternalUID *string `json:"external_uid,omitempty"`
	// The date and time at which this Customer was activated.
	ActivatedAt *time.Time `json:"activated_at,omitempty"`
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	// The type of Customer
	//
	CustomerType *DeleteCustomerCustomerType `json:"customer_type,omitempty"`
	// Email of the Customer
	Email *string `json:"email,omitempty"`
	// Indicates whether or not the client is responsible for identity verification of this Customer. If true, the `kyc_status` will be "pre_verified".
	ClientVerified *bool `json:"client_verified,omitempty"`
	// A value indicating the state of KYC/AML evaluation.
	//
	KycStatus optionalnullable.OptionalNullable[DeleteCustomerKycStatus] `json:"kyc_status,omitempty"`
	// A list of reasons for the current `kyc_status`.
	KycStatusReasons optionalnullable.OptionalNullable[[]DeleteCustomerKycStatusReason] `json:"kyc_status_reasons,omitempty"`
	// The lock reason provided by the Client, an admin User, or the system at the time the Customer was locked. This field will be null if and only if the `locked_at` is null.
	//
	LockReason optionalnullable.OptionalNullable[string] `json:"lock_reason,omitempty"`
	// The date and time when the Customer was locked. This field will be null if and only if the `lock_reason` is null.
	//
	LockedAt optionalnullable.OptionalNullable[time.Time] `json:"locked_at,omitempty"`
	// The date and time when the Customer's PII was last confirmed to be accurate
	//
	PiiConfirmedAt *time.Time `json:"pii_confirmed_at,omitempty"`
	// A list of uids referring to Pools belonging to this Customer.
	PoolUids []string `json:"pool_uids,omitempty"`
	// The UID of the primary Customer. Null unless the customer type is `secondary`.
	PrimaryCustomerUID optionalnullable.OptionalNullable[string] `json:"primary_customer_uid,omitempty"`
	// A list of Profile Responses submitted by the Customer
	ProfileResponses []DeleteCustomerProfileResponse `json:"profile_responses,omitempty"`
	// A UID referring to the program this customer belongs to
	ProgramUID *string `json:"program_uid,omitempty"`
	// The UIDs of secondary Customers. Null unless the customer type is `primary`.
	SecondaryCustomerUids optionalnullable.OptionalNullable[[]string] `json:"secondary_customer_uids,omitempty"`
	// A value indicating the overall state of this Customer.
	//
	Status *DeleteCustomerStatus `json:"status,omitempty"`
	// Total asset owned by the customer in US dollars
	TotalBalance *string `json:"total_balance,omitempty"`
	// If the Customer's status is `archived` this will have the time at which they were archived.
	//
	ArchivedAt optionalnullable.OptionalNullable[time.Time] `json:"archived_at,omitempty"`
	Details    *DeleteCustomerDetails                       `json:"details,omitempty"`
}

func (d DeleteCustomerResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteCustomerResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *DeleteCustomerResponseBody) GetUID() *string {
	if o == nil {
		return nil
	}
	return o.UID
}

func (o *DeleteCustomerResponseBody) GetExternalUID() *string {
	if o == nil {
		return nil
	}
	return o.ExternalUID
}

func (o *DeleteCustomerResponseBody) GetActivatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ActivatedAt
}

func (o *DeleteCustomerResponseBody) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *DeleteCustomerResponseBody) GetCustomerType() *DeleteCustomerCustomerType {
	if o == nil {
		return nil
	}
	return o.CustomerType
}

func (o *DeleteCustomerResponseBody) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *DeleteCustomerResponseBody) GetClientVerified() *bool {
	if o == nil {
		return nil
	}
	return o.ClientVerified
}

func (o *DeleteCustomerResponseBody) GetKycStatus() optionalnullable.OptionalNullable[DeleteCustomerKycStatus] {
	if o == nil {
		return nil
	}
	return o.KycStatus
}

func (o *DeleteCustomerResponseBody) GetKycStatusReasons() optionalnullable.OptionalNullable[[]DeleteCustomerKycStatusReason] {
	if o == nil {
		return nil
	}
	return o.KycStatusReasons
}

func (o *DeleteCustomerResponseBody) GetLockReason() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.LockReason
}

func (o *DeleteCustomerResponseBody) GetLockedAt() optionalnullable.OptionalNullable[time.Time] {
	if o == nil {
		return nil
	}
	return o.LockedAt
}

func (o *DeleteCustomerResponseBody) GetPiiConfirmedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.PiiConfirmedAt
}

func (o *DeleteCustomerResponseBody) GetPoolUids() []string {
	if o == nil {
		return nil
	}
	return o.PoolUids
}

func (o *DeleteCustomerResponseBody) GetPrimaryCustomerUID() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.PrimaryCustomerUID
}

func (o *DeleteCustomerResponseBody) GetProfileResponses() []DeleteCustomerProfileResponse {
	if o == nil {
		return nil
	}
	return o.ProfileResponses
}

func (o *DeleteCustomerResponseBody) GetProgramUID() *string {
	if o == nil {
		return nil
	}
	return o.ProgramUID
}

func (o *DeleteCustomerResponseBody) GetSecondaryCustomerUids() optionalnullable.OptionalNullable[[]string] {
	if o == nil {
		return nil
	}
	return o.SecondaryCustomerUids
}

func (o *DeleteCustomerResponseBody) GetStatus() *DeleteCustomerStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *DeleteCustomerResponseBody) GetTotalBalance() *string {
	if o == nil {
		return nil
	}
	return o.TotalBalance
}

func (o *DeleteCustomerResponseBody) GetArchivedAt() optionalnullable.OptionalNullable[time.Time] {
	if o == nil {
		return nil
	}
	return o.ArchivedAt
}

func (o *DeleteCustomerResponseBody) GetDetails() *DeleteCustomerDetails {
	if o == nil {
		return nil
	}
	return o.Details
}

type DeleteCustomerResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Customer has begun the archive process.
	Object  *DeleteCustomerResponseBody
	Headers map[string][]string
}

func (o *DeleteCustomerResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeleteCustomerResponse) GetObject() *DeleteCustomerResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *DeleteCustomerResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
