// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type DeleteSyntheticAccountRequest struct {
	// Newline-generated unique id resource specific to the current endpoint
	UID string `pathParam:"style=simple,explode=false,name=uid"`
}

func (o *DeleteSyntheticAccountRequest) GetUID() string {
	if o == nil {
		return ""
	}
	return o.UID
}

type DeleteSyntheticAccountError struct {
	// Code provided by Newline for reference
	Code *int64 `json:"code,omitempty"`
	// Title of Error Code
	Title *string `json:"title,omitempty"`
	// Description of Error Code
	Detail *string `json:"detail,omitempty"`
	// Error Timestamp
	OccurredAt *string `json:"occurred_at,omitempty"`
	// Included based on Error Code; Additional context to help users self-solve the error
	Extra *string `json:"extra,omitempty"`
}

func (o *DeleteSyntheticAccountError) GetCode() *int64 {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *DeleteSyntheticAccountError) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *DeleteSyntheticAccountError) GetDetail() *string {
	if o == nil {
		return nil
	}
	return o.Detail
}

func (o *DeleteSyntheticAccountError) GetOccurredAt() *string {
	if o == nil {
		return nil
	}
	return o.OccurredAt
}

func (o *DeleteSyntheticAccountError) GetExtra() *string {
	if o == nil {
		return nil
	}
	return o.Extra
}

type DeleteSyntheticAccountResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Headers  map[string][]string
}

func (o *DeleteSyntheticAccountResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeleteSyntheticAccountResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
