// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/optionalnullable"
	"mockserver/internal/sdk/utils"
	"time"
)

// GetCustodialLineItemsQueryParamStatus - Filter by status. Multiple values are allowed, e.g. `status[]=pending&status[]=settled`.
type GetCustodialLineItemsQueryParamStatus string

const (
	GetCustodialLineItemsQueryParamStatusSettled GetCustodialLineItemsQueryParamStatus = "settled"
	GetCustodialLineItemsQueryParamStatusVoided  GetCustodialLineItemsQueryParamStatus = "voided"
)

func (e GetCustodialLineItemsQueryParamStatus) ToPointer() *GetCustodialLineItemsQueryParamStatus {
	return &e
}
func (e *GetCustodialLineItemsQueryParamStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "settled":
		fallthrough
	case "voided":
		*e = GetCustodialLineItemsQueryParamStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetCustodialLineItemsQueryParamStatus: %v", v)
	}
}

type GetCustodialLineItemsSort string

const (
	GetCustodialLineItemsSortCreatedAtAsc       GetCustodialLineItemsSort = "created_at_asc"
	GetCustodialLineItemsSortCreatedAtDesc      GetCustodialLineItemsSort = "created_at_desc"
	GetCustodialLineItemsSortDescriptionAsc     GetCustodialLineItemsSort = "description_asc"
	GetCustodialLineItemsSortDescriptionDesc    GetCustodialLineItemsSort = "description_desc"
	GetCustodialLineItemsSortSettledIndexAsc    GetCustodialLineItemsSort = "settled_index_asc"
	GetCustodialLineItemsSortSettledIndexDesc   GetCustodialLineItemsSort = "settled_index_desc"
	GetCustodialLineItemsSortUsDollarAmountAsc  GetCustodialLineItemsSort = "us_dollar_amount_asc"
	GetCustodialLineItemsSortUsDollarAmountDesc GetCustodialLineItemsSort = "us_dollar_amount_desc"
)

func (e GetCustodialLineItemsSort) ToPointer() *GetCustodialLineItemsSort {
	return &e
}
func (e *GetCustodialLineItemsSort) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at_asc":
		fallthrough
	case "created_at_desc":
		fallthrough
	case "description_asc":
		fallthrough
	case "description_desc":
		fallthrough
	case "settled_index_asc":
		fallthrough
	case "settled_index_desc":
		fallthrough
	case "us_dollar_amount_asc":
		fallthrough
	case "us_dollar_amount_desc":
		*e = GetCustodialLineItemsSort(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetCustodialLineItemsSort: %v", v)
	}
}

type GetCustodialLineItemsRequest struct {
	// Filter by Customer. Multiple values are allowed, e.g. `customer_uid[]=uKxmLxUEiSj5h4M3&customer_uid[]=y9reyPMNEWuuYSC1`.
	//
	CustomerUID         *string `queryParam:"style=form,explode=true,name=customer_uid"`
	CustodialAccountUID *string `queryParam:"style=form,explode=true,name=custodial_account_uid"`
	// Filter by status. Multiple values are allowed, e.g. `status[]=pending&status[]=settled`.
	//
	Status *GetCustodialLineItemsQueryParamStatus `queryParam:"style=form,explode=true,name=status"`
	// Return any records having a us_dollar_amount at or below us_dollar_amount_max.
	//
	UsDollarAmountMax *float64 `queryParam:"style=form,explode=true,name=us_dollar_amount_max"`
	// Return any records having a us_dollar_amount at or above us_dollar_amount_min.
	//
	UsDollarAmountMin *float64 `queryParam:"style=form,explode=true,name=us_dollar_amount_min"`
	// Filter by Transaction Event. Multiple values are allowed, e.g. `transaction_event_uid[]=MB2yqBrm3c4bUbou&transaction_event_uid[]=N5tuy12zZzB9bftb`.
	//
	TransactionEventUID *string `queryParam:"style=form,explode=true,name=transaction_event_uid"`
	// Filter by Transaction. Multiple values are allowed, e.g. `transaction_uid[]=SMwKC1osz77DTEiu&transaction_uid[]=f1UDvUVNnXTKtgxu`.
	//
	TransactionUID *string `queryParam:"style=form,explode=true,name=transaction_uid"`
	// Maximum number of items to retrieve. This filter is automatically applied with the default value if not given.
	//
	Limit *int64 `default:"100" queryParam:"style=form,explode=true,name=limit"`
	// Index of the items to start retrieving from
	Offset *int64                     `default:"0" queryParam:"style=form,explode=true,name=offset"`
	Sort   *GetCustodialLineItemsSort `queryParam:"style=form,explode=true,name=sort"`
}

func (g GetCustodialLineItemsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCustodialLineItemsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *GetCustodialLineItemsRequest) GetCustomerUID() *string {
	if o == nil {
		return nil
	}
	return o.CustomerUID
}

func (o *GetCustodialLineItemsRequest) GetCustodialAccountUID() *string {
	if o == nil {
		return nil
	}
	return o.CustodialAccountUID
}

func (o *GetCustodialLineItemsRequest) GetStatus() *GetCustodialLineItemsQueryParamStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *GetCustodialLineItemsRequest) GetUsDollarAmountMax() *float64 {
	if o == nil {
		return nil
	}
	return o.UsDollarAmountMax
}

func (o *GetCustodialLineItemsRequest) GetUsDollarAmountMin() *float64 {
	if o == nil {
		return nil
	}
	return o.UsDollarAmountMin
}

func (o *GetCustodialLineItemsRequest) GetTransactionEventUID() *string {
	if o == nil {
		return nil
	}
	return o.TransactionEventUID
}

func (o *GetCustodialLineItemsRequest) GetTransactionUID() *string {
	if o == nil {
		return nil
	}
	return o.TransactionUID
}

func (o *GetCustodialLineItemsRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *GetCustodialLineItemsRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

func (o *GetCustodialLineItemsRequest) GetSort() *GetCustodialLineItemsSort {
	if o == nil {
		return nil
	}
	return o.Sort
}

// GetCustodialLineItemsDataStatus - Other statuses such as `pending` will be available later
type GetCustodialLineItemsDataStatus string

const (
	GetCustodialLineItemsDataStatusSettled GetCustodialLineItemsDataStatus = "settled"
	GetCustodialLineItemsDataStatusVoided  GetCustodialLineItemsDataStatus = "voided"
)

func (e GetCustodialLineItemsDataStatus) ToPointer() *GetCustodialLineItemsDataStatus {
	return &e
}
func (e *GetCustodialLineItemsDataStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "settled":
		fallthrough
	case "voided":
		*e = GetCustodialLineItemsDataStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetCustodialLineItemsDataStatus: %v", v)
	}
}

type GetCustodialLineItemsData struct {
	// Newline-generated unique id resource specific to the current endpoint
	UID *string `json:"uid,omitempty"`
	// A unique index that indicates the order in which the Custodial Line Items were settled
	//
	SettledIndex *int64 `json:"settled_index,omitempty"`
	// UID of the Transaction this Custodial Line Item belongs to
	TransactionUID *string `json:"transaction_uid,omitempty"`
	// UID of the Transaction Event this Custodial Line Item belongs to
	TransactionEventUID *string `json:"transaction_event_uid,omitempty"`
	// UID of the Custodial Account this Custodial Line Item is associated with
	CustodialAccountUID *string `json:"custodial_account_uid,omitempty"`
	// If this Custodial Line Item represents a Debit Card purchase or refund, the UID of the Debit Card used for the purchase/refund. Otherwise not provided.
	//
	DebitCardUID *string `json:"debit_card_uid,omitempty"`
	// Other statuses such as `pending` will be available later
	Status *GetCustodialLineItemsDataStatus `json:"status,omitempty"`
	// The signed USD amount of this specific Custodial Line Item
	UsDollarAmount *string `json:"us_dollar_amount,omitempty"`
	// The running balance after settlement for this specific Asset Type held within the Custodial Account, expressed in US Dollars calculated using the asset price used for settlement. This field may be empty unless the status is `settled` or `voided`.
	//
	RunningUsDollarBalance optionalnullable.OptionalNullable[string] `json:"running_us_dollar_balance,omitempty"`
	// The running balance after settlement for this specific Asset Type held within the Custodial Account, expressed in units of the given asset type. This field may be empty unless the status is `settled` or `voided`.
	//
	RunningAssetBalance optionalnullable.OptionalNullable[string] `json:"running_asset_balance,omitempty"`
	// The quantity of the specific asset type for this Custodial Line Item
	AssetQuantity *string `json:"asset_quantity,omitempty"`
	// The type of asset for this Custodial Line Item
	AssetType *string `json:"asset_type,omitempty"`
	// If this Custodial Line Item involves a security purchase/sale the USD value at the time of the purchase/sale
	//
	ClosingPrice *string `json:"closing_price,omitempty"`
	// Symbols and/or numbers that represent different types of Custodial Line Items.
	//
	Type *string `json:"type,omitempty"`
	// Descriptions pulled from the custodians, such as through NACHA description or ISO-8583 data element 43
	//
	Description *string `json:"description,omitempty"`
	// The date and time when the Custodial Line Items is first recognized by Newline. This may be when the Transfer is initiated if the Custodial Line Item is associated with one.
	//
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// This field may be empty if status is not `settled` or `voided`
	OccurredAt *time.Time `json:"occurred_at,omitempty"`
	// The date and time when the Custodial Line Item is settled
	SettledAt *time.Time `json:"settled_at,omitempty"`
}

func (g GetCustodialLineItemsData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCustodialLineItemsData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *GetCustodialLineItemsData) GetUID() *string {
	if o == nil {
		return nil
	}
	return o.UID
}

func (o *GetCustodialLineItemsData) GetSettledIndex() *int64 {
	if o == nil {
		return nil
	}
	return o.SettledIndex
}

func (o *GetCustodialLineItemsData) GetTransactionUID() *string {
	if o == nil {
		return nil
	}
	return o.TransactionUID
}

func (o *GetCustodialLineItemsData) GetTransactionEventUID() *string {
	if o == nil {
		return nil
	}
	return o.TransactionEventUID
}

func (o *GetCustodialLineItemsData) GetCustodialAccountUID() *string {
	if o == nil {
		return nil
	}
	return o.CustodialAccountUID
}

func (o *GetCustodialLineItemsData) GetDebitCardUID() *string {
	if o == nil {
		return nil
	}
	return o.DebitCardUID
}

func (o *GetCustodialLineItemsData) GetStatus() *GetCustodialLineItemsDataStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *GetCustodialLineItemsData) GetUsDollarAmount() *string {
	if o == nil {
		return nil
	}
	return o.UsDollarAmount
}

func (o *GetCustodialLineItemsData) GetRunningUsDollarBalance() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.RunningUsDollarBalance
}

func (o *GetCustodialLineItemsData) GetRunningAssetBalance() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.RunningAssetBalance
}

func (o *GetCustodialLineItemsData) GetAssetQuantity() *string {
	if o == nil {
		return nil
	}
	return o.AssetQuantity
}

func (o *GetCustodialLineItemsData) GetAssetType() *string {
	if o == nil {
		return nil
	}
	return o.AssetType
}

func (o *GetCustodialLineItemsData) GetClosingPrice() *string {
	if o == nil {
		return nil
	}
	return o.ClosingPrice
}

func (o *GetCustodialLineItemsData) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *GetCustodialLineItemsData) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *GetCustodialLineItemsData) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *GetCustodialLineItemsData) GetOccurredAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.OccurredAt
}

func (o *GetCustodialLineItemsData) GetSettledAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.SettledAt
}

// GetCustodialLineItemsResponseBody - A list of Custodial Line Items is returned
type GetCustodialLineItemsResponseBody struct {
	// Total count of items available to retrieve
	TotalCount *int64 `json:"total_count,omitempty"`
	// Number of items retrieved
	Count *int64 `json:"count,omitempty"`
	// Maximum number of items to retrieve
	Limit *int64 `json:"limit,omitempty"`
	// Index of the first item to retrieve
	Offset *int64                      `json:"offset,omitempty"`
	Data   []GetCustodialLineItemsData `json:"data,omitempty"`
}

func (o *GetCustodialLineItemsResponseBody) GetTotalCount() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalCount
}

func (o *GetCustodialLineItemsResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetCustodialLineItemsResponseBody) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *GetCustodialLineItemsResponseBody) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

func (o *GetCustodialLineItemsResponseBody) GetData() []GetCustodialLineItemsData {
	if o == nil {
		return nil
	}
	return o.Data
}

type GetCustodialLineItemsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A list of Custodial Line Items is returned
	Object  *GetCustodialLineItemsResponseBody
	Headers map[string][]string
}

func (o *GetCustodialLineItemsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetCustodialLineItemsResponse) GetObject() *GetCustodialLineItemsResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *GetCustodialLineItemsResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
