// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/optionalnullable"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"time"
)

type GetCustomerRequest struct {
	// Newline-generated unique id resource specific to the current endpoint
	UID string `pathParam:"style=simple,explode=false,name=uid"`
}

func (o *GetCustomerRequest) GetUID() string {
	if o == nil {
		return ""
	}
	return o.UID
}

// GetCustomerCustomerType - The type of Customer
type GetCustomerCustomerType string

const (
	GetCustomerCustomerTypePrimary        GetCustomerCustomerType = "primary"
	GetCustomerCustomerTypeSecondary      GetCustomerCustomerType = "secondary"
	GetCustomerCustomerTypeSoleProprietor GetCustomerCustomerType = "sole_proprietor"
	GetCustomerCustomerTypeSubLedger      GetCustomerCustomerType = "sub_ledger"
)

func (e GetCustomerCustomerType) ToPointer() *GetCustomerCustomerType {
	return &e
}
func (e *GetCustomerCustomerType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "primary":
		fallthrough
	case "secondary":
		fallthrough
	case "sole_proprietor":
		fallthrough
	case "sub_ledger":
		*e = GetCustomerCustomerType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetCustomerCustomerType: %v", v)
	}
}

// GetCustomerKycStatus - A value indicating the state of KYC/AML evaluation.
type GetCustomerKycStatus string

const (
	GetCustomerKycStatusManualReview             GetCustomerKycStatus = "manual_review"
	GetCustomerKycStatusApproved                 GetCustomerKycStatus = "approved"
	GetCustomerKycStatusDenied                   GetCustomerKycStatus = "denied"
	GetCustomerKycStatusPendingIDDocuments       GetCustomerKycStatus = "pending_id_documents"
	GetCustomerKycStatusPendingPoaDocuments      GetCustomerKycStatus = "pending_poa_documents"
	GetCustomerKycStatusPendingIdandpoaDocuments GetCustomerKycStatus = "pending_idandpoa_documents"
	GetCustomerKycStatusDocumentsProvided        GetCustomerKycStatus = "documents_provided"
	GetCustomerKycStatusDocumentsRejected        GetCustomerKycStatus = "documents_rejected"
	GetCustomerKycStatusRetakeImages             GetCustomerKycStatus = "retake_images"
	GetCustomerKycStatusPreVerified              GetCustomerKycStatus = "pre_verified"
)

func (e GetCustomerKycStatus) ToPointer() *GetCustomerKycStatus {
	return &e
}
func (e *GetCustomerKycStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "manual_review":
		fallthrough
	case "approved":
		fallthrough
	case "denied":
		fallthrough
	case "pending_id_documents":
		fallthrough
	case "pending_poa_documents":
		fallthrough
	case "pending_idandpoa_documents":
		fallthrough
	case "documents_provided":
		fallthrough
	case "documents_rejected":
		fallthrough
	case "retake_images":
		fallthrough
	case "pre_verified":
		*e = GetCustomerKycStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetCustomerKycStatus: %v", v)
	}
}

type GetCustomerKycStatusReason string

const (
	GetCustomerKycStatusReasonApproved                                     GetCustomerKycStatusReason = "Approved"
	GetCustomerKycStatusReasonValidDocumentsProvided                       GetCustomerKycStatusReason = "Valid Documents Provided"
	GetCustomerKycStatusReasonArchivedDueToApplicationInactivity           GetCustomerKycStatusReason = "Archived due to application inactivity"
	GetCustomerKycStatusReasonFurtherReviewRequired                        GetCustomerKycStatusReason = "Further review required"
	GetCustomerKycStatusReasonMinorAgeLessThan18Years                      GetCustomerKycStatusReason = "Minor (age < 18 years)"
	GetCustomerKycStatusReasonInvalidDocumentsSubmittedMultipleTimes       GetCustomerKycStatusReason = "Invalid Documents submitted multiple times"
	GetCustomerKycStatusReasonMinimumRequirementsToOpenAnAccountWereNotMet GetCustomerKycStatusReason = "Minimum requirements to open an account were not met"
	GetCustomerKycStatusReasonInvalidDocuments                             GetCustomerKycStatusReason = "Invalid documents"
	GetCustomerKycStatusReasonIncorrectDocumentProvidedForIDDocument       GetCustomerKycStatusReason = "Incorrect document provided for ID document"
	GetCustomerKycStatusReasonExpiredID                                    GetCustomerKycStatusReason = "Expired ID"
	GetCustomerKycStatusReasonIllegibleIDDocument                          GetCustomerKycStatusReason = "Illegible ID document"
	GetCustomerKycStatusReasonIncorrectDocumentProvidedForPoaDocument      GetCustomerKycStatusReason = "Incorrect document provided for POA document"
	GetCustomerKycStatusReasonInvalidPoaProvided                           GetCustomerKycStatusReason = "Invalid POA provided"
	GetCustomerKycStatusReasonIllegiblePoaDocument                         GetCustomerKycStatusReason = "Illegible POA document"
)

func (e GetCustomerKycStatusReason) ToPointer() *GetCustomerKycStatusReason {
	return &e
}
func (e *GetCustomerKycStatusReason) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Approved":
		fallthrough
	case "Valid Documents Provided":
		fallthrough
	case "Archived due to application inactivity":
		fallthrough
	case "Further review required":
		fallthrough
	case "Minor (age < 18 years)":
		fallthrough
	case "Invalid Documents submitted multiple times":
		fallthrough
	case "Minimum requirements to open an account were not met":
		fallthrough
	case "Invalid documents":
		fallthrough
	case "Incorrect document provided for ID document":
		fallthrough
	case "Expired ID":
		fallthrough
	case "Illegible ID document":
		fallthrough
	case "Incorrect document provided for POA document":
		fallthrough
	case "Invalid POA provided":
		fallthrough
	case "Illegible POA document":
		*e = GetCustomerKycStatusReason(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetCustomerKycStatusReason: %v", v)
	}
}

type GetCustomerProfileResponse struct {
	// A statement that requires a response in order to onboard a Customer for a Product
	ProfileRequirement *string `json:"profile_requirement,omitempty"`
	// The Customer's response to the Profile Requirement as a single string value.
	ProfileResponse *string `json:"profile_response,omitempty"`
	// A UID referring to the Profile Requirement
	ProfileRequirementUID *string `json:"profile_requirement_uid,omitempty"`
}

func (o *GetCustomerProfileResponse) GetProfileRequirement() *string {
	if o == nil {
		return nil
	}
	return o.ProfileRequirement
}

func (o *GetCustomerProfileResponse) GetProfileResponse() *string {
	if o == nil {
		return nil
	}
	return o.ProfileResponse
}

func (o *GetCustomerProfileResponse) GetProfileRequirementUID() *string {
	if o == nil {
		return nil
	}
	return o.ProfileRequirementUID
}

// GetCustomerStatus - A value indicating the overall state of this Customer.
type GetCustomerStatus string

const (
	GetCustomerStatusInitiated        GetCustomerStatus = "initiated"
	GetCustomerStatusQueued           GetCustomerStatus = "queued"
	GetCustomerStatusIdentityVerified GetCustomerStatus = "identity_verified"
	GetCustomerStatusActive           GetCustomerStatus = "active"
	GetCustomerStatusManualReview     GetCustomerStatus = "manual_review"
	GetCustomerStatusRejected         GetCustomerStatus = "rejected"
	GetCustomerStatusPendingArchival  GetCustomerStatus = "pending_archival"
	GetCustomerStatusArchived         GetCustomerStatus = "archived"
	GetCustomerStatusUnderReview      GetCustomerStatus = "under_review"
)

func (e GetCustomerStatus) ToPointer() *GetCustomerStatus {
	return &e
}
func (e *GetCustomerStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "initiated":
		fallthrough
	case "queued":
		fallthrough
	case "identity_verified":
		fallthrough
	case "active":
		fallthrough
	case "manual_review":
		fallthrough
	case "rejected":
		fallthrough
	case "pending_archival":
		fallthrough
	case "archived":
		fallthrough
	case "under_review":
		*e = GetCustomerStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetCustomerStatus: %v", v)
	}
}

type GetCustomerAddress struct {
	// Maximum 35 characters
	Street1 *string `json:"street1"`
	// Maximum 35 characters
	Street2 optionalnullable.OptionalNullable[string] `json:"street2,omitempty"`
	// Maximum 35 characters
	City *string `json:"city"`
	// 2 characters. Must be a valid US state abbreviation.
	State *string `json:"state"`
	// 5-digit string. ZIP+4 is allowed.
	PostalCode *string `json:"postal_code"`
}

func (o *GetCustomerAddress) GetStreet1() *string {
	if o == nil {
		return nil
	}
	return o.Street1
}

func (o *GetCustomerAddress) GetStreet2() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Street2
}

func (o *GetCustomerAddress) GetCity() *string {
	if o == nil {
		return nil
	}
	return o.City
}

func (o *GetCustomerAddress) GetState() *string {
	if o == nil {
		return nil
	}
	return o.State
}

func (o *GetCustomerAddress) GetPostalCode() *string {
	if o == nil {
		return nil
	}
	return o.PostalCode
}

// GetCustomerDetails - An object containing the supplied identifying information for the Customer
type GetCustomerDetails struct {
	// 1-40 characters
	FirstName optionalnullable.OptionalNullable[string] `json:"first_name,omitempty"`
	// 1-40 characters
	MiddleName optionalnullable.OptionalNullable[string] `json:"middle_name,omitempty"`
	// 1-40 characters
	LastName optionalnullable.OptionalNullable[string] `json:"last_name,omitempty"`
	// 1-30 characters
	Suffix optionalnullable.OptionalNullable[string] `json:"suffix,omitempty"`
	// Exactly 10 digits long (no hyphens, parentheses, or spaces)
	Phone optionalnullable.OptionalNullable[string] `json:"phone,omitempty"`
	// Required for customers of type `sole_proprietor` and discarded otherwise. 1-256 alphanumeric characters.
	BusinessName optionalnullable.OptionalNullable[string] `json:"business_name,omitempty"`
	SsnLastFour  optionalnullable.OptionalNullable[string] `json:"ssn_last_four,omitempty"`
	// Follows pattern 'YYYY-MM-DD'
	Dob     optionalnullable.OptionalNullable[types.Date] `json:"dob,omitempty"`
	Address *GetCustomerAddress                           `json:"address,omitempty"`
}

func (g GetCustomerDetails) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCustomerDetails) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *GetCustomerDetails) GetFirstName() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.FirstName
}

func (o *GetCustomerDetails) GetMiddleName() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.MiddleName
}

func (o *GetCustomerDetails) GetLastName() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.LastName
}

func (o *GetCustomerDetails) GetSuffix() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Suffix
}

func (o *GetCustomerDetails) GetPhone() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Phone
}

func (o *GetCustomerDetails) GetBusinessName() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.BusinessName
}

func (o *GetCustomerDetails) GetSsnLastFour() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.SsnLastFour
}

func (o *GetCustomerDetails) GetDob() optionalnullable.OptionalNullable[types.Date] {
	if o == nil {
		return nil
	}
	return o.Dob
}

func (o *GetCustomerDetails) GetAddress() *GetCustomerAddress {
	if o == nil {
		return nil
	}
	return o.Address
}

// GetCustomerResponseBody - A single Customer is returned
type GetCustomerResponseBody struct {
	// Newline-generated unique id resource specific to the current endpoint
	UID *string `json:"uid,omitempty"`
	// A unique identifier the Client supplies. It must be unique within the resource type. If the same value is given, no new resource will be created.
	//
	ExternalUID *string `json:"external_uid,omitempty"`
	// The date and time at which this Customer was activated.
	ActivatedAt *time.Time `json:"activated_at,omitempty"`
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	// The type of Customer
	//
	CustomerType *GetCustomerCustomerType `json:"customer_type,omitempty"`
	// Email of the Customer
	Email *string `json:"email,omitempty"`
	// Indicates whether or not the client is responsible for identity verification of this Customer. If true, the `kyc_status` will be "pre_verified".
	ClientVerified *bool `json:"client_verified,omitempty"`
	// A value indicating the state of KYC/AML evaluation.
	//
	KycStatus optionalnullable.OptionalNullable[GetCustomerKycStatus] `json:"kyc_status,omitempty"`
	// A list of reasons for the current `kyc_status`.
	KycStatusReasons optionalnullable.OptionalNullable[[]GetCustomerKycStatusReason] `json:"kyc_status_reasons,omitempty"`
	// The lock reason provided by the Client, an admin User, or the system at the time the Customer was locked. This field will be null if and only if the `locked_at` is null.
	//
	LockReason optionalnullable.OptionalNullable[string] `json:"lock_reason,omitempty"`
	// The date and time when the Customer was locked. This field will be null if and only if the `lock_reason` is null.
	//
	LockedAt optionalnullable.OptionalNullable[time.Time] `json:"locked_at,omitempty"`
	// The date and time when the Customer's PII was last confirmed to be accurate
	//
	PiiConfirmedAt *time.Time `json:"pii_confirmed_at,omitempty"`
	// A list of uids referring to Pools belonging to this Customer.
	PoolUids []string `json:"pool_uids,omitempty"`
	// The UID of the primary Customer. Null unless the customer type is `secondary`.
	PrimaryCustomerUID optionalnullable.OptionalNullable[string] `json:"primary_customer_uid,omitempty"`
	// A list of Profile Responses submitted by the Customer
	ProfileResponses []GetCustomerProfileResponse `json:"profile_responses,omitempty"`
	// A UID referring to the program this customer belongs to
	ProgramUID *string `json:"program_uid,omitempty"`
	// The UIDs of secondary Customers. Null unless the customer type is `primary`.
	SecondaryCustomerUids optionalnullable.OptionalNullable[[]string] `json:"secondary_customer_uids,omitempty"`
	// A value indicating the overall state of this Customer.
	//
	Status *GetCustomerStatus `json:"status,omitempty"`
	// Total asset owned by the customer in US dollars
	TotalBalance *string `json:"total_balance,omitempty"`
	// If the Customer's status is `archived` this will have the time at which they were archived.
	//
	ArchivedAt optionalnullable.OptionalNullable[time.Time] `json:"archived_at,omitempty"`
	Details    *GetCustomerDetails                          `json:"details,omitempty"`
}

func (g GetCustomerResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCustomerResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *GetCustomerResponseBody) GetUID() *string {
	if o == nil {
		return nil
	}
	return o.UID
}

func (o *GetCustomerResponseBody) GetExternalUID() *string {
	if o == nil {
		return nil
	}
	return o.ExternalUID
}

func (o *GetCustomerResponseBody) GetActivatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ActivatedAt
}

func (o *GetCustomerResponseBody) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *GetCustomerResponseBody) GetCustomerType() *GetCustomerCustomerType {
	if o == nil {
		return nil
	}
	return o.CustomerType
}

func (o *GetCustomerResponseBody) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *GetCustomerResponseBody) GetClientVerified() *bool {
	if o == nil {
		return nil
	}
	return o.ClientVerified
}

func (o *GetCustomerResponseBody) GetKycStatus() optionalnullable.OptionalNullable[GetCustomerKycStatus] {
	if o == nil {
		return nil
	}
	return o.KycStatus
}

func (o *GetCustomerResponseBody) GetKycStatusReasons() optionalnullable.OptionalNullable[[]GetCustomerKycStatusReason] {
	if o == nil {
		return nil
	}
	return o.KycStatusReasons
}

func (o *GetCustomerResponseBody) GetLockReason() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.LockReason
}

func (o *GetCustomerResponseBody) GetLockedAt() optionalnullable.OptionalNullable[time.Time] {
	if o == nil {
		return nil
	}
	return o.LockedAt
}

func (o *GetCustomerResponseBody) GetPiiConfirmedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.PiiConfirmedAt
}

func (o *GetCustomerResponseBody) GetPoolUids() []string {
	if o == nil {
		return nil
	}
	return o.PoolUids
}

func (o *GetCustomerResponseBody) GetPrimaryCustomerUID() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.PrimaryCustomerUID
}

func (o *GetCustomerResponseBody) GetProfileResponses() []GetCustomerProfileResponse {
	if o == nil {
		return nil
	}
	return o.ProfileResponses
}

func (o *GetCustomerResponseBody) GetProgramUID() *string {
	if o == nil {
		return nil
	}
	return o.ProgramUID
}

func (o *GetCustomerResponseBody) GetSecondaryCustomerUids() optionalnullable.OptionalNullable[[]string] {
	if o == nil {
		return nil
	}
	return o.SecondaryCustomerUids
}

func (o *GetCustomerResponseBody) GetStatus() *GetCustomerStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *GetCustomerResponseBody) GetTotalBalance() *string {
	if o == nil {
		return nil
	}
	return o.TotalBalance
}

func (o *GetCustomerResponseBody) GetArchivedAt() optionalnullable.OptionalNullable[time.Time] {
	if o == nil {
		return nil
	}
	return o.ArchivedAt
}

func (o *GetCustomerResponseBody) GetDetails() *GetCustomerDetails {
	if o == nil {
		return nil
	}
	return o.Details
}

type GetCustomerResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A single Customer is returned
	Object  *GetCustomerResponseBody
	Headers map[string][]string
}

func (o *GetCustomerResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetCustomerResponse) GetObject() *GetCustomerResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *GetCustomerResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
