// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/models/components"
)

type GetProductRequest struct {
	// Newline-generated unique id resource specific to the current endpoint
	UID string `pathParam:"style=simple,explode=false,name=uid"`
}

func (o *GetProductRequest) GetUID() string {
	if o == nil {
		return ""
	}
	return o.UID
}

// GetProductRequirementType - The type of the response values for the requirement
type GetProductRequirementType string

const (
	GetProductRequirementTypeFixedList      GetProductRequirementType = "fixed_list"
	GetProductRequirementTypeIntegerGreater GetProductRequirementType = "integer_greater"
	GetProductRequirementTypeOrderedList    GetProductRequirementType = "ordered_list"
	GetProductRequirementTypeNumber         GetProductRequirementType = "number"
	GetProductRequirementTypeString         GetProductRequirementType = "string"
)

func (e GetProductRequirementType) ToPointer() *GetProductRequirementType {
	return &e
}
func (e *GetProductRequirementType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "fixed_list":
		fallthrough
	case "integer_greater":
		fallthrough
	case "ordered_list":
		fallthrough
	case "number":
		fallthrough
	case "string":
		*e = GetProductRequirementType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetProductRequirementType: %v", v)
	}
}

type GetProductProfileRequirement struct {
	// A UID referring to the Profile Requirement
	ProfileRequirementUID *string `json:"profile_requirement_uid,omitempty"`
	// A statement that requires response in order to onboard a Customer for a Product
	ProfileRequirement *string `json:"profile_requirement,omitempty"`
	// an identifier by which requirements can be grouped
	Category *string `json:"category,omitempty"`
	// an indication of whether a response is required or optional
	Required *bool `json:"required,omitempty"`
	// The type of the response values for the requirement
	RequirementType *GetProductRequirementType `json:"requirement_type,omitempty"`
	// List of valid response values, if applicable
	ResponseValues []string `json:"response_values,omitempty"`
}

func (o *GetProductProfileRequirement) GetProfileRequirementUID() *string {
	if o == nil {
		return nil
	}
	return o.ProfileRequirementUID
}

func (o *GetProductProfileRequirement) GetProfileRequirement() *string {
	if o == nil {
		return nil
	}
	return o.ProfileRequirement
}

func (o *GetProductProfileRequirement) GetCategory() *string {
	if o == nil {
		return nil
	}
	return o.Category
}

func (o *GetProductProfileRequirement) GetRequired() *bool {
	if o == nil {
		return nil
	}
	return o.Required
}

func (o *GetProductProfileRequirement) GetRequirementType() *GetProductRequirementType {
	if o == nil {
		return nil
	}
	return o.RequirementType
}

func (o *GetProductProfileRequirement) GetResponseValues() []string {
	if o == nil {
		return nil
	}
	return o.ResponseValues
}

type GetProductRequiredField struct {
	CustomerType *string  `json:"customer_type,omitempty"`
	Fields       []string `json:"fields,omitempty"`
}

func (o *GetProductRequiredField) GetCustomerType() *string {
	if o == nil {
		return nil
	}
	return o.CustomerType
}

func (o *GetProductRequiredField) GetFields() []string {
	if o == nil {
		return nil
	}
	return o.Fields
}

// GetProductResponseBody - A single Product is returned
type GetProductResponseBody struct {
	// A unique identifier for this resource
	UID         *string `json:"uid,omitempty"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	// A unique identifier for a Product Compliance Plan
	ProductCompliancePlanUID *string `json:"product_compliance_plan_uid,omitempty"`
	CompliancePlanName       *string `json:"compliance_plan_name,omitempty"`
	// A list of customer types allowed for this Product
	CustomerTypes []string `json:"customer_types,omitempty"`
	// A list of uids referring to Products that a Customer must onboard to before this Product is available
	PrerequisiteProductUids []string `json:"prerequisite_product_uids,omitempty"`
	// A list of Profile Requirements a Customer must provide Profile Responses to
	ProfileRequirements []GetProductProfileRequirement `json:"profile_requirements,omitempty"`
	// A unique identifier for a Program
	ProgramUID *string `json:"program_uid,omitempty"`
	// List of required PII fields per Customer type
	RequiredFields []GetProductRequiredField `json:"required_fields,omitempty"`
}

func (o *GetProductResponseBody) GetUID() *string {
	if o == nil {
		return nil
	}
	return o.UID
}

func (o *GetProductResponseBody) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *GetProductResponseBody) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *GetProductResponseBody) GetProductCompliancePlanUID() *string {
	if o == nil {
		return nil
	}
	return o.ProductCompliancePlanUID
}

func (o *GetProductResponseBody) GetCompliancePlanName() *string {
	if o == nil {
		return nil
	}
	return o.CompliancePlanName
}

func (o *GetProductResponseBody) GetCustomerTypes() []string {
	if o == nil {
		return nil
	}
	return o.CustomerTypes
}

func (o *GetProductResponseBody) GetPrerequisiteProductUids() []string {
	if o == nil {
		return nil
	}
	return o.PrerequisiteProductUids
}

func (o *GetProductResponseBody) GetProfileRequirements() []GetProductProfileRequirement {
	if o == nil {
		return nil
	}
	return o.ProfileRequirements
}

func (o *GetProductResponseBody) GetProgramUID() *string {
	if o == nil {
		return nil
	}
	return o.ProgramUID
}

func (o *GetProductResponseBody) GetRequiredFields() []GetProductRequiredField {
	if o == nil {
		return nil
	}
	return o.RequiredFields
}

type GetProductResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A single Product is returned
	Object  *GetProductResponseBody
	Headers map[string][]string
}

func (o *GetProductResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetProductResponse) GetObject() *GetProductResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *GetProductResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
