// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
	"time"
)

// GetTransactionEventsQueryParamType - Filter by type. Multiple values are allowed, e.g. `type[]=odfi_ach_deposit&type[]=odfi_ach_withdrawal`.
type GetTransactionEventsQueryParamType string

const (
	GetTransactionEventsQueryParamTypeOdfiAchDeposit    GetTransactionEventsQueryParamType = "odfi_ach_deposit"
	GetTransactionEventsQueryParamTypeOdfiAchWithdrawal GetTransactionEventsQueryParamType = "odfi_ach_withdrawal"
	GetTransactionEventsQueryParamTypeRdfiAchDeposit    GetTransactionEventsQueryParamType = "rdfi_ach_deposit"
	GetTransactionEventsQueryParamTypeRdfiAchWithdrawal GetTransactionEventsQueryParamType = "rdfi_ach_withdrawal"
)

func (e GetTransactionEventsQueryParamType) ToPointer() *GetTransactionEventsQueryParamType {
	return &e
}
func (e *GetTransactionEventsQueryParamType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "odfi_ach_deposit":
		fallthrough
	case "odfi_ach_withdrawal":
		fallthrough
	case "rdfi_ach_deposit":
		fallthrough
	case "rdfi_ach_withdrawal":
		*e = GetTransactionEventsQueryParamType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetTransactionEventsQueryParamType: %v", v)
	}
}

type GetTransactionEventsSort string

const (
	GetTransactionEventsSortCreatedAtAsc       GetTransactionEventsSort = "created_at_asc"
	GetTransactionEventsSortCreatedAtDesc      GetTransactionEventsSort = "created_at_desc"
	GetTransactionEventsSortDescriptionAsc     GetTransactionEventsSort = "description_asc"
	GetTransactionEventsSortDescriptionDesc    GetTransactionEventsSort = "description_desc"
	GetTransactionEventsSortSettledIndexAsc    GetTransactionEventsSort = "settled_index_asc"
	GetTransactionEventsSortSettledIndexDesc   GetTransactionEventsSort = "settled_index_desc"
	GetTransactionEventsSortUsDollarAmountAsc  GetTransactionEventsSort = "us_dollar_amount_asc"
	GetTransactionEventsSortUsDollarAmountDesc GetTransactionEventsSort = "us_dollar_amount_desc"
)

func (e GetTransactionEventsSort) ToPointer() *GetTransactionEventsSort {
	return &e
}
func (e *GetTransactionEventsSort) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at_asc":
		fallthrough
	case "created_at_desc":
		fallthrough
	case "description_asc":
		fallthrough
	case "description_desc":
		fallthrough
	case "settled_index_asc":
		fallthrough
	case "settled_index_desc":
		fallthrough
	case "us_dollar_amount_asc":
		fallthrough
	case "us_dollar_amount_desc":
		*e = GetTransactionEventsSort(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetTransactionEventsSort: %v", v)
	}
}

type GetTransactionEventsRequest struct {
	SourceCustodialAccountUID      *string `queryParam:"style=form,explode=true,name=source_custodial_account_uid"`
	DestinationCustodialAccountUID *string `queryParam:"style=form,explode=true,name=destination_custodial_account_uid"`
	CustodialAccountUID            *string `queryParam:"style=form,explode=true,name=custodial_account_uid"`
	// Filter by type. Multiple values are allowed, e.g. `type[]=odfi_ach_deposit&type[]=odfi_ach_withdrawal`.
	//
	Type *GetTransactionEventsQueryParamType `queryParam:"style=form,explode=true,name=type"`
	// Filter by Transaction. Multiple values are allowed, e.g. `transaction_uid[]=SMwKC1osz77DTEiu&transaction_uid[]=f1UDvUVNnXTKtgxu`.
	//
	TransactionUID *string `queryParam:"style=form,explode=true,name=transaction_uid"`
	// Maximum number of items to retrieve. This filter is automatically applied with the default value if not given.
	//
	Limit *int64 `default:"100" queryParam:"style=form,explode=true,name=limit"`
	// Index of the items to start retrieving from
	Offset *int64                    `default:"0" queryParam:"style=form,explode=true,name=offset"`
	Sort   *GetTransactionEventsSort `queryParam:"style=form,explode=true,name=sort"`
}

func (g GetTransactionEventsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetTransactionEventsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *GetTransactionEventsRequest) GetSourceCustodialAccountUID() *string {
	if o == nil {
		return nil
	}
	return o.SourceCustodialAccountUID
}

func (o *GetTransactionEventsRequest) GetDestinationCustodialAccountUID() *string {
	if o == nil {
		return nil
	}
	return o.DestinationCustodialAccountUID
}

func (o *GetTransactionEventsRequest) GetCustodialAccountUID() *string {
	if o == nil {
		return nil
	}
	return o.CustodialAccountUID
}

func (o *GetTransactionEventsRequest) GetType() *GetTransactionEventsQueryParamType {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *GetTransactionEventsRequest) GetTransactionUID() *string {
	if o == nil {
		return nil
	}
	return o.TransactionUID
}

func (o *GetTransactionEventsRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *GetTransactionEventsRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

func (o *GetTransactionEventsRequest) GetSort() *GetTransactionEventsSort {
	if o == nil {
		return nil
	}
	return o.Sort
}

// GetTransactionEventsStatus - Transaction Events will always have a status of `settled`
type GetTransactionEventsStatus string

const (
	GetTransactionEventsStatusSettled GetTransactionEventsStatus = "settled"
)

func (e GetTransactionEventsStatus) ToPointer() *GetTransactionEventsStatus {
	return &e
}
func (e *GetTransactionEventsStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "settled":
		*e = GetTransactionEventsStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetTransactionEventsStatus: %v", v)
	}
}

type GetTransactionEventsTypeSettled string

const (
	GetTransactionEventsTypeSettledOdfiAchDeposit    GetTransactionEventsTypeSettled = "odfi_ach_deposit"
	GetTransactionEventsTypeSettledOdfiAchWithdrawal GetTransactionEventsTypeSettled = "odfi_ach_withdrawal"
	GetTransactionEventsTypeSettledRdfiAchDeposit    GetTransactionEventsTypeSettled = "rdfi_ach_deposit"
	GetTransactionEventsTypeSettledRdfiAchWithdrawal GetTransactionEventsTypeSettled = "rdfi_ach_withdrawal"
)

func (e GetTransactionEventsTypeSettled) ToPointer() *GetTransactionEventsTypeSettled {
	return &e
}
func (e *GetTransactionEventsTypeSettled) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "odfi_ach_deposit":
		fallthrough
	case "odfi_ach_withdrawal":
		fallthrough
	case "rdfi_ach_deposit":
		fallthrough
	case "rdfi_ach_withdrawal":
		*e = GetTransactionEventsTypeSettled(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetTransactionEventsTypeSettled: %v", v)
	}
}

// GetTransactionEventsNetAsset - Indicates whether the Customer's asset has gone up (`positive`), gone down (`negative`) or stayed the same (`neutral`) as a result of this Transaction Event. This value is determined by `type`.
type GetTransactionEventsNetAsset string

const (
	GetTransactionEventsNetAssetPositive GetTransactionEventsNetAsset = "positive"
	GetTransactionEventsNetAssetNegative GetTransactionEventsNetAsset = "negative"
	GetTransactionEventsNetAssetNeutral  GetTransactionEventsNetAsset = "neutral"
)

func (e GetTransactionEventsNetAsset) ToPointer() *GetTransactionEventsNetAsset {
	return &e
}
func (e *GetTransactionEventsNetAsset) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "positive":
		fallthrough
	case "negative":
		fallthrough
	case "neutral":
		*e = GetTransactionEventsNetAsset(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetTransactionEventsNetAsset: %v", v)
	}
}

type GetTransactionEventsData struct {
	// Newline-generated unique id resource specific to the current endpoint
	UID *string `json:"uid,omitempty"`
	// A unique index that indicates the order in which Transaction Events were settled
	//
	SettledIndex *int64 `json:"settled_index,omitempty"`
	// A list of UIDS referring to Transactions this Transaction Event belongs to.
	//
	TransactionUids []string `json:"transaction_uids,omitempty"`
	// Custodial Account from which the asset is pulled
	SourceCustodialAccountUID *string `json:"source_custodial_account_uid,omitempty"`
	// Custodial Account where the asset lands
	DestinationCustodialAccountUID *string `json:"destination_custodial_account_uid,omitempty"`
	// A list of UIDS referring to Custodial Line Items belonging to this event. There are always at least two line items if the status is `settled`.
	//
	CustodialLineItemUids []string `json:"custodial_line_item_uids,omitempty"`
	// Transaction Events will always have a status of `settled`
	Status *GetTransactionEventsStatus `json:"status,omitempty"`
	// The amount will never be negative
	UsDollarAmount *string                          `json:"us_dollar_amount,omitempty"`
	Type           *GetTransactionEventsTypeSettled `json:"type,omitempty"`
	// If this Transaction Event represents a Debit Card purchase or refund, the UID of the Debit Card used for the purchase/refund. Otherwise not provided.
	//
	DebitCardUID *string `json:"debit_card_uid,omitempty"`
	// Indicates whether the Customer's asset has gone up (`positive`), gone down (`negative`) or stayed the same (`neutral`) as a result of this Transaction Event. This value is determined by `type`.
	//
	NetAsset    *GetTransactionEventsNetAsset `json:"net_asset,omitempty"`
	Description *string                       `json:"description,omitempty"`
	// The date and time when the event is first recognized by Newline. This may be when the Transfer is initiated if the event is associated with one.
	//
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// The date and time when the event is settled
	SettledAt *time.Time `json:"settled_at,omitempty"`
}

func (g GetTransactionEventsData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetTransactionEventsData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *GetTransactionEventsData) GetUID() *string {
	if o == nil {
		return nil
	}
	return o.UID
}

func (o *GetTransactionEventsData) GetSettledIndex() *int64 {
	if o == nil {
		return nil
	}
	return o.SettledIndex
}

func (o *GetTransactionEventsData) GetTransactionUids() []string {
	if o == nil {
		return nil
	}
	return o.TransactionUids
}

func (o *GetTransactionEventsData) GetSourceCustodialAccountUID() *string {
	if o == nil {
		return nil
	}
	return o.SourceCustodialAccountUID
}

func (o *GetTransactionEventsData) GetDestinationCustodialAccountUID() *string {
	if o == nil {
		return nil
	}
	return o.DestinationCustodialAccountUID
}

func (o *GetTransactionEventsData) GetCustodialLineItemUids() []string {
	if o == nil {
		return nil
	}
	return o.CustodialLineItemUids
}

func (o *GetTransactionEventsData) GetStatus() *GetTransactionEventsStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *GetTransactionEventsData) GetUsDollarAmount() *string {
	if o == nil {
		return nil
	}
	return o.UsDollarAmount
}

func (o *GetTransactionEventsData) GetType() *GetTransactionEventsTypeSettled {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *GetTransactionEventsData) GetDebitCardUID() *string {
	if o == nil {
		return nil
	}
	return o.DebitCardUID
}

func (o *GetTransactionEventsData) GetNetAsset() *GetTransactionEventsNetAsset {
	if o == nil {
		return nil
	}
	return o.NetAsset
}

func (o *GetTransactionEventsData) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *GetTransactionEventsData) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *GetTransactionEventsData) GetSettledAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.SettledAt
}

// GetTransactionEventsResponseBody - A list of Transaction Events is returned
type GetTransactionEventsResponseBody struct {
	// Total count of items available to retrieve
	TotalCount *int64 `json:"total_count,omitempty"`
	// Number of items retrieved
	Count *int64 `json:"count,omitempty"`
	// Maximum number of items to retrieve
	Limit *int64 `json:"limit,omitempty"`
	// Index of the first item to retrieve
	Offset *int64                     `json:"offset,omitempty"`
	Data   []GetTransactionEventsData `json:"data,omitempty"`
}

func (o *GetTransactionEventsResponseBody) GetTotalCount() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalCount
}

func (o *GetTransactionEventsResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetTransactionEventsResponseBody) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *GetTransactionEventsResponseBody) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

func (o *GetTransactionEventsResponseBody) GetData() []GetTransactionEventsData {
	if o == nil {
		return nil
	}
	return o.Data
}

type GetTransactionEventsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A list of Transaction Events is returned
	Object  *GetTransactionEventsResponseBody
	Headers map[string][]string
}

func (o *GetTransactionEventsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetTransactionEventsResponse) GetObject() *GetTransactionEventsResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *GetTransactionEventsResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
