// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/optionalnullable"
)

// PostCombinedTransfersAccountType - The type of ACH account
type PostCombinedTransfersAccountType string

const (
	PostCombinedTransfersAccountTypeChecking PostCombinedTransfersAccountType = "checking"
	PostCombinedTransfersAccountTypeSavings  PostCombinedTransfersAccountType = "savings"
)

func (e PostCombinedTransfersAccountType) ToPointer() *PostCombinedTransfersAccountType {
	return &e
}
func (e *PostCombinedTransfersAccountType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "checking":
		fallthrough
	case "savings":
		*e = PostCombinedTransfersAccountType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostCombinedTransfersAccountType: %v", v)
	}
}

// SyntheticAccountAch - Contains ACH-specific information. Only populated if the Synthetic Account is in the `ach_external` category.
type SyntheticAccountAch struct {
	// The type of ACH account
	AccountType PostCombinedTransfersAccountType `json:"account_type"`
	// Name of the business or individual who owns the external account. Conditional maximum character length: for all newline supported SEC codes other than CIE, the counterparty_name can be 22 characters. For CIE SEC codes, the counterparty_name can be up to 15 characters.
	//
	CounterpartyName string `json:"counterparty_name"`
}

func (o *SyntheticAccountAch) GetAccountType() PostCombinedTransfersAccountType {
	if o == nil {
		return PostCombinedTransfersAccountType("")
	}
	return o.AccountType
}

func (o *SyntheticAccountAch) GetCounterpartyName() string {
	if o == nil {
		return ""
	}
	return o.CounterpartyName
}

type PostCombinedTransfersInstantPaymentCounterpartyAddress struct {
	// Building number for counterparty address. Alphanumeric only.
	StreetNumber string `json:"street_number"`
	// Street name for counterparty address
	Street1 string `json:"street1"`
	// Optional second line of street
	Street2 *string `json:"street2,omitempty"`
	// Maximum 35 characters
	City *string `json:"city"`
	// 2 characters. Must be a valid US state abbreviation.
	State *string `json:"state"`
	// 5-digit string. ZIP+4 is allowed.
	PostalCode *string `json:"postal_code"`
	Country    *string `json:"country"`
}

func (o *PostCombinedTransfersInstantPaymentCounterpartyAddress) GetStreetNumber() string {
	if o == nil {
		return ""
	}
	return o.StreetNumber
}

func (o *PostCombinedTransfersInstantPaymentCounterpartyAddress) GetStreet1() string {
	if o == nil {
		return ""
	}
	return o.Street1
}

func (o *PostCombinedTransfersInstantPaymentCounterpartyAddress) GetStreet2() *string {
	if o == nil {
		return nil
	}
	return o.Street2
}

func (o *PostCombinedTransfersInstantPaymentCounterpartyAddress) GetCity() *string {
	if o == nil {
		return nil
	}
	return o.City
}

func (o *PostCombinedTransfersInstantPaymentCounterpartyAddress) GetState() *string {
	if o == nil {
		return nil
	}
	return o.State
}

func (o *PostCombinedTransfersInstantPaymentCounterpartyAddress) GetPostalCode() *string {
	if o == nil {
		return nil
	}
	return o.PostalCode
}

func (o *PostCombinedTransfersInstantPaymentCounterpartyAddress) GetCountry() *string {
	if o == nil {
		return nil
	}
	return o.Country
}

// SyntheticAccountInstantPayment - Contains Instant Payment-specific information. Only populated if the Synthetic Account is in the `instant_payments_external` category.
type SyntheticAccountInstantPayment struct {
	// Address of the business or individual who owns the external account.
	//
	CounterpartyAddress PostCombinedTransfersInstantPaymentCounterpartyAddress `json:"counterparty_address"`
	// Name of the business or individual who owns the counterparty Account.
	//
	CounterpartyName string `json:"counterparty_name"`
	// Email address of the counterparty
	Email optionalnullable.OptionalNullable[string] `json:"email,omitempty"`
	// Exactly 10 digits long (no hyphens, parentheses, or spaces)
	Phone optionalnullable.OptionalNullable[string] `json:"phone,omitempty"`
}

func (o *SyntheticAccountInstantPayment) GetCounterpartyAddress() PostCombinedTransfersInstantPaymentCounterpartyAddress {
	if o == nil {
		return PostCombinedTransfersInstantPaymentCounterpartyAddress{}
	}
	return o.CounterpartyAddress
}

func (o *SyntheticAccountInstantPayment) GetCounterpartyName() string {
	if o == nil {
		return ""
	}
	return o.CounterpartyName
}

func (o *SyntheticAccountInstantPayment) GetEmail() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *SyntheticAccountInstantPayment) GetPhone() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Phone
}

// PostCombinedTransfersWireCounterpartyAddress - Address of the business or individual who owns the external account.
type PostCombinedTransfersWireCounterpartyAddress struct {
	// Optional 35 characters. Cannot contain \# @ $ ! " % & * ; < > { } [ ] _ ^ \ ~
	//
	Line1 optionalnullable.OptionalNullable[string] `json:"line1,omitempty"`
	// Optional 35 characters. Cannot contain \# @ $ ! " % & * ; < > { } [ ] _ ^ \ ~
	//
	Line2 optionalnullable.OptionalNullable[string] `json:"line2,omitempty"`
	// Optional 32 characters. Note that this length is shorter than the other lines. Cannot contain \# @ $ ! " % & * ; < > { } [ ] _ ^ \ ~
	//
	Line3   optionalnullable.OptionalNullable[string] `json:"line3,omitempty"`
	Country optionalnullable.OptionalNullable[string] `json:"country,omitempty"`
}

func (o *PostCombinedTransfersWireCounterpartyAddress) GetLine1() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Line1
}

func (o *PostCombinedTransfersWireCounterpartyAddress) GetLine2() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Line2
}

func (o *PostCombinedTransfersWireCounterpartyAddress) GetLine3() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Line3
}

func (o *PostCombinedTransfersWireCounterpartyAddress) GetCountry() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Country
}

// PostCombinedTransfersCounterpartyBankAddress - Address of the financial institution where the external account is held.
type PostCombinedTransfersCounterpartyBankAddress struct {
	// Optional 35 characters. Cannot contain \# @ $ ! " % & * ; < > { } [ ] _ ^ \ ~
	//
	Line1 optionalnullable.OptionalNullable[string] `json:"line1,omitempty"`
	// Optional 35 characters. Cannot contain \# @ $ ! " % & * ; < > { } [ ] _ ^ \ ~
	//
	Line2 optionalnullable.OptionalNullable[string] `json:"line2,omitempty"`
	// Optional 32 characters. Note that this length is shorter than the other lines. Cannot contain \# @ $ ! " % & * ; < > { } [ ] _ ^ \ ~
	//
	Line3   optionalnullable.OptionalNullable[string] `json:"line3,omitempty"`
	Country optionalnullable.OptionalNullable[string] `json:"country,omitempty"`
}

func (o *PostCombinedTransfersCounterpartyBankAddress) GetLine1() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Line1
}

func (o *PostCombinedTransfersCounterpartyBankAddress) GetLine2() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Line2
}

func (o *PostCombinedTransfersCounterpartyBankAddress) GetLine3() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Line3
}

func (o *PostCombinedTransfersCounterpartyBankAddress) GetCountry() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Country
}

// SyntheticAccountWire - Contains wire-specific information. Only populated if the Synthetic Account is in the `wire_external` category.
type SyntheticAccountWire struct {
	// Address of the business or individual who owns the external account.
	//
	CounterpartyAddress optionalnullable.OptionalNullable[PostCombinedTransfersWireCounterpartyAddress] `json:"counterparty_address,omitempty"`
	// Name of the business or individual who owns the counterparty Account. Required for synthetic accounts in the wire_external category. Maximum 35 characters.
	//
	CounterpartyName string `json:"counterparty_name"`
	// Address of the financial institution where the external account is held.
	//
	CounterpartyBankAddress optionalnullable.OptionalNullable[PostCombinedTransfersCounterpartyBankAddress] `json:"counterparty_bank_address,omitempty"`
	// Name of the financial institution where the counterparty account is held.
	//
	CounterpartyBankName optionalnullable.OptionalNullable[string] `json:"counterparty_bank_name,omitempty"`
}

func (o *SyntheticAccountWire) GetCounterpartyAddress() optionalnullable.OptionalNullable[PostCombinedTransfersWireCounterpartyAddress] {
	if o == nil {
		return nil
	}
	return o.CounterpartyAddress
}

func (o *SyntheticAccountWire) GetCounterpartyName() string {
	if o == nil {
		return ""
	}
	return o.CounterpartyName
}

func (o *SyntheticAccountWire) GetCounterpartyBankAddress() optionalnullable.OptionalNullable[PostCombinedTransfersCounterpartyBankAddress] {
	if o == nil {
		return nil
	}
	return o.CounterpartyBankAddress
}

func (o *SyntheticAccountWire) GetCounterpartyBankName() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.CounterpartyBankName
}

// SyntheticAccountRequest - Synthetic Account to be created or reused for a transfer. For more details on object structure, supported options and examples please refer to  [POST /synthetic_accounts](#tag/Synthetic-Accounts/paths/~1synthetic_accounts/post).
type SyntheticAccountRequest struct {
	// A unique identifier the Client supplies. It must be unique within the resource type. If the same value is given, no new resource will be created.
	//
	ExternalUID string `json:"external_uid"`
	// A unique name, per pool, to identify the resource
	Name string `json:"name"`
	// The unique id of the Synthetic Account's pool
	PoolUID string `json:"pool_uid"`
	// A unique id referring to the Synthetic Account's type.
	//
	SyntheticAccountTypeUID string `json:"synthetic_account_type_uid"`
	// The ABA routing number (if any) associated with this account. Some Synthetic Account Types require this field to be submitted along with the POST request. For example, any Synthetic Account Type from the `ach_external` or the `wire_external` category will require a `routing_number`. Submitting a `routing_number` with a Synthetic Account Type that does not require one will result in the routing number being ignored.
	RoutingNumber optionalnullable.OptionalNullable[string] `json:"routing_number,omitempty"`
	// The account number (if any) associated with this account. Some Synthetic Account Types require this field to be submitted along with the POST request. For example, any Synthetic Account Type from the `ach_external` or the `wire_external` category will require an `account_number`. Submitting an `account_number` with a Synthetic Account Type that does not require one will result in the account number being ignored.
	AccountNumber optionalnullable.OptionalNullable[string] `json:"account_number,omitempty"`
	// The processor token required to create certain Synthetic Account Types.
	ExternalProcessorToken optionalnullable.OptionalNullable[string] `json:"external_processor_token,omitempty"`
	// Contains ACH-specific information. Only populated if the Synthetic Account is in the `ach_external` category.
	//
	Ach *SyntheticAccountAch `json:"ach,omitempty"`
	// Contains Instant Payment-specific information. Only populated if the Synthetic Account is in the `instant_payments_external` category.
	//
	InstantPayment *SyntheticAccountInstantPayment `json:"instant_payment,omitempty"`
	// Contains wire-specific information. Only populated if the Synthetic Account is in the `wire_external` category.
	//
	Wire *SyntheticAccountWire `json:"wire,omitempty"`
}

func (o *SyntheticAccountRequest) GetExternalUID() string {
	if o == nil {
		return ""
	}
	return o.ExternalUID
}

func (o *SyntheticAccountRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *SyntheticAccountRequest) GetPoolUID() string {
	if o == nil {
		return ""
	}
	return o.PoolUID
}

func (o *SyntheticAccountRequest) GetSyntheticAccountTypeUID() string {
	if o == nil {
		return ""
	}
	return o.SyntheticAccountTypeUID
}

func (o *SyntheticAccountRequest) GetRoutingNumber() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.RoutingNumber
}

func (o *SyntheticAccountRequest) GetAccountNumber() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.AccountNumber
}

func (o *SyntheticAccountRequest) GetExternalProcessorToken() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.ExternalProcessorToken
}

func (o *SyntheticAccountRequest) GetAch() *SyntheticAccountAch {
	if o == nil {
		return nil
	}
	return o.Ach
}

func (o *SyntheticAccountRequest) GetInstantPayment() *SyntheticAccountInstantPayment {
	if o == nil {
		return nil
	}
	return o.InstantPayment
}

func (o *SyntheticAccountRequest) GetWire() *SyntheticAccountWire {
	if o == nil {
		return nil
	}
	return o.Wire
}

// PostCombinedTransfersInitiatorType - The initiator_type declares the originator for the Transfer. If set to Customer, origination information is pulled from the supplied initiating_customer_uid. If set to Transmitter, origination information is required, provided in the transmitter object (see below). Defaults to Customer. Providing Transmitter information is the Client's responsibility, please review more details in our [Transfers guide](https://developers.newline53.com/docs/transfer#introduction-what-is-a-transfer).
type PostCombinedTransfersInitiatorType string

const (
	PostCombinedTransfersInitiatorTypeCustomer    PostCombinedTransfersInitiatorType = "customer"
	PostCombinedTransfersInitiatorTypeTransmitter PostCombinedTransfersInitiatorType = "transmitter"
)

func (e PostCombinedTransfersInitiatorType) ToPointer() *PostCombinedTransfersInitiatorType {
	return &e
}
func (e *PostCombinedTransfersInitiatorType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "customer":
		fallthrough
	case "transmitter":
		*e = PostCombinedTransfersInitiatorType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostCombinedTransfersInitiatorType: %v", v)
	}
}

// PostCombinedTransfersSecCode - Standard Entry Class (SEC) code. Newline supports the following SEC codes: CCD, CIE, PPD, TEL, WEB. For more details, refer to our ACH guide's [section](https://developers.newline53.com/docs/ach#standard-entry-class-sec-codes) on SEC code use.
type PostCombinedTransfersSecCode string

const (
	PostCombinedTransfersSecCodeCcd PostCombinedTransfersSecCode = "CCD"
	PostCombinedTransfersSecCodeCie PostCombinedTransfersSecCode = "CIE"
	PostCombinedTransfersSecCodePpd PostCombinedTransfersSecCode = "PPD"
	PostCombinedTransfersSecCodeTel PostCombinedTransfersSecCode = "TEL"
	PostCombinedTransfersSecCodeWeb PostCombinedTransfersSecCode = "WEB"
)

func (e PostCombinedTransfersSecCode) ToPointer() *PostCombinedTransfersSecCode {
	return &e
}
func (e *PostCombinedTransfersSecCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "CCD":
		fallthrough
	case "CIE":
		fallthrough
	case "PPD":
		fallthrough
	case "TEL":
		fallthrough
	case "WEB":
		*e = PostCombinedTransfersSecCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostCombinedTransfersSecCode: %v", v)
	}
}

// PostCombinedTransfersPaymentType - Recurring (R), single entry (S), or standing authorization entry (ST). If no value is provided, the default value populated in the NACHA file is for a single entry.
type PostCombinedTransfersPaymentType string

const (
	PostCombinedTransfersPaymentTypeR  PostCombinedTransfersPaymentType = "R"
	PostCombinedTransfersPaymentTypeS  PostCombinedTransfersPaymentType = "S"
	PostCombinedTransfersPaymentTypeSt PostCombinedTransfersPaymentType = "ST"
)

func (e PostCombinedTransfersPaymentType) ToPointer() *PostCombinedTransfersPaymentType {
	return &e
}
func (e *PostCombinedTransfersPaymentType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "R":
		fallthrough
	case "S":
		fallthrough
	case "ST":
		*e = PostCombinedTransfersPaymentType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostCombinedTransfersPaymentType: %v", v)
	}
}

// PostCombinedTransfersServiceProcessing - Requested service processing duration for the ACH transfer. Allowable values are: STANDARD or SAMEDAY
type PostCombinedTransfersServiceProcessing string

const (
	PostCombinedTransfersServiceProcessingSameday  PostCombinedTransfersServiceProcessing = "SAMEDAY"
	PostCombinedTransfersServiceProcessingStandard PostCombinedTransfersServiceProcessing = "STANDARD"
)

func (e PostCombinedTransfersServiceProcessing) ToPointer() *PostCombinedTransfersServiceProcessing {
	return &e
}
func (e *PostCombinedTransfersServiceProcessing) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "SAMEDAY":
		fallthrough
	case "STANDARD":
		*e = PostCombinedTransfersServiceProcessing(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostCombinedTransfersServiceProcessing: %v", v)
	}
}

// TransferAch - ACH information. Only present if the Transfer is an ACH.
type TransferAch struct {
	// Individual or business originating the ACH transfer. 1 to 16 characters; letters, numbers, apostrophe, comma, period, dash allowed.
	//
	OriginatorName string `json:"originator_name"`
	// ACH Company ID. 1 to 10 characters. Letters, numbers, apostrophe, comma, period, dash allowed. Optional for the majority of cases. Required if the general liability account is configured with multiple IDs. Whether optional or required, it will be validated if supplied.
	//
	CompanyID *string `json:"company_id,omitempty"`
	// An optional field to add customized information such as a customer code or internal reference number. 1 to 10 characters. Alphanumeric. Also allows '.', ',', or '-'.
	//
	CompanyDiscretionaryData *string `json:"company_discretionary_data,omitempty"`
	// If prenote is 'true', the amount of the transfer must be $0.00. Newline will infer credit_prenote or debit_prenote based on the source and destination accounts. If prenote is 'true', then the resulting Transaction Type of the resulting transaction record is of type: 'ach'. If no value is provided, the default value will be 'false'.
	//
	Prenote *bool `json:"prenote,omitempty"`
	// Standard Entry Class (SEC) code. Newline supports the following SEC codes: CCD, CIE, PPD, TEL, WEB. For more details, refer to our ACH guide's [section](https://developers.newline53.com/docs/ach#standard-entry-class-sec-codes) on SEC code use.
	//
	SecCode PostCombinedTransfersSecCode `json:"sec_code"`
	// Recurring (R), single entry (S), or standing authorization entry (ST). If no value is provided, the default value populated in the NACHA file is for a single entry.
	//
	PaymentType *PostCombinedTransfersPaymentType `json:"payment_type,omitempty"`
	// Description value that will appear in the bank statement.
	//
	EntryDescription string `json:"entry_description"`
	// Requested service processing duration for the ACH transfer. Allowable values are: STANDARD or SAMEDAY
	//
	ServiceProcessing PostCombinedTransfersServiceProcessing `json:"service_processing"`
	// The effective date when the transaction is scheduled to be processed. Date values provided cannot be in the past or provided in the future beyond 30 days. For received returns, if the date provided by the originating financial institution does not match the Newline format, then the raw value will be returned. The Newline date format is YYYY-MM-DD
	//
	EffectiveEntryDate string `json:"effective_entry_date"`
	// Unique identifier supplied by the originator of a transaction (e.g. invoice number). 1 to 22 characters depending on SEC code, alphanumeric. If the SEC value is anything other than CIE, then this is an optional field and can be up to 15 characters. If SEC value CIE is provided, then the ID number is mandatory, and the character length can be up to 22 characters.
	//
	IDNumber *string `json:"id_number,omitempty"`
	// Optional additional payment-related information, such as invoice numbers, originator/receiver information, payment instructions, etc. Up to 80 characters. Optional for all newline supported SEC codes other than TEL. Newline will reject the Transfer if an Addenda value is provided with SEC code TEL.
	//
	Addenda *string `json:"addenda,omitempty"`
}

func (o *TransferAch) GetOriginatorName() string {
	if o == nil {
		return ""
	}
	return o.OriginatorName
}

func (o *TransferAch) GetCompanyID() *string {
	if o == nil {
		return nil
	}
	return o.CompanyID
}

func (o *TransferAch) GetCompanyDiscretionaryData() *string {
	if o == nil {
		return nil
	}
	return o.CompanyDiscretionaryData
}

func (o *TransferAch) GetPrenote() *bool {
	if o == nil {
		return nil
	}
	return o.Prenote
}

func (o *TransferAch) GetSecCode() PostCombinedTransfersSecCode {
	if o == nil {
		return PostCombinedTransfersSecCode("")
	}
	return o.SecCode
}

func (o *TransferAch) GetPaymentType() *PostCombinedTransfersPaymentType {
	if o == nil {
		return nil
	}
	return o.PaymentType
}

func (o *TransferAch) GetEntryDescription() string {
	if o == nil {
		return ""
	}
	return o.EntryDescription
}

func (o *TransferAch) GetServiceProcessing() PostCombinedTransfersServiceProcessing {
	if o == nil {
		return PostCombinedTransfersServiceProcessing("")
	}
	return o.ServiceProcessing
}

func (o *TransferAch) GetEffectiveEntryDate() string {
	if o == nil {
		return ""
	}
	return o.EffectiveEntryDate
}

func (o *TransferAch) GetIDNumber() *string {
	if o == nil {
		return nil
	}
	return o.IDNumber
}

func (o *TransferAch) GetAddenda() *string {
	if o == nil {
		return nil
	}
	return o.Addenda
}

// PostCombinedTransfersInstantPaymentTransmitter - Address of the Transmitter. Must be provided if the `initiator_type` is `transmitter`.
type PostCombinedTransfersInstantPaymentTransmitter struct {
	// Name of the Transmitter.
	//
	Name string `json:"name"`
	// Up to 24 characters, and supplied by Transmitter. Alphanumeric only.
	TransmitterIdentifier string `json:"transmitter_identifier"`
	// Building number for Transmitter address. Alphanumeric only.
	StreetNumber string `json:"street_number"`
	// Street name for Transmitter address
	Street1 string `json:"street1"`
	// Maximum 35 characters
	City *string `json:"city"`
	// 2 characters. Must be a valid US state abbreviation.
	State *string `json:"state"`
	// 5-digit string. ZIP+4 is allowed.
	PostalCode *string `json:"postal_code"`
	Country    *string `json:"country"`
}

func (o *PostCombinedTransfersInstantPaymentTransmitter) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *PostCombinedTransfersInstantPaymentTransmitter) GetTransmitterIdentifier() string {
	if o == nil {
		return ""
	}
	return o.TransmitterIdentifier
}

func (o *PostCombinedTransfersInstantPaymentTransmitter) GetStreetNumber() string {
	if o == nil {
		return ""
	}
	return o.StreetNumber
}

func (o *PostCombinedTransfersInstantPaymentTransmitter) GetStreet1() string {
	if o == nil {
		return ""
	}
	return o.Street1
}

func (o *PostCombinedTransfersInstantPaymentTransmitter) GetCity() *string {
	if o == nil {
		return nil
	}
	return o.City
}

func (o *PostCombinedTransfersInstantPaymentTransmitter) GetState() *string {
	if o == nil {
		return nil
	}
	return o.State
}

func (o *PostCombinedTransfersInstantPaymentTransmitter) GetPostalCode() *string {
	if o == nil {
		return nil
	}
	return o.PostalCode
}

func (o *PostCombinedTransfersInstantPaymentTransmitter) GetCountry() *string {
	if o == nil {
		return nil
	}
	return o.Country
}

// TransferInstantPayment - Instant payment information. Only present if the Transfer is an instant payment.
type TransferInstantPayment struct {
	InstantPaymentTransmitter *PostCombinedTransfersInstantPaymentTransmitter `json:"instant_payment_transmitter,omitempty"`
	// A message transmitted to the recipient bank. Can contain letters and numbers as well as '-', '_', and spaces.
	//
	Memo optionalnullable.OptionalNullable[string] `json:"memo,omitempty"`
}

func (o *TransferInstantPayment) GetInstantPaymentTransmitter() *PostCombinedTransfersInstantPaymentTransmitter {
	if o == nil {
		return nil
	}
	return o.InstantPaymentTransmitter
}

func (o *TransferInstantPayment) GetMemo() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Memo
}

type PostCombinedTransfersIntermediaryBankAddress struct {
	// Optional 35 characters. Cannot contain \# @ $ ! " % & * ; < > { } [ ] _ ^ \ ~
	//
	Line1 optionalnullable.OptionalNullable[string] `json:"line1,omitempty"`
	// Optional 35 characters. Cannot contain \# @ $ ! " % & * ; < > { } [ ] _ ^ \ ~
	//
	Line2 optionalnullable.OptionalNullable[string] `json:"line2,omitempty"`
	// Optional 32 characters. Note that this length is shorter than the other lines. Cannot contain \# @ $ ! " % & * ; < > { } [ ] _ ^ \ ~
	//
	Line3   optionalnullable.OptionalNullable[string] `json:"line3,omitempty"`
	Country optionalnullable.OptionalNullable[string] `json:"country,omitempty"`
}

func (o *PostCombinedTransfersIntermediaryBankAddress) GetLine1() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Line1
}

func (o *PostCombinedTransfersIntermediaryBankAddress) GetLine2() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Line2
}

func (o *PostCombinedTransfersIntermediaryBankAddress) GetLine3() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Line3
}

func (o *PostCombinedTransfersIntermediaryBankAddress) GetCountry() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Country
}

// PostCombinedTransfersWireTransmitter - Address of the Transmitter. Must be provided if the `initiator_type` is `transmitter`.
type PostCombinedTransfersWireTransmitter struct {
	// Name of the Transmitter.
	//
	Name string `json:"name"`
	// Up to 24 characters, and supplied by Transmitter. Alphanumeric only.
	TransmitterIdentifier string `json:"transmitter_identifier"`
	// Up to 35 characters. Cannot contain \# @ $ ! " % & * ; < > { } [ ] _ ^ \ ~
	Line1 *string `json:"line1"`
	// Optional 35 characters. Cannot contain \# @ $ ! " % & * ; < > { } [ ] _ ^ \ ~
	//
	Line2 optionalnullable.OptionalNullable[string] `json:"line2,omitempty"`
	// Optional 32 characters. Note that this length is shorter than the other lines. Cannot contain \# @ $ ! " % & * ; < > { } [ ] _ ^ \ ~
	//
	Line3   optionalnullable.OptionalNullable[string] `json:"line3,omitempty"`
	Country string                                    `json:"country"`
}

func (o *PostCombinedTransfersWireTransmitter) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *PostCombinedTransfersWireTransmitter) GetTransmitterIdentifier() string {
	if o == nil {
		return ""
	}
	return o.TransmitterIdentifier
}

func (o *PostCombinedTransfersWireTransmitter) GetLine1() *string {
	if o == nil {
		return nil
	}
	return o.Line1
}

func (o *PostCombinedTransfersWireTransmitter) GetLine2() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Line2
}

func (o *PostCombinedTransfersWireTransmitter) GetLine3() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Line3
}

func (o *PostCombinedTransfersWireTransmitter) GetCountry() string {
	if o == nil {
		return ""
	}
	return o.Country
}

// TransferWire - Wire-specific information. Only present if the Transfer is a wire.
type TransferWire struct {
	// Address of the intermediary bank. To be populated if an intermediary bank is required to execute the wire transfer.
	//
	IntermediaryBankAddress *PostCombinedTransfersIntermediaryBankAddress `json:"intermediary_bank_address,omitempty"`
	IntermediaryBankName    *string                                       `json:"intermediary_bank_name,omitempty"`
	// The ABA routing number associated with the intermediary bank involved in the wire transfer. This value is required if intermediary_bank_name or intermediary_bank_address is present; optional otherwise
	//
	IntermediaryBankRoutingNumber *string `json:"intermediary_bank_routing_number,omitempty"`
	// Additional details or instructions for the wire, issued to the recipient financial institution when the wire is executed.
	//
	WireInstructions *string                               `json:"wire_instructions,omitempty"`
	WireTransmitter  *PostCombinedTransfersWireTransmitter `json:"wire_transmitter,omitempty"`
}

func (o *TransferWire) GetIntermediaryBankAddress() *PostCombinedTransfersIntermediaryBankAddress {
	if o == nil {
		return nil
	}
	return o.IntermediaryBankAddress
}

func (o *TransferWire) GetIntermediaryBankName() *string {
	if o == nil {
		return nil
	}
	return o.IntermediaryBankName
}

func (o *TransferWire) GetIntermediaryBankRoutingNumber() *string {
	if o == nil {
		return nil
	}
	return o.IntermediaryBankRoutingNumber
}

func (o *TransferWire) GetWireInstructions() *string {
	if o == nil {
		return nil
	}
	return o.WireInstructions
}

func (o *TransferWire) GetWireTransmitter() *PostCombinedTransfersWireTransmitter {
	if o == nil {
		return nil
	}
	return o.WireTransmitter
}

// TransferRequest - Transfer details to initiate a transfer with. For more details on object structure, supported options and examples please refer to [POST /transfers](#tag/Transfers/paths/~1transfers/post). **NOTE:** Only source or destination synthetic account uid must be supplied for combined transfer, `synthetic_account` from the request will be used as the other party.
type TransferRequest struct {
	// A unique identifier the Client supplies. It must be unique within the resource type. If the same value is given, no new resource will be created.
	//
	ExternalUID *string `json:"external_uid,omitempty"`
	// Synthetic Account where the assets should be debited. Must be an active liability or external-type account. Cannot be equal to `destination_synthetic_account_uid`.
	SourceSyntheticAccountUID string `json:"source_synthetic_account_uid"`
	// Synthetic Account where the assets should be credited. Must be an active liability or external-type account. Cannot be equal to `source_synthetic_account_uid`.
	DestinationSyntheticAccountUID string `json:"destination_synthetic_account_uid"`
	// Customer that initiated the Transfer, when `initiator_type` is `customer`. The Customer and Synthetic Accounts supplied in the Transfer request must relate to the same Pool for the Transfer to be accepted.
	InitiatingCustomerUID string `json:"initiating_customer_uid"`
	// Customer who is on the receiving end of the Transfer. The destination Customer must be provided for peer to peer Transfers and can be optional for all other Transfers. If not provided, the destination Customer will be the same as the initiating Customer by default.
	DestinationCustomerUID *string `json:"destination_customer_uid,omitempty"`
	// The initiator_type declares the originator for the Transfer. If set to Customer, origination information is pulled from the supplied initiating_customer_uid. If set to Transmitter, origination information is required, provided in the transmitter object (see below). Defaults to Customer. Providing Transmitter information is the Client's responsibility, please review more details in our [Transfers guide](https://developers.newline53.com/docs/transfer#introduction-what-is-a-transfer).
	//
	InitiatorType *PostCombinedTransfersInitiatorType `json:"initiator_type,omitempty"`
	// The USD amount to transfer
	UsdTransferAmount string `json:"usd_transfer_amount"`
	// ACH information. Only present if the Transfer is an ACH.
	//
	Ach *TransferAch `json:"ach,omitempty"`
	// Instant payment information. Only present if the Transfer is an instant payment.
	//
	InstantPayment *TransferInstantPayment `json:"instant_payment,omitempty"`
	// Wire-specific information. Only present if the Transfer is a wire.
	//
	Wire *TransferWire `json:"wire,omitempty"`
}

func (o *TransferRequest) GetExternalUID() *string {
	if o == nil {
		return nil
	}
	return o.ExternalUID
}

func (o *TransferRequest) GetSourceSyntheticAccountUID() string {
	if o == nil {
		return ""
	}
	return o.SourceSyntheticAccountUID
}

func (o *TransferRequest) GetDestinationSyntheticAccountUID() string {
	if o == nil {
		return ""
	}
	return o.DestinationSyntheticAccountUID
}

func (o *TransferRequest) GetInitiatingCustomerUID() string {
	if o == nil {
		return ""
	}
	return o.InitiatingCustomerUID
}

func (o *TransferRequest) GetDestinationCustomerUID() *string {
	if o == nil {
		return nil
	}
	return o.DestinationCustomerUID
}

func (o *TransferRequest) GetInitiatorType() *PostCombinedTransfersInitiatorType {
	if o == nil {
		return nil
	}
	return o.InitiatorType
}

func (o *TransferRequest) GetUsdTransferAmount() string {
	if o == nil {
		return ""
	}
	return o.UsdTransferAmount
}

func (o *TransferRequest) GetAch() *TransferAch {
	if o == nil {
		return nil
	}
	return o.Ach
}

func (o *TransferRequest) GetInstantPayment() *TransferInstantPayment {
	if o == nil {
		return nil
	}
	return o.InstantPayment
}

func (o *TransferRequest) GetWire() *TransferWire {
	if o == nil {
		return nil
	}
	return o.Wire
}

type PostCombinedTransfersRequest struct {
	// Optional client-supplied uid
	ExternalUID      *string                 `json:"external_uid,omitempty"`
	SyntheticAccount SyntheticAccountRequest `json:"synthetic_account"`
	Transfer         TransferRequest         `json:"transfer"`
}

func (o *PostCombinedTransfersRequest) GetExternalUID() *string {
	if o == nil {
		return nil
	}
	return o.ExternalUID
}

func (o *PostCombinedTransfersRequest) GetSyntheticAccount() SyntheticAccountRequest {
	if o == nil {
		return SyntheticAccountRequest{}
	}
	return o.SyntheticAccount
}

func (o *PostCombinedTransfersRequest) GetTransfer() TransferRequest {
	if o == nil {
		return TransferRequest{}
	}
	return o.Transfer
}

type PostCombinedTransfersUnprocessableEntityError struct {
	// Code provided by Newline for reference
	Code *int64 `json:"code,omitempty"`
	// Title of Error Code
	Title *string `json:"title,omitempty"`
	// Description of Error Code
	Detail *string `json:"detail,omitempty"`
	// Error Timestamp
	OccurredAt *string `json:"occurred_at,omitempty"`
	// Included based on Error Code; Additional context to help users self-solve the error
	Extra *string `json:"extra,omitempty"`
}

func (o *PostCombinedTransfersUnprocessableEntityError) GetCode() *int64 {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *PostCombinedTransfersUnprocessableEntityError) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *PostCombinedTransfersUnprocessableEntityError) GetDetail() *string {
	if o == nil {
		return nil
	}
	return o.Detail
}

func (o *PostCombinedTransfersUnprocessableEntityError) GetOccurredAt() *string {
	if o == nil {
		return nil
	}
	return o.OccurredAt
}

func (o *PostCombinedTransfersUnprocessableEntityError) GetExtra() *string {
	if o == nil {
		return nil
	}
	return o.Extra
}

type PostCombinedTransfersForbiddenError struct {
	// Code provided by Newline for reference
	Code *int64 `json:"code,omitempty"`
	// Title of Error Code
	Title *string `json:"title,omitempty"`
	// Description of Error Code
	Detail *string `json:"detail,omitempty"`
	// Error Timestamp
	OccurredAt *string `json:"occurred_at,omitempty"`
	// Included based on Error Code; Additional context to help users self-solve the error
	Extra *string `json:"extra,omitempty"`
}

func (o *PostCombinedTransfersForbiddenError) GetCode() *int64 {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *PostCombinedTransfersForbiddenError) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *PostCombinedTransfersForbiddenError) GetDetail() *string {
	if o == nil {
		return nil
	}
	return o.Detail
}

func (o *PostCombinedTransfersForbiddenError) GetOccurredAt() *string {
	if o == nil {
		return nil
	}
	return o.OccurredAt
}

func (o *PostCombinedTransfersForbiddenError) GetExtra() *string {
	if o == nil {
		return nil
	}
	return o.Extra
}

type PostCombinedTransfersError struct {
	// Code provided by Newline for reference
	Code *int64 `json:"code,omitempty"`
	// Title of Error Code
	Title *string `json:"title,omitempty"`
	// Description of Error Code
	Detail *string `json:"detail,omitempty"`
	// Error Timestamp
	OccurredAt *string `json:"occurred_at,omitempty"`
	// Included based on Error Code; Additional context to help users self-solve the error
	Extra *string `json:"extra,omitempty"`
}

func (o *PostCombinedTransfersError) GetCode() *int64 {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *PostCombinedTransfersError) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *PostCombinedTransfersError) GetDetail() *string {
	if o == nil {
		return nil
	}
	return o.Detail
}

func (o *PostCombinedTransfersError) GetOccurredAt() *string {
	if o == nil {
		return nil
	}
	return o.OccurredAt
}

func (o *PostCombinedTransfersError) GetExtra() *string {
	if o == nil {
		return nil
	}
	return o.Extra
}

// PostCombinedTransfersStatus - The combined transfer's status
type PostCombinedTransfersStatus string

const (
	PostCombinedTransfersStatusQueued    PostCombinedTransfersStatus = "queued"
	PostCombinedTransfersStatusPending   PostCombinedTransfersStatus = "pending"
	PostCombinedTransfersStatusFailed    PostCombinedTransfersStatus = "failed"
	PostCombinedTransfersStatusCompleted PostCombinedTransfersStatus = "completed"
)

func (e PostCombinedTransfersStatus) ToPointer() *PostCombinedTransfersStatus {
	return &e
}
func (e *PostCombinedTransfersStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "queued":
		fallthrough
	case "pending":
		fallthrough
	case "failed":
		fallthrough
	case "completed":
		*e = PostCombinedTransfersStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostCombinedTransfersStatus: %v", v)
	}
}

// PostCombinedTransfersSyntheticAccountResponse - Parameters provided at time of creation. UID field will get populated once synthetic account has been successfully created, unless uid value was supplied at creation time.
type PostCombinedTransfersSyntheticAccountResponse struct {
}

// PostCombinedTransfersTransferResponse - Parameters provided at time of creation. UID field will get populated once transfer has been successfully initiated.
type PostCombinedTransfersTransferResponse struct {
}

// PostCombinedTransfersResponseBody - A single Combined Transfer is returned
type PostCombinedTransfersResponseBody struct {
	// Timestamp of when the combined_transfer was created
	CreatedAt *string `json:"created_at,omitempty"`
	// A collection of errors that occured during synthetic account and/or transfer creation. Only displayed if errors were detected.
	//
	Errors []PostCombinedTransfersError `json:"errors,omitempty"`
	// Optional client-supplied uid
	ExternalUID *string `json:"external_uid,omitempty"`
	// The combined transfer's status
	Status *PostCombinedTransfersStatus `json:"status,omitempty"`
	// Parameters provided at time of creation. UID field will get populated once synthetic account has been successfully created, unless uid value was supplied at creation time.
	//
	SyntheticAccount *PostCombinedTransfersSyntheticAccountResponse `json:"synthetic_account,omitempty"`
	// Parameters provided at time of creation. UID field will get populated once transfer has been successfully initiated.
	//
	Transfer *PostCombinedTransfersTransferResponse `json:"transfer,omitempty"`
	// Unique identifier for the Combined Transfer
	UID *string `json:"uid,omitempty"`
}

func (o *PostCombinedTransfersResponseBody) GetCreatedAt() *string {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *PostCombinedTransfersResponseBody) GetErrors() []PostCombinedTransfersError {
	if o == nil {
		return nil
	}
	return o.Errors
}

func (o *PostCombinedTransfersResponseBody) GetExternalUID() *string {
	if o == nil {
		return nil
	}
	return o.ExternalUID
}

func (o *PostCombinedTransfersResponseBody) GetStatus() *PostCombinedTransfersStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *PostCombinedTransfersResponseBody) GetSyntheticAccount() *PostCombinedTransfersSyntheticAccountResponse {
	if o == nil {
		return nil
	}
	return o.SyntheticAccount
}

func (o *PostCombinedTransfersResponseBody) GetTransfer() *PostCombinedTransfersTransferResponse {
	if o == nil {
		return nil
	}
	return o.Transfer
}

func (o *PostCombinedTransfersResponseBody) GetUID() *string {
	if o == nil {
		return nil
	}
	return o.UID
}

type PostCombinedTransfersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A single Combined Transfer is returned
	Object  *PostCombinedTransfersResponseBody
	Headers map[string][]string
}

func (o *PostCombinedTransfersResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PostCombinedTransfersResponse) GetObject() *PostCombinedTransfersResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *PostCombinedTransfersResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
