// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/optionalnullable"
	"mockserver/internal/sdk/utils"
	"time"
)

// UpdateSyntheticAccountAccountTypeRequest - The type of ACH account
type UpdateSyntheticAccountAccountTypeRequest string

const (
	UpdateSyntheticAccountAccountTypeRequestChecking UpdateSyntheticAccountAccountTypeRequest = "checking"
	UpdateSyntheticAccountAccountTypeRequestSavings  UpdateSyntheticAccountAccountTypeRequest = "savings"
)

func (e UpdateSyntheticAccountAccountTypeRequest) ToPointer() *UpdateSyntheticAccountAccountTypeRequest {
	return &e
}
func (e *UpdateSyntheticAccountAccountTypeRequest) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "checking":
		fallthrough
	case "savings":
		*e = UpdateSyntheticAccountAccountTypeRequest(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateSyntheticAccountAccountTypeRequest: %v", v)
	}
}

// UpdateSyntheticAccountAchRequest - Contains ACH-specific information. Only populated if the Synthetic Account is in the `ach_external` category.
type UpdateSyntheticAccountAchRequest struct {
	// The type of ACH account
	AccountType *UpdateSyntheticAccountAccountTypeRequest `json:"account_type,omitempty"`
	// Name of the business or individual who owns the external account. Conditional maximum character length: for all newline supported SEC codes other than CIE, the counterparty_name can be 22 characters. For CIE SEC codes, the counterparty_name can be up to 15 characters.
	//
	CounterpartyName *string `json:"counterparty_name,omitempty"`
}

func (o *UpdateSyntheticAccountAchRequest) GetAccountType() *UpdateSyntheticAccountAccountTypeRequest {
	if o == nil {
		return nil
	}
	return o.AccountType
}

func (o *UpdateSyntheticAccountAchRequest) GetCounterpartyName() *string {
	if o == nil {
		return nil
	}
	return o.CounterpartyName
}

type UpdateSyntheticAccountInstantPaymentCounterpartyAddressRequest struct {
	// Building number for counterparty address. Alphanumeric only.
	StreetNumber string `json:"street_number"`
	// Street name for counterparty address
	Street1 string `json:"street1"`
	// Optional second line of street
	Street2 *string `json:"street2,omitempty"`
	// Maximum 35 characters
	City *string `json:"city"`
	// 2 characters. Must be a valid US state abbreviation.
	State *string `json:"state"`
	// 5-digit string. ZIP+4 is allowed.
	PostalCode *string `json:"postal_code"`
	Country    *string `json:"country"`
}

func (o *UpdateSyntheticAccountInstantPaymentCounterpartyAddressRequest) GetStreetNumber() string {
	if o == nil {
		return ""
	}
	return o.StreetNumber
}

func (o *UpdateSyntheticAccountInstantPaymentCounterpartyAddressRequest) GetStreet1() string {
	if o == nil {
		return ""
	}
	return o.Street1
}

func (o *UpdateSyntheticAccountInstantPaymentCounterpartyAddressRequest) GetStreet2() *string {
	if o == nil {
		return nil
	}
	return o.Street2
}

func (o *UpdateSyntheticAccountInstantPaymentCounterpartyAddressRequest) GetCity() *string {
	if o == nil {
		return nil
	}
	return o.City
}

func (o *UpdateSyntheticAccountInstantPaymentCounterpartyAddressRequest) GetState() *string {
	if o == nil {
		return nil
	}
	return o.State
}

func (o *UpdateSyntheticAccountInstantPaymentCounterpartyAddressRequest) GetPostalCode() *string {
	if o == nil {
		return nil
	}
	return o.PostalCode
}

func (o *UpdateSyntheticAccountInstantPaymentCounterpartyAddressRequest) GetCountry() *string {
	if o == nil {
		return nil
	}
	return o.Country
}

// UpdateSyntheticAccountInstantPaymentRequest - Contains Instant Payment-specific information. Only populated if the Synthetic Account is in the `instant_payment_external` category.
type UpdateSyntheticAccountInstantPaymentRequest struct {
	// Address of the business or individual who owns the external account.
	//
	CounterpartyAddress *UpdateSyntheticAccountInstantPaymentCounterpartyAddressRequest `json:"counterparty_address,omitempty"`
	// Name of the business or individual who owns the counterparty Account.
	//
	CounterpartyName *string `json:"counterparty_name,omitempty"`
	// Email address of the counterparty
	Email optionalnullable.OptionalNullable[string] `json:"email,omitempty"`
	// Exactly 10 digits long (no hyphens, parentheses, or spaces)
	Phone optionalnullable.OptionalNullable[string] `json:"phone,omitempty"`
}

func (o *UpdateSyntheticAccountInstantPaymentRequest) GetCounterpartyAddress() *UpdateSyntheticAccountInstantPaymentCounterpartyAddressRequest {
	if o == nil {
		return nil
	}
	return o.CounterpartyAddress
}

func (o *UpdateSyntheticAccountInstantPaymentRequest) GetCounterpartyName() *string {
	if o == nil {
		return nil
	}
	return o.CounterpartyName
}

func (o *UpdateSyntheticAccountInstantPaymentRequest) GetEmail() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *UpdateSyntheticAccountInstantPaymentRequest) GetPhone() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Phone
}

// UpdateSyntheticAccountWireCounterpartyAddressRequest - Address of the business or individual who owns the external account.
type UpdateSyntheticAccountWireCounterpartyAddressRequest struct {
	// Optional 35 characters. Cannot contain \# @ $ ! " % & * ; < > { } [ ] _ ^ \ ~
	//
	Line1 optionalnullable.OptionalNullable[string] `json:"line1,omitempty"`
	// Optional 35 characters. Cannot contain \# @ $ ! " % & * ; < > { } [ ] _ ^ \ ~
	//
	Line2 optionalnullable.OptionalNullable[string] `json:"line2,omitempty"`
	// Optional 32 characters. Note that this length is shorter than the other lines. Cannot contain \# @ $ ! " % & * ; < > { } [ ] _ ^ \ ~
	//
	Line3   optionalnullable.OptionalNullable[string] `json:"line3,omitempty"`
	Country optionalnullable.OptionalNullable[string] `json:"country,omitempty"`
}

func (o *UpdateSyntheticAccountWireCounterpartyAddressRequest) GetLine1() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Line1
}

func (o *UpdateSyntheticAccountWireCounterpartyAddressRequest) GetLine2() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Line2
}

func (o *UpdateSyntheticAccountWireCounterpartyAddressRequest) GetLine3() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Line3
}

func (o *UpdateSyntheticAccountWireCounterpartyAddressRequest) GetCountry() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Country
}

// UpdateSyntheticAccountCounterpartyBankAddressRequest - Address of the financial institution where the external account is held.
type UpdateSyntheticAccountCounterpartyBankAddressRequest struct {
	// Optional 35 characters. Cannot contain \# @ $ ! " % & * ; < > { } [ ] _ ^ \ ~
	//
	Line1 optionalnullable.OptionalNullable[string] `json:"line1,omitempty"`
	// Optional 35 characters. Cannot contain \# @ $ ! " % & * ; < > { } [ ] _ ^ \ ~
	//
	Line2 optionalnullable.OptionalNullable[string] `json:"line2,omitempty"`
	// Optional 32 characters. Note that this length is shorter than the other lines. Cannot contain \# @ $ ! " % & * ; < > { } [ ] _ ^ \ ~
	//
	Line3   optionalnullable.OptionalNullable[string] `json:"line3,omitempty"`
	Country optionalnullable.OptionalNullable[string] `json:"country,omitempty"`
}

func (o *UpdateSyntheticAccountCounterpartyBankAddressRequest) GetLine1() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Line1
}

func (o *UpdateSyntheticAccountCounterpartyBankAddressRequest) GetLine2() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Line2
}

func (o *UpdateSyntheticAccountCounterpartyBankAddressRequest) GetLine3() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Line3
}

func (o *UpdateSyntheticAccountCounterpartyBankAddressRequest) GetCountry() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Country
}

// UpdateSyntheticAccountWireRequest - Contains wire-specific information. Only populated if the Synthetic Account is in the `wire_external` category.
type UpdateSyntheticAccountWireRequest struct {
	// Address of the business or individual who owns the external account.
	//
	CounterpartyAddress optionalnullable.OptionalNullable[UpdateSyntheticAccountWireCounterpartyAddressRequest] `json:"counterparty_address,omitempty"`
	// Name of the business or individual who owns the counterparty Account. Required for synthetic accounts in the wire_external category. Maximum 35 characters.
	//
	CounterpartyName *string `json:"counterparty_name,omitempty"`
	// Address of the financial institution where the external account is held.
	//
	CounterpartyBankAddress optionalnullable.OptionalNullable[UpdateSyntheticAccountCounterpartyBankAddressRequest] `json:"counterparty_bank_address,omitempty"`
	// Name of the financial institution where the counterparty account is held.
	//
	CounterpartyBankName optionalnullable.OptionalNullable[string] `json:"counterparty_bank_name,omitempty"`
}

func (o *UpdateSyntheticAccountWireRequest) GetCounterpartyAddress() optionalnullable.OptionalNullable[UpdateSyntheticAccountWireCounterpartyAddressRequest] {
	if o == nil {
		return nil
	}
	return o.CounterpartyAddress
}

func (o *UpdateSyntheticAccountWireRequest) GetCounterpartyName() *string {
	if o == nil {
		return nil
	}
	return o.CounterpartyName
}

func (o *UpdateSyntheticAccountWireRequest) GetCounterpartyBankAddress() optionalnullable.OptionalNullable[UpdateSyntheticAccountCounterpartyBankAddressRequest] {
	if o == nil {
		return nil
	}
	return o.CounterpartyBankAddress
}

func (o *UpdateSyntheticAccountWireRequest) GetCounterpartyBankName() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.CounterpartyBankName
}

type UpdateSyntheticAccountRequestBody struct {
	// A unique identifier the Client supplies. It must be unique within the resource type. If the same value is given, no new resource will be created.
	//
	ExternalUID *string `json:"external_uid,omitempty"`
	// A unique name, per pool, to identify the resource
	Name *string `json:"name,omitempty"`
	// The unique id of the Synthetic Account's pool
	PoolUID *string `json:"pool_uid,omitempty"`
	// A unique id referring to the Synthetic Account's type.
	//
	SyntheticAccountTypeUID *string `json:"synthetic_account_type_uid,omitempty"`
	// The ABA routing number (if any) associated with this account. Some Synthetic Account Types require this field to be submitted along with the POST request. For example, any Synthetic Account Type from the `ach_external` or the `wire_external` category will require a `routing_number`. Submitting a `routing_number` with a Synthetic Account Type that does not require one will result in the routing number being ignored.
	RoutingNumber optionalnullable.OptionalNullable[string] `json:"routing_number,omitempty"`
	// The account number (if any) associated with this account. Some Synthetic Account Types require this field to be submitted along with the POST request. For example, any Synthetic Account Type from the `ach_external` or the `wire_external` category will require an `account_number`. Submitting an `account_number` with a Synthetic Account Type that does not require one will result in the account number being ignored.
	AccountNumber optionalnullable.OptionalNullable[string] `json:"account_number,omitempty"`
	// A reason for the Synthetic Account metadata change
	//
	Note *string `json:"note,omitempty"`
	// Contains ACH-specific information. Only populated if the Synthetic Account is in the `ach_external` category.
	//
	Ach *UpdateSyntheticAccountAchRequest `json:"ach,omitempty"`
	// Contains Instant Payment-specific information. Only populated if the Synthetic Account is in the `instant_payment_external` category.
	//
	InstantPayment *UpdateSyntheticAccountInstantPaymentRequest `json:"instant_payment,omitempty"`
	// Contains wire-specific information. Only populated if the Synthetic Account is in the `wire_external` category.
	//
	Wire *UpdateSyntheticAccountWireRequest `json:"wire,omitempty"`
}

func (o *UpdateSyntheticAccountRequestBody) GetExternalUID() *string {
	if o == nil {
		return nil
	}
	return o.ExternalUID
}

func (o *UpdateSyntheticAccountRequestBody) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UpdateSyntheticAccountRequestBody) GetPoolUID() *string {
	if o == nil {
		return nil
	}
	return o.PoolUID
}

func (o *UpdateSyntheticAccountRequestBody) GetSyntheticAccountTypeUID() *string {
	if o == nil {
		return nil
	}
	return o.SyntheticAccountTypeUID
}

func (o *UpdateSyntheticAccountRequestBody) GetRoutingNumber() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.RoutingNumber
}

func (o *UpdateSyntheticAccountRequestBody) GetAccountNumber() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.AccountNumber
}

func (o *UpdateSyntheticAccountRequestBody) GetNote() *string {
	if o == nil {
		return nil
	}
	return o.Note
}

func (o *UpdateSyntheticAccountRequestBody) GetAch() *UpdateSyntheticAccountAchRequest {
	if o == nil {
		return nil
	}
	return o.Ach
}

func (o *UpdateSyntheticAccountRequestBody) GetInstantPayment() *UpdateSyntheticAccountInstantPaymentRequest {
	if o == nil {
		return nil
	}
	return o.InstantPayment
}

func (o *UpdateSyntheticAccountRequestBody) GetWire() *UpdateSyntheticAccountWireRequest {
	if o == nil {
		return nil
	}
	return o.Wire
}

type UpdateSyntheticAccountRequest struct {
	// Newline-generated unique id resource specific to the current endpoint
	UID  string                            `pathParam:"style=simple,explode=false,name=uid"`
	Body UpdateSyntheticAccountRequestBody `request:"mediaType=application/json"`
}

func (o *UpdateSyntheticAccountRequest) GetUID() string {
	if o == nil {
		return ""
	}
	return o.UID
}

func (o *UpdateSyntheticAccountRequest) GetBody() UpdateSyntheticAccountRequestBody {
	if o == nil {
		return UpdateSyntheticAccountRequestBody{}
	}
	return o.Body
}

type UpdateSyntheticAccountError struct {
	// Code provided by Newline for reference
	Code *int64 `json:"code,omitempty"`
	// Title of Error Code
	Title *string `json:"title,omitempty"`
	// Description of Error Code
	Detail *string `json:"detail,omitempty"`
	// Error Timestamp
	OccurredAt *string `json:"occurred_at,omitempty"`
	// Included based on Error Code; Additional context to help users self-solve the error
	Extra *string `json:"extra,omitempty"`
}

func (o *UpdateSyntheticAccountError) GetCode() *int64 {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *UpdateSyntheticAccountError) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *UpdateSyntheticAccountError) GetDetail() *string {
	if o == nil {
		return nil
	}
	return o.Detail
}

func (o *UpdateSyntheticAccountError) GetOccurredAt() *string {
	if o == nil {
		return nil
	}
	return o.OccurredAt
}

func (o *UpdateSyntheticAccountError) GetExtra() *string {
	if o == nil {
		return nil
	}
	return o.Extra
}

// UpdateSyntheticAccountSyntheticAccountCategory - The name of the Synthetic Account Category associated with the Synthetic Account Type for this account. Refer to the Synthetic Account Type for details.
type UpdateSyntheticAccountSyntheticAccountCategory string

const (
	UpdateSyntheticAccountSyntheticAccountCategoryGeneral                UpdateSyntheticAccountSyntheticAccountCategory = "general"
	UpdateSyntheticAccountSyntheticAccountCategoryAchExternal            UpdateSyntheticAccountSyntheticAccountCategory = "ach_external"
	UpdateSyntheticAccountSyntheticAccountCategoryInstantPaymentExternal UpdateSyntheticAccountSyntheticAccountCategory = "instant_payment_external"
	UpdateSyntheticAccountSyntheticAccountCategoryWireExternal           UpdateSyntheticAccountSyntheticAccountCategory = "wire_external"
)

func (e UpdateSyntheticAccountSyntheticAccountCategory) ToPointer() *UpdateSyntheticAccountSyntheticAccountCategory {
	return &e
}
func (e *UpdateSyntheticAccountSyntheticAccountCategory) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "general":
		fallthrough
	case "ach_external":
		fallthrough
	case "instant_payment_external":
		fallthrough
	case "wire_external":
		*e = UpdateSyntheticAccountSyntheticAccountCategory(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateSyntheticAccountSyntheticAccountCategory: %v", v)
	}
}

// UpdateSyntheticAccountStatus - A value indicating the overall state of this Synthetic Account.
type UpdateSyntheticAccountStatus string

const (
	UpdateSyntheticAccountStatusInitiated UpdateSyntheticAccountStatus = "initiated"
	UpdateSyntheticAccountStatusActive    UpdateSyntheticAccountStatus = "active"
	UpdateSyntheticAccountStatusArchived  UpdateSyntheticAccountStatus = "archived"
	UpdateSyntheticAccountStatusFailed    UpdateSyntheticAccountStatus = "failed"
)

func (e UpdateSyntheticAccountStatus) ToPointer() *UpdateSyntheticAccountStatus {
	return &e
}
func (e *UpdateSyntheticAccountStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "initiated":
		fallthrough
	case "active":
		fallthrough
	case "archived":
		fallthrough
	case "failed":
		*e = UpdateSyntheticAccountStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateSyntheticAccountStatus: %v", v)
	}
}

type UpdateSyntheticAccountAssetBalance struct {
	AssetQuantity        *string `json:"asset_quantity,omitempty"`
	AssetType            *string `json:"asset_type,omitempty"`
	CurrentUsdValue      *string `json:"current_usd_value,omitempty"`
	CustodialAccountUID  *string `json:"custodial_account_uid,omitempty"`
	CustodialAccountName *string `json:"custodial_account_name,omitempty"`
	Debit                *bool   `json:"debit,omitempty"`
}

func (o *UpdateSyntheticAccountAssetBalance) GetAssetQuantity() *string {
	if o == nil {
		return nil
	}
	return o.AssetQuantity
}

func (o *UpdateSyntheticAccountAssetBalance) GetAssetType() *string {
	if o == nil {
		return nil
	}
	return o.AssetType
}

func (o *UpdateSyntheticAccountAssetBalance) GetCurrentUsdValue() *string {
	if o == nil {
		return nil
	}
	return o.CurrentUsdValue
}

func (o *UpdateSyntheticAccountAssetBalance) GetCustodialAccountUID() *string {
	if o == nil {
		return nil
	}
	return o.CustodialAccountUID
}

func (o *UpdateSyntheticAccountAssetBalance) GetCustodialAccountName() *string {
	if o == nil {
		return nil
	}
	return o.CustodialAccountName
}

func (o *UpdateSyntheticAccountAssetBalance) GetDebit() *bool {
	if o == nil {
		return nil
	}
	return o.Debit
}

// UpdateSyntheticAccountAccountTypeResponse - The type of ACH account
type UpdateSyntheticAccountAccountTypeResponse string

const (
	UpdateSyntheticAccountAccountTypeResponseChecking UpdateSyntheticAccountAccountTypeResponse = "checking"
	UpdateSyntheticAccountAccountTypeResponseSavings  UpdateSyntheticAccountAccountTypeResponse = "savings"
)

func (e UpdateSyntheticAccountAccountTypeResponse) ToPointer() *UpdateSyntheticAccountAccountTypeResponse {
	return &e
}
func (e *UpdateSyntheticAccountAccountTypeResponse) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "checking":
		fallthrough
	case "savings":
		*e = UpdateSyntheticAccountAccountTypeResponse(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateSyntheticAccountAccountTypeResponse: %v", v)
	}
}

// UpdateSyntheticAccountAchResponse - Contains ACH-specific information. Only populated if the Synthetic Account is in the `ach_external` category.
type UpdateSyntheticAccountAchResponse struct {
	// The type of ACH account
	AccountType *UpdateSyntheticAccountAccountTypeResponse `json:"account_type,omitempty"`
	// Name of the business or individual who owns the external account. Conditional maximum character length: for all newline supported SEC codes other than CIE, the counterparty_name can be 22 characters. For CIE SEC codes, the counterparty_name can be up to 15 characters.
	//
	CounterpartyName *string `json:"counterparty_name,omitempty"`
}

func (o *UpdateSyntheticAccountAchResponse) GetAccountType() *UpdateSyntheticAccountAccountTypeResponse {
	if o == nil {
		return nil
	}
	return o.AccountType
}

func (o *UpdateSyntheticAccountAchResponse) GetCounterpartyName() *string {
	if o == nil {
		return nil
	}
	return o.CounterpartyName
}

type UpdateSyntheticAccountInstantPaymentCounterpartyAddressResponse struct {
	// Building number for counterparty address. Alphanumeric only.
	StreetNumber string `json:"street_number"`
	// Street name for counterparty address
	Street1 string `json:"street1"`
	// Optional second line of street
	Street2 *string `json:"street2,omitempty"`
	// Maximum 35 characters
	City *string `json:"city"`
	// 2 characters. Must be a valid US state abbreviation.
	State *string `json:"state"`
	// 5-digit string. ZIP+4 is allowed.
	PostalCode *string `json:"postal_code"`
	Country    *string `json:"country"`
}

func (o *UpdateSyntheticAccountInstantPaymentCounterpartyAddressResponse) GetStreetNumber() string {
	if o == nil {
		return ""
	}
	return o.StreetNumber
}

func (o *UpdateSyntheticAccountInstantPaymentCounterpartyAddressResponse) GetStreet1() string {
	if o == nil {
		return ""
	}
	return o.Street1
}

func (o *UpdateSyntheticAccountInstantPaymentCounterpartyAddressResponse) GetStreet2() *string {
	if o == nil {
		return nil
	}
	return o.Street2
}

func (o *UpdateSyntheticAccountInstantPaymentCounterpartyAddressResponse) GetCity() *string {
	if o == nil {
		return nil
	}
	return o.City
}

func (o *UpdateSyntheticAccountInstantPaymentCounterpartyAddressResponse) GetState() *string {
	if o == nil {
		return nil
	}
	return o.State
}

func (o *UpdateSyntheticAccountInstantPaymentCounterpartyAddressResponse) GetPostalCode() *string {
	if o == nil {
		return nil
	}
	return o.PostalCode
}

func (o *UpdateSyntheticAccountInstantPaymentCounterpartyAddressResponse) GetCountry() *string {
	if o == nil {
		return nil
	}
	return o.Country
}

type UpdateSyntheticAccountInstantPaymentResponse struct {
	// Address of the business or individual who owns the external account.
	//
	CounterpartyAddress *UpdateSyntheticAccountInstantPaymentCounterpartyAddressResponse `json:"counterparty_address,omitempty"`
	// Name of the business or individual who owns the counterparty Account.
	//
	CounterpartyName *string `json:"counterparty_name,omitempty"`
	// Email address of the counterparty
	Email optionalnullable.OptionalNullable[string] `json:"email,omitempty"`
	// Exactly 10 digits long (no hyphens, parentheses, or spaces)
	Phone optionalnullable.OptionalNullable[string] `json:"phone,omitempty"`
}

func (o *UpdateSyntheticAccountInstantPaymentResponse) GetCounterpartyAddress() *UpdateSyntheticAccountInstantPaymentCounterpartyAddressResponse {
	if o == nil {
		return nil
	}
	return o.CounterpartyAddress
}

func (o *UpdateSyntheticAccountInstantPaymentResponse) GetCounterpartyName() *string {
	if o == nil {
		return nil
	}
	return o.CounterpartyName
}

func (o *UpdateSyntheticAccountInstantPaymentResponse) GetEmail() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *UpdateSyntheticAccountInstantPaymentResponse) GetPhone() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Phone
}

// UpdateSyntheticAccountWireCounterpartyAddressResponse - Address of the business or individual who owns the external account.
type UpdateSyntheticAccountWireCounterpartyAddressResponse struct {
	// Optional 35 characters. Cannot contain \# @ $ ! " % & * ; < > { } [ ] _ ^ \ ~
	//
	Line1 optionalnullable.OptionalNullable[string] `json:"line1,omitempty"`
	// Optional 35 characters. Cannot contain \# @ $ ! " % & * ; < > { } [ ] _ ^ \ ~
	//
	Line2 optionalnullable.OptionalNullable[string] `json:"line2,omitempty"`
	// Optional 32 characters. Note that this length is shorter than the other lines. Cannot contain \# @ $ ! " % & * ; < > { } [ ] _ ^ \ ~
	//
	Line3   optionalnullable.OptionalNullable[string] `json:"line3,omitempty"`
	Country optionalnullable.OptionalNullable[string] `json:"country,omitempty"`
}

func (o *UpdateSyntheticAccountWireCounterpartyAddressResponse) GetLine1() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Line1
}

func (o *UpdateSyntheticAccountWireCounterpartyAddressResponse) GetLine2() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Line2
}

func (o *UpdateSyntheticAccountWireCounterpartyAddressResponse) GetLine3() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Line3
}

func (o *UpdateSyntheticAccountWireCounterpartyAddressResponse) GetCountry() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Country
}

// UpdateSyntheticAccountCounterpartyBankAddressResponse - Address of the financial institution where the external account is held.
type UpdateSyntheticAccountCounterpartyBankAddressResponse struct {
	// Optional 35 characters. Cannot contain \# @ $ ! " % & * ; < > { } [ ] _ ^ \ ~
	//
	Line1 optionalnullable.OptionalNullable[string] `json:"line1,omitempty"`
	// Optional 35 characters. Cannot contain \# @ $ ! " % & * ; < > { } [ ] _ ^ \ ~
	//
	Line2 optionalnullable.OptionalNullable[string] `json:"line2,omitempty"`
	// Optional 32 characters. Note that this length is shorter than the other lines. Cannot contain \# @ $ ! " % & * ; < > { } [ ] _ ^ \ ~
	//
	Line3   optionalnullable.OptionalNullable[string] `json:"line3,omitempty"`
	Country optionalnullable.OptionalNullable[string] `json:"country,omitempty"`
}

func (o *UpdateSyntheticAccountCounterpartyBankAddressResponse) GetLine1() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Line1
}

func (o *UpdateSyntheticAccountCounterpartyBankAddressResponse) GetLine2() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Line2
}

func (o *UpdateSyntheticAccountCounterpartyBankAddressResponse) GetLine3() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Line3
}

func (o *UpdateSyntheticAccountCounterpartyBankAddressResponse) GetCountry() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Country
}

// UpdateSyntheticAccountWireResponse - Contains wire-specific information. Only populated if the Synthetic Account is in the `wire_external` category.
type UpdateSyntheticAccountWireResponse struct {
	// Address of the business or individual who owns the external account.
	//
	CounterpartyAddress optionalnullable.OptionalNullable[UpdateSyntheticAccountWireCounterpartyAddressResponse] `json:"counterparty_address,omitempty"`
	// Name of the business or individual who owns the counterparty Account. Required for synthetic accounts in the wire_external category. Maximum 35 characters.
	//
	CounterpartyName *string `json:"counterparty_name,omitempty"`
	// Address of the financial institution where the external account is held.
	//
	CounterpartyBankAddress optionalnullable.OptionalNullable[UpdateSyntheticAccountCounterpartyBankAddressResponse] `json:"counterparty_bank_address,omitempty"`
	// Name of the financial institution where the counterparty account is held.
	//
	CounterpartyBankName optionalnullable.OptionalNullable[string] `json:"counterparty_bank_name,omitempty"`
}

func (o *UpdateSyntheticAccountWireResponse) GetCounterpartyAddress() optionalnullable.OptionalNullable[UpdateSyntheticAccountWireCounterpartyAddressResponse] {
	if o == nil {
		return nil
	}
	return o.CounterpartyAddress
}

func (o *UpdateSyntheticAccountWireResponse) GetCounterpartyName() *string {
	if o == nil {
		return nil
	}
	return o.CounterpartyName
}

func (o *UpdateSyntheticAccountWireResponse) GetCounterpartyBankAddress() optionalnullable.OptionalNullable[UpdateSyntheticAccountCounterpartyBankAddressResponse] {
	if o == nil {
		return nil
	}
	return o.CounterpartyBankAddress
}

func (o *UpdateSyntheticAccountWireResponse) GetCounterpartyBankName() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.CounterpartyBankName
}

// UpdateSyntheticAccountResponseBody - The updated Synthetic Account resource is returned
type UpdateSyntheticAccountResponseBody struct {
	// Newline-generated unique id resource specific to the current endpoint
	UID *string `json:"uid,omitempty"`
	// A unique identifier the Client supplies. It must be unique within the resource type. If the same value is given, no new resource will be created.
	//
	ExternalUID *string `json:"external_uid,omitempty"`
	// A unique name, per pool, to identify the resource
	Name *string `json:"name,omitempty"`
	// The unique id of the Synthetic Account's pool
	PoolUID *string `json:"pool_uid,omitempty"`
	// A unique id referring to the Synthetic Account's type.
	//
	SyntheticAccountTypeUID *string `json:"synthetic_account_type_uid,omitempty"`
	// Array of unique ids of the Custodial Accounts this Synthetic Account is associated with.
	//
	CustodialAccountUids []string `json:"custodial_account_uids,omitempty"`
	// The name of the Synthetic Account Category associated with the Synthetic Account Type for this account. Refer to the Synthetic Account Type for details.
	SyntheticAccountCategory *UpdateSyntheticAccountSyntheticAccountCategory `json:"synthetic_account_category,omitempty"`
	// A value indicating the overall state of this Synthetic Account.
	//
	Status *UpdateSyntheticAccountStatus `json:"status,omitempty"`
	// Liability or asset. Any Synthetic Account created via [POST /synthetic_accounts](/reference/post_synthetic-accounts) is a liability account, except for external accounts. Some asset Synthetic Accounts are automatically created by Newline during Customer onboarding for accounting purposes.
	Liability *bool `json:"liability,omitempty"`
	// The current settled balance of this account in US Dollars. This field will be null for synthetic_account_types in an external category (`ach_external`, `instant_payment_external`, `wire_external`).
	NetUsdBalance optionalnullable.OptionalNullable[string] `json:"net_usd_balance,omitempty"`
	// The sum of all pending transactions for this account in US Dollars. This field will be null for Synthetic Account Types in an external category (`ach_external`, `instant_payment_external`, `wire_external`).
	NetUsdPendingBalance optionalnullable.OptionalNullable[string] `json:"net_usd_pending_balance,omitempty"`
	// The balance available to spend calculated as the settled balance less any pending withdrawals. Pending deposits are not included. This field will be null for Synthetic Account Types in an external category (`ach_external`, `instant_payment_external`, `wire_external`).
	NetUsdAvailableBalance optionalnullable.OptionalNullable[string] `json:"net_usd_available_balance,omitempty"`
	// The settled balance for the account in US Dollars as of the date in net_usd_closing_balance_as_of. This field will be null for Synthetic Account Types in an external category (`ach_external`, `instant_payment_external`, `wire_external`).
	NetUsdClosingBalance optionalnullable.OptionalNullable[string] `json:"net_usd_closing_balance,omitempty"`
	// The date that net_usd_closing_balance was last calculated. This field will be null for Synthetic Account Types in an external category (`ach_external`, `instant_payment_external`, `wire_external`).
	NetUsdClosingBalanceAsOf *string `json:"net_usd_closing_balance_as_of,omitempty"`
	// A list of balances for the various asset types held in Custodial Accounts associated with this Synthetic Account.
	//
	AssetBalances []*UpdateSyntheticAccountAssetBalance `json:"asset_balances,omitempty"`
	// Used to identify the Master Synthetic Accounts that exist for every Program Customer. Master Synthetic Accounts are the default accounts where any unknown custodial transactions will settle and cannot be archived while a Program Customer is still active.
	//
	MasterAccount *bool `json:"master_account,omitempty"`
	// The ABA routing number (if any) associated with this account. Some Synthetic Account Types require this field to be submitted along with the POST request. For example, any Synthetic Account Type from the `ach_external` or the `wire_external` category will require a `routing_number`. Submitting a `routing_number` with a Synthetic Account Type that does not require one will result in the routing number being ignored.
	RoutingNumber optionalnullable.OptionalNullable[string] `json:"routing_number,omitempty"`
	// Last 4 digits of the Synthetic Account number
	AccountNumberLastFour optionalnullable.OptionalNullable[string] `json:"account_number_last_four,omitempty"`
	// The DateTime at which this account was created
	OpenedAt *time.Time `json:"opened_at,omitempty"`
	// The DateTime at which this account was closed. This value will be present if the status is `archived` or `failed`.
	//
	ClosedAt optionalnullable.OptionalNullable[time.Time] `json:"closed_at,omitempty"`
	// The account number (if any) associated with this account. Some Synthetic Account Types require this field to be submitted along with the POST request. For example, any Synthetic Account Type from the `ach_external` or the `wire_external` category will require an `account_number`. Submitting an `account_number` with a Synthetic Account Type that does not require one will result in the account number being ignored.
	AccountNumber optionalnullable.OptionalNullable[string] `json:"account_number,omitempty"`
	// Contains ACH-specific information. Only populated if the Synthetic Account is in the `ach_external` category.
	//
	Ach            *UpdateSyntheticAccountAchResponse            `json:"ach,omitempty"`
	InstantPayment *UpdateSyntheticAccountInstantPaymentResponse `json:"instant_payment,omitempty"`
	// Contains wire-specific information. Only populated if the Synthetic Account is in the `wire_external` category.
	//
	Wire *UpdateSyntheticAccountWireResponse `json:"wire,omitempty"`
}

func (u UpdateSyntheticAccountResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateSyntheticAccountResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *UpdateSyntheticAccountResponseBody) GetUID() *string {
	if o == nil {
		return nil
	}
	return o.UID
}

func (o *UpdateSyntheticAccountResponseBody) GetExternalUID() *string {
	if o == nil {
		return nil
	}
	return o.ExternalUID
}

func (o *UpdateSyntheticAccountResponseBody) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UpdateSyntheticAccountResponseBody) GetPoolUID() *string {
	if o == nil {
		return nil
	}
	return o.PoolUID
}

func (o *UpdateSyntheticAccountResponseBody) GetSyntheticAccountTypeUID() *string {
	if o == nil {
		return nil
	}
	return o.SyntheticAccountTypeUID
}

func (o *UpdateSyntheticAccountResponseBody) GetCustodialAccountUids() []string {
	if o == nil {
		return nil
	}
	return o.CustodialAccountUids
}

func (o *UpdateSyntheticAccountResponseBody) GetSyntheticAccountCategory() *UpdateSyntheticAccountSyntheticAccountCategory {
	if o == nil {
		return nil
	}
	return o.SyntheticAccountCategory
}

func (o *UpdateSyntheticAccountResponseBody) GetStatus() *UpdateSyntheticAccountStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *UpdateSyntheticAccountResponseBody) GetLiability() *bool {
	if o == nil {
		return nil
	}
	return o.Liability
}

func (o *UpdateSyntheticAccountResponseBody) GetNetUsdBalance() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.NetUsdBalance
}

func (o *UpdateSyntheticAccountResponseBody) GetNetUsdPendingBalance() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.NetUsdPendingBalance
}

func (o *UpdateSyntheticAccountResponseBody) GetNetUsdAvailableBalance() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.NetUsdAvailableBalance
}

func (o *UpdateSyntheticAccountResponseBody) GetNetUsdClosingBalance() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.NetUsdClosingBalance
}

func (o *UpdateSyntheticAccountResponseBody) GetNetUsdClosingBalanceAsOf() *string {
	if o == nil {
		return nil
	}
	return o.NetUsdClosingBalanceAsOf
}

func (o *UpdateSyntheticAccountResponseBody) GetAssetBalances() []*UpdateSyntheticAccountAssetBalance {
	if o == nil {
		return nil
	}
	return o.AssetBalances
}

func (o *UpdateSyntheticAccountResponseBody) GetMasterAccount() *bool {
	if o == nil {
		return nil
	}
	return o.MasterAccount
}

func (o *UpdateSyntheticAccountResponseBody) GetRoutingNumber() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.RoutingNumber
}

func (o *UpdateSyntheticAccountResponseBody) GetAccountNumberLastFour() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.AccountNumberLastFour
}

func (o *UpdateSyntheticAccountResponseBody) GetOpenedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.OpenedAt
}

func (o *UpdateSyntheticAccountResponseBody) GetClosedAt() optionalnullable.OptionalNullable[time.Time] {
	if o == nil {
		return nil
	}
	return o.ClosedAt
}

func (o *UpdateSyntheticAccountResponseBody) GetAccountNumber() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.AccountNumber
}

func (o *UpdateSyntheticAccountResponseBody) GetAch() *UpdateSyntheticAccountAchResponse {
	if o == nil {
		return nil
	}
	return o.Ach
}

func (o *UpdateSyntheticAccountResponseBody) GetInstantPayment() *UpdateSyntheticAccountInstantPaymentResponse {
	if o == nil {
		return nil
	}
	return o.InstantPayment
}

func (o *UpdateSyntheticAccountResponseBody) GetWire() *UpdateSyntheticAccountWireResponse {
	if o == nil {
		return nil
	}
	return o.Wire
}

type UpdateSyntheticAccountResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The updated Synthetic Account resource is returned
	Object  *UpdateSyntheticAccountResponseBody
	Headers map[string][]string
}

func (o *UpdateSyntheticAccountResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateSyntheticAccountResponse) GetObject() *UpdateSyntheticAccountResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *UpdateSyntheticAccountResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
