/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetCustodialAccountClosingBalanceRequest = {
  /**
   * Newline-generated unique id resource specific to the current endpoint
   */
  uid: string;
};

/**
 * A single Custodial Account Closing Balance is returned
 */
export type GetCustodialAccountClosingBalanceResponseBody = {
  /**
   * Newline-generated unique id resource specific to the current endpoint
   */
  uid?: string | undefined;
  /**
   * A unique id referring to the Custodial Account
   */
  custodialAccountUid?: string | undefined;
  /**
   * A unique id referring to the External Custodial Account
   */
  custodialAccountExternalUid?: string | undefined;
  /**
   * The USD amount of the Custodial Account's closing balance
   */
  netUsdClosingBalance?: string | undefined;
  netUsdClosingBalanceAsOf?: Date | undefined;
};

export type GetCustodialAccountClosingBalanceResponse = {
  headers: { [k: string]: Array<string> };
  result: GetCustodialAccountClosingBalanceResponseBody;
};

/** @internal */
export type GetCustodialAccountClosingBalanceRequest$Outbound = {
  uid: string;
};

/** @internal */
export const GetCustodialAccountClosingBalanceRequest$outboundSchema:
  z.ZodMiniType<
    GetCustodialAccountClosingBalanceRequest$Outbound,
    GetCustodialAccountClosingBalanceRequest
  > = z.object({
    uid: z.string(),
  });

export function getCustodialAccountClosingBalanceRequestToJSON(
  getCustodialAccountClosingBalanceRequest:
    GetCustodialAccountClosingBalanceRequest,
): string {
  return JSON.stringify(
    GetCustodialAccountClosingBalanceRequest$outboundSchema.parse(
      getCustodialAccountClosingBalanceRequest,
    ),
  );
}

/** @internal */
export const GetCustodialAccountClosingBalanceResponseBody$inboundSchema:
  z.ZodMiniType<GetCustodialAccountClosingBalanceResponseBody, unknown> = z
    .pipe(
      z.object({
        uid: types.optional(types.string()),
        custodial_account_uid: types.optional(types.string()),
        custodial_account_external_uid: types.optional(types.string()),
        net_usd_closing_balance: types.optional(types.string()),
        net_usd_closing_balance_as_of: types.optional(types.date()),
      }),
      z.transform((v) => {
        return remap$(v, {
          "custodial_account_uid": "custodialAccountUid",
          "custodial_account_external_uid": "custodialAccountExternalUid",
          "net_usd_closing_balance": "netUsdClosingBalance",
          "net_usd_closing_balance_as_of": "netUsdClosingBalanceAsOf",
        });
      }),
    );

export function getCustodialAccountClosingBalanceResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetCustodialAccountClosingBalanceResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetCustodialAccountClosingBalanceResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetCustodialAccountClosingBalanceResponseBody' from JSON`,
  );
}

/** @internal */
export const GetCustodialAccountClosingBalanceResponse$inboundSchema:
  z.ZodMiniType<GetCustodialAccountClosingBalanceResponse, unknown> = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: z.lazy(() =>
        GetCustodialAccountClosingBalanceResponseBody$inboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function getCustodialAccountClosingBalanceResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetCustodialAccountClosingBalanceResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetCustodialAccountClosingBalanceResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetCustodialAccountClosingBalanceResponse' from JSON`,
  );
}
