/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetSyntheticAccountTypeRequest = {
  /**
   * Newline-generated unique id resource specific to the current endpoint
   */
  uid: string;
};

/**
 * The name of the Synthetic Account Category for this type. Accounts can be in one of several categories that indicate their handling properties and defining characteristics such as 'general' or 'external'. As an example, 'external' accounts do not actually hold any assets and are instead used to represent an account at an external institution for use in initiating transfers.
 */
export const GetSyntheticAccountTypeSyntheticAccountCategory = {
  General: "general",
  AchExternal: "ach_external",
  InstantPaymentsExternal: "instant_payments_external",
  WireExternal: "wire_external",
} as const;
/**
 * The name of the Synthetic Account Category for this type. Accounts can be in one of several categories that indicate their handling properties and defining characteristics such as 'general' or 'external'. As an example, 'external' accounts do not actually hold any assets and are instead used to represent an account at an external institution for use in initiating transfers.
 */
export type GetSyntheticAccountTypeSyntheticAccountCategory = OpenEnum<
  typeof GetSyntheticAccountTypeSyntheticAccountCategory
>;

/**
 * A single Synthetic Account Type is returned
 */
export type GetSyntheticAccountTypeResponseBody = {
  /**
   * Newline-generated unique id resource specific to the current endpoint
   */
  uid?: string | undefined;
  /**
   * A unique name, per pool, to identify the resource
   */
  name?: string | undefined;
  /**
   * A description outlining the intended use and requirements for this program's instance of the synthetic_account_type
   */
  description?: string | undefined;
  /**
   * A UID referring to the Program this synthetic_account_type belongs to
   */
  programUid?: string | undefined;
  /**
   * The name of the Synthetic Account Category for this type. Accounts can be in one of several categories that indicate their handling properties and defining characteristics such as 'general' or 'external'. As an example, 'external' accounts do not actually hold any assets and are instead used to represent an account at an external institution for use in initiating transfers.
   */
  syntheticAccountCategory?:
    | GetSyntheticAccountTypeSyntheticAccountCategory
    | undefined;
};

export type GetSyntheticAccountTypeResponse = {
  headers: { [k: string]: Array<string> };
  result: GetSyntheticAccountTypeResponseBody;
};

/** @internal */
export type GetSyntheticAccountTypeRequest$Outbound = {
  uid: string;
};

/** @internal */
export const GetSyntheticAccountTypeRequest$outboundSchema: z.ZodMiniType<
  GetSyntheticAccountTypeRequest$Outbound,
  GetSyntheticAccountTypeRequest
> = z.object({
  uid: z.string(),
});

export function getSyntheticAccountTypeRequestToJSON(
  getSyntheticAccountTypeRequest: GetSyntheticAccountTypeRequest,
): string {
  return JSON.stringify(
    GetSyntheticAccountTypeRequest$outboundSchema.parse(
      getSyntheticAccountTypeRequest,
    ),
  );
}

/** @internal */
export const GetSyntheticAccountTypeSyntheticAccountCategory$inboundSchema:
  z.ZodMiniType<GetSyntheticAccountTypeSyntheticAccountCategory, unknown> =
    openEnums.inboundSchema(GetSyntheticAccountTypeSyntheticAccountCategory);

/** @internal */
export const GetSyntheticAccountTypeResponseBody$inboundSchema: z.ZodMiniType<
  GetSyntheticAccountTypeResponseBody,
  unknown
> = z.pipe(
  z.object({
    uid: types.optional(types.string()),
    name: types.optional(types.string()),
    description: types.optional(types.string()),
    program_uid: types.optional(types.string()),
    synthetic_account_category: types.optional(
      GetSyntheticAccountTypeSyntheticAccountCategory$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "program_uid": "programUid",
      "synthetic_account_category": "syntheticAccountCategory",
    });
  }),
);

export function getSyntheticAccountTypeResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetSyntheticAccountTypeResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetSyntheticAccountTypeResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSyntheticAccountTypeResponseBody' from JSON`,
  );
}

/** @internal */
export const GetSyntheticAccountTypeResponse$inboundSchema: z.ZodMiniType<
  GetSyntheticAccountTypeResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetSyntheticAccountTypeResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getSyntheticAccountTypeResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetSyntheticAccountTypeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSyntheticAccountTypeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSyntheticAccountTypeResponse' from JSON`,
  );
}
