/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Filter by type. Multiple values are allowed, e.g. `type[]=odfi_ach_deposit&type[]=odfi_ach_withdrawal`.
 *
 * @remarks
 */
export const GetTransactionEventsQueryParamType = {
  OdfiAchDeposit: "odfi_ach_deposit",
  OdfiAchWithdrawal: "odfi_ach_withdrawal",
  RdfiAchDeposit: "rdfi_ach_deposit",
  RdfiAchWithdrawal: "rdfi_ach_withdrawal",
} as const;
/**
 * Filter by type. Multiple values are allowed, e.g. `type[]=odfi_ach_deposit&type[]=odfi_ach_withdrawal`.
 *
 * @remarks
 */
export type GetTransactionEventsQueryParamType = ClosedEnum<
  typeof GetTransactionEventsQueryParamType
>;

export const GetTransactionEventsSort = {
  CreatedAtAsc: "created_at_asc",
  CreatedAtDesc: "created_at_desc",
  DescriptionAsc: "description_asc",
  DescriptionDesc: "description_desc",
  SettledIndexAsc: "settled_index_asc",
  SettledIndexDesc: "settled_index_desc",
  UsDollarAmountAsc: "us_dollar_amount_asc",
  UsDollarAmountDesc: "us_dollar_amount_desc",
} as const;
export type GetTransactionEventsSort = ClosedEnum<
  typeof GetTransactionEventsSort
>;

export type GetTransactionEventsRequest = {
  sourceCustodialAccountUid?: string | undefined;
  destinationCustodialAccountUid?: string | undefined;
  custodialAccountUid?: string | undefined;
  /**
   * Filter by type. Multiple values are allowed, e.g. `type[]=odfi_ach_deposit&type[]=odfi_ach_withdrawal`.
   *
   * @remarks
   */
  type?: GetTransactionEventsQueryParamType | undefined;
  /**
   * Filter by Transaction. Multiple values are allowed, e.g. `transaction_uid[]=SMwKC1osz77DTEiu&transaction_uid[]=f1UDvUVNnXTKtgxu`.
   *
   * @remarks
   */
  transactionUid?: string | undefined;
  /**
   * Maximum number of items to retrieve. This filter is automatically applied with the default value if not given.
   *
   * @remarks
   */
  limit?: number | undefined;
  /**
   * Index of the items to start retrieving from
   */
  offset?: number | undefined;
  sort?: GetTransactionEventsSort | undefined;
};

/**
 * Transaction Events will always have a status of `settled`
 */
export const GetTransactionEventsStatus = {
  Settled: "settled",
} as const;
/**
 * Transaction Events will always have a status of `settled`
 */
export type GetTransactionEventsStatus = ClosedEnum<
  typeof GetTransactionEventsStatus
>;

export const GetTransactionEventsTypeSettled = {
  OdfiAchDeposit: "odfi_ach_deposit",
  OdfiAchWithdrawal: "odfi_ach_withdrawal",
  RdfiAchDeposit: "rdfi_ach_deposit",
  RdfiAchWithdrawal: "rdfi_ach_withdrawal",
} as const;
export type GetTransactionEventsTypeSettled = OpenEnum<
  typeof GetTransactionEventsTypeSettled
>;

/**
 * Indicates whether the Customer's asset has gone up (`positive`), gone down (`negative`) or stayed the same (`neutral`) as a result of this Transaction Event. This value is determined by `type`.
 *
 * @remarks
 */
export const GetTransactionEventsNetAsset = {
  Positive: "positive",
  Negative: "negative",
  Neutral: "neutral",
} as const;
/**
 * Indicates whether the Customer's asset has gone up (`positive`), gone down (`negative`) or stayed the same (`neutral`) as a result of this Transaction Event. This value is determined by `type`.
 *
 * @remarks
 */
export type GetTransactionEventsNetAsset = OpenEnum<
  typeof GetTransactionEventsNetAsset
>;

export type GetTransactionEventsData = {
  /**
   * Newline-generated unique id resource specific to the current endpoint
   */
  uid?: string | undefined;
  /**
   * A unique index that indicates the order in which Transaction Events were settled
   *
   * @remarks
   */
  settledIndex?: number | undefined;
  /**
   * A list of UIDS referring to Transactions this Transaction Event belongs to.
   *
   * @remarks
   */
  transactionUids?: Array<string> | undefined;
  /**
   * Custodial Account from which the asset is pulled
   */
  sourceCustodialAccountUid?: string | undefined;
  /**
   * Custodial Account where the asset lands
   */
  destinationCustodialAccountUid?: string | undefined;
  /**
   * A list of UIDS referring to Custodial Line Items belonging to this event. There are always at least two line items if the status is `settled`.
   *
   * @remarks
   */
  custodialLineItemUids?: Array<string> | undefined;
  /**
   * Transaction Events will always have a status of `settled`
   */
  status?: GetTransactionEventsStatus | undefined;
  /**
   * The amount will never be negative
   */
  usDollarAmount?: string | undefined;
  type?: GetTransactionEventsTypeSettled | undefined;
  /**
   * If this Transaction Event represents a Debit Card purchase or refund, the UID of the Debit Card used for the purchase/refund. Otherwise not provided.
   *
   * @remarks
   */
  debitCardUid?: string | undefined;
  /**
   * Indicates whether the Customer's asset has gone up (`positive`), gone down (`negative`) or stayed the same (`neutral`) as a result of this Transaction Event. This value is determined by `type`.
   *
   * @remarks
   */
  netAsset?: GetTransactionEventsNetAsset | undefined;
  description?: string | undefined;
  /**
   * The date and time when the event is first recognized by Newline. This may be when the Transfer is initiated if the event is associated with one.
   *
   * @remarks
   */
  createdAt?: Date | undefined;
  /**
   * The date and time when the event is settled
   */
  settledAt?: Date | undefined;
};

/**
 * A list of Transaction Events is returned
 */
export type GetTransactionEventsResponseBody = {
  /**
   * Total count of items available to retrieve
   */
  totalCount?: number | undefined;
  /**
   * Number of items retrieved
   */
  count?: number | undefined;
  /**
   * Maximum number of items to retrieve
   */
  limit?: number | undefined;
  /**
   * Index of the first item to retrieve
   */
  offset?: number | undefined;
  data?: Array<GetTransactionEventsData> | undefined;
};

export type GetTransactionEventsResponse = {
  headers: { [k: string]: Array<string> };
  result: GetTransactionEventsResponseBody;
};

/** @internal */
export const GetTransactionEventsQueryParamType$outboundSchema: z.ZodMiniEnum<
  typeof GetTransactionEventsQueryParamType
> = z.enum(GetTransactionEventsQueryParamType);

/** @internal */
export const GetTransactionEventsSort$outboundSchema: z.ZodMiniEnum<
  typeof GetTransactionEventsSort
> = z.enum(GetTransactionEventsSort);

/** @internal */
export type GetTransactionEventsRequest$Outbound = {
  source_custodial_account_uid?: string | undefined;
  destination_custodial_account_uid?: string | undefined;
  custodial_account_uid?: string | undefined;
  type?: string | undefined;
  transaction_uid?: string | undefined;
  limit: number;
  offset: number;
  sort?: string | undefined;
};

/** @internal */
export const GetTransactionEventsRequest$outboundSchema: z.ZodMiniType<
  GetTransactionEventsRequest$Outbound,
  GetTransactionEventsRequest
> = z.pipe(
  z.object({
    sourceCustodialAccountUid: z.optional(z.string()),
    destinationCustodialAccountUid: z.optional(z.string()),
    custodialAccountUid: z.optional(z.string()),
    type: z.optional(GetTransactionEventsQueryParamType$outboundSchema),
    transactionUid: z.optional(z.string()),
    limit: z._default(z.int(), 100),
    offset: z._default(z.int(), 0),
    sort: z.optional(GetTransactionEventsSort$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      sourceCustodialAccountUid: "source_custodial_account_uid",
      destinationCustodialAccountUid: "destination_custodial_account_uid",
      custodialAccountUid: "custodial_account_uid",
      transactionUid: "transaction_uid",
    });
  }),
);

export function getTransactionEventsRequestToJSON(
  getTransactionEventsRequest: GetTransactionEventsRequest,
): string {
  return JSON.stringify(
    GetTransactionEventsRequest$outboundSchema.parse(
      getTransactionEventsRequest,
    ),
  );
}

/** @internal */
export const GetTransactionEventsStatus$inboundSchema: z.ZodMiniEnum<
  typeof GetTransactionEventsStatus
> = z.enum(GetTransactionEventsStatus);

/** @internal */
export const GetTransactionEventsTypeSettled$inboundSchema: z.ZodMiniType<
  GetTransactionEventsTypeSettled,
  unknown
> = openEnums.inboundSchema(GetTransactionEventsTypeSettled);

/** @internal */
export const GetTransactionEventsNetAsset$inboundSchema: z.ZodMiniType<
  GetTransactionEventsNetAsset,
  unknown
> = openEnums.inboundSchema(GetTransactionEventsNetAsset);

/** @internal */
export const GetTransactionEventsData$inboundSchema: z.ZodMiniType<
  GetTransactionEventsData,
  unknown
> = z.pipe(
  z.object({
    uid: types.optional(types.string()),
    settled_index: types.optional(types.number()),
    transaction_uids: types.optional(z.array(types.string())),
    source_custodial_account_uid: types.optional(types.string()),
    destination_custodial_account_uid: types.optional(types.string()),
    custodial_line_item_uids: types.optional(z.array(types.string())),
    status: types.optional(GetTransactionEventsStatus$inboundSchema),
    us_dollar_amount: types.optional(types.string()),
    type: types.optional(GetTransactionEventsTypeSettled$inboundSchema),
    debit_card_uid: types.optional(types.string()),
    net_asset: types.optional(GetTransactionEventsNetAsset$inboundSchema),
    description: types.optional(types.string()),
    created_at: types.optional(types.date()),
    settled_at: types.optional(types.date()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "settled_index": "settledIndex",
      "transaction_uids": "transactionUids",
      "source_custodial_account_uid": "sourceCustodialAccountUid",
      "destination_custodial_account_uid": "destinationCustodialAccountUid",
      "custodial_line_item_uids": "custodialLineItemUids",
      "us_dollar_amount": "usDollarAmount",
      "debit_card_uid": "debitCardUid",
      "net_asset": "netAsset",
      "created_at": "createdAt",
      "settled_at": "settledAt",
    });
  }),
);

export function getTransactionEventsDataFromJSON(
  jsonString: string,
): SafeParseResult<GetTransactionEventsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTransactionEventsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTransactionEventsData' from JSON`,
  );
}

/** @internal */
export const GetTransactionEventsResponseBody$inboundSchema: z.ZodMiniType<
  GetTransactionEventsResponseBody,
  unknown
> = z.pipe(
  z.object({
    total_count: types.optional(types.number()),
    count: types.optional(types.number()),
    limit: types.optional(types.number()),
    offset: types.optional(types.number()),
    data: types.optional(
      z.array(z.lazy(() => GetTransactionEventsData$inboundSchema)),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "total_count": "totalCount",
    });
  }),
);

export function getTransactionEventsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetTransactionEventsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTransactionEventsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTransactionEventsResponseBody' from JSON`,
  );
}

/** @internal */
export const GetTransactionEventsResponse$inboundSchema: z.ZodMiniType<
  GetTransactionEventsResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetTransactionEventsResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getTransactionEventsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetTransactionEventsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTransactionEventsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTransactionEventsResponse' from JSON`,
  );
}
