/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type ListCustodialAccountClosingBalancesRequest = {
  /**
   * Filter by Custodial Account
   */
  custodialAccountUid?: string | undefined;
  /**
   * Filter by Custodial Account External. Multiple values are allowed, e.g. `custodial_account_external_uid[]=4XkJnsfHsuqrxmeX&custodial_account_external_uid[]=exMDShw6yM3NHLYV`.
   *
   * @remarks
   */
  custodialAccountExternalUid?: string | undefined;
  /**
   * Maximum number of items to retrieve. This filter is automatically applied with the default value if not given.
   *
   * @remarks
   */
  limit?: number | undefined;
  /**
   * Index of the items to start retrieving from
   */
  offset?: number | undefined;
  netUsdClosingBalanceAsOf?: Date | undefined;
  netUsdClosingBalanceBefore?: Date | undefined;
  netUsdClosingBalanceAfter?: Date | undefined;
};

export type ListCustodialAccountClosingBalancesData = {
  /**
   * Newline-generated unique id resource specific to the current endpoint
   */
  uid?: string | undefined;
  /**
   * A unique id referring to the Custodial Account
   */
  custodialAccountUid?: string | undefined;
  /**
   * A unique id referring to the External Custodial Account
   */
  custodialAccountExternalUid?: string | undefined;
  /**
   * The USD amount of the Custodial Account's closing balance
   */
  netUsdClosingBalance?: string | undefined;
  netUsdClosingBalanceAsOf?: Date | undefined;
};

/**
 * A list of Custodial Account Closing balances is returned
 */
export type ListCustodialAccountClosingBalancesResponseBody = {
  /**
   * Total count of items available to retrieve
   */
  totalCount?: number | undefined;
  /**
   * Number of items retrieved
   */
  count?: number | undefined;
  /**
   * Maximum number of items to retrieve
   */
  limit?: number | undefined;
  /**
   * Index of the first item to retrieve
   */
  offset?: number | undefined;
  data?: Array<ListCustodialAccountClosingBalancesData> | undefined;
};

export type ListCustodialAccountClosingBalancesResponse = {
  headers: { [k: string]: Array<string> };
  result: ListCustodialAccountClosingBalancesResponseBody;
};

/** @internal */
export type ListCustodialAccountClosingBalancesRequest$Outbound = {
  custodial_account_uid?: string | undefined;
  custodial_account_external_uid?: string | undefined;
  limit: number;
  offset: number;
  net_usd_closing_balance_as_of?: string | undefined;
  net_usd_closing_balance_before?: string | undefined;
  net_usd_closing_balance_after?: string | undefined;
};

/** @internal */
export const ListCustodialAccountClosingBalancesRequest$outboundSchema:
  z.ZodMiniType<
    ListCustodialAccountClosingBalancesRequest$Outbound,
    ListCustodialAccountClosingBalancesRequest
  > = z.pipe(
    z.object({
      custodialAccountUid: z.optional(z.string()),
      custodialAccountExternalUid: z.optional(z.string()),
      limit: z._default(z.int(), 100),
      offset: z._default(z.int(), 0),
      netUsdClosingBalanceAsOf: z.optional(
        z.pipe(z.date(), z.transform(v => v.toISOString())),
      ),
      netUsdClosingBalanceBefore: z.optional(
        z.pipe(z.date(), z.transform(v => v.toISOString())),
      ),
      netUsdClosingBalanceAfter: z.optional(
        z.pipe(z.date(), z.transform(v => v.toISOString())),
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        custodialAccountUid: "custodial_account_uid",
        custodialAccountExternalUid: "custodial_account_external_uid",
        netUsdClosingBalanceAsOf: "net_usd_closing_balance_as_of",
        netUsdClosingBalanceBefore: "net_usd_closing_balance_before",
        netUsdClosingBalanceAfter: "net_usd_closing_balance_after",
      });
    }),
  );

export function listCustodialAccountClosingBalancesRequestToJSON(
  listCustodialAccountClosingBalancesRequest:
    ListCustodialAccountClosingBalancesRequest,
): string {
  return JSON.stringify(
    ListCustodialAccountClosingBalancesRequest$outboundSchema.parse(
      listCustodialAccountClosingBalancesRequest,
    ),
  );
}

/** @internal */
export const ListCustodialAccountClosingBalancesData$inboundSchema:
  z.ZodMiniType<ListCustodialAccountClosingBalancesData, unknown> = z.pipe(
    z.object({
      uid: types.optional(types.string()),
      custodial_account_uid: types.optional(types.string()),
      custodial_account_external_uid: types.optional(types.string()),
      net_usd_closing_balance: types.optional(types.string()),
      net_usd_closing_balance_as_of: types.optional(types.date()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "custodial_account_uid": "custodialAccountUid",
        "custodial_account_external_uid": "custodialAccountExternalUid",
        "net_usd_closing_balance": "netUsdClosingBalance",
        "net_usd_closing_balance_as_of": "netUsdClosingBalanceAsOf",
      });
    }),
  );

export function listCustodialAccountClosingBalancesDataFromJSON(
  jsonString: string,
): SafeParseResult<
  ListCustodialAccountClosingBalancesData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListCustodialAccountClosingBalancesData$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListCustodialAccountClosingBalancesData' from JSON`,
  );
}

/** @internal */
export const ListCustodialAccountClosingBalancesResponseBody$inboundSchema:
  z.ZodMiniType<ListCustodialAccountClosingBalancesResponseBody, unknown> = z
    .pipe(
      z.object({
        total_count: types.optional(types.number()),
        count: types.optional(types.number()),
        limit: types.optional(types.number()),
        offset: types.optional(types.number()),
        data: types.optional(z.array(z.lazy(() =>
          ListCustodialAccountClosingBalancesData$inboundSchema
        ))),
      }),
      z.transform((v) => {
        return remap$(v, {
          "total_count": "totalCount",
        });
      }),
    );

export function listCustodialAccountClosingBalancesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  ListCustodialAccountClosingBalancesResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListCustodialAccountClosingBalancesResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListCustodialAccountClosingBalancesResponseBody' from JSON`,
  );
}

/** @internal */
export const ListCustodialAccountClosingBalancesResponse$inboundSchema:
  z.ZodMiniType<ListCustodialAccountClosingBalancesResponse, unknown> = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: z.lazy(() =>
        ListCustodialAccountClosingBalancesResponseBody$inboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function listCustodialAccountClosingBalancesResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ListCustodialAccountClosingBalancesResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListCustodialAccountClosingBalancesResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListCustodialAccountClosingBalancesResponse' from JSON`,
  );
}
