/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type PutVirtualReferenceNumbersUidUnlockRequest = {
  /**
   * Newline-generated unique id resource specific to the current endpoint
   */
  uid: string;
};

export type PutVirtualReferenceNumbersUidUnlockUnprocessableEntityError = {
  /**
   * Code provided by Newline for reference
   */
  code?: number | undefined;
  /**
   * Title of Error Code
   */
  title?: string | undefined;
  /**
   * Description of Error Code
   */
  detail?: string | undefined;
  /**
   * Error Timestamp
   */
  occurredAt?: string | undefined;
  /**
   * Included based on Error Code; Additional context to help users self-solve the error
   */
  extra?: string | undefined;
};

export type PutVirtualReferenceNumbersUidUnlockNotFoundError = {
  /**
   * Code provided by Newline for reference
   */
  code?: number | undefined;
  /**
   * Title of Error Code
   */
  title?: string | undefined;
  /**
   * Description of Error Code
   */
  detail?: string | undefined;
  /**
   * Error Timestamp
   */
  occurredAt?: string | undefined;
  /**
   * Included based on Error Code; Additional context to help users self-solve the error
   */
  extra?: string | undefined;
};

/**
 * Registration status with Newline and Fifth Third, for RTP network acceptance.
 */
export const PutVirtualReferenceNumbersUidUnlockInstantPaymentRailRegistrationStatus =
  {
    Failed: "failed",
    Pending: "pending",
    Registered: "registered",
    Unregistered: "unregistered",
  } as const;
/**
 * Registration status with Newline and Fifth Third, for RTP network acceptance.
 */
export type PutVirtualReferenceNumbersUidUnlockInstantPaymentRailRegistrationStatus =
  OpenEnum<
    typeof PutVirtualReferenceNumbersUidUnlockInstantPaymentRailRegistrationStatus
  >;

/**
 * Provided reason for locking the VRN.
 */
export const PutVirtualReferenceNumbersUidUnlockLockReason = {
  Admin: "admin",
  CustomerRequest: "customer_request",
} as const;
/**
 * Provided reason for locking the VRN.
 */
export type PutVirtualReferenceNumbersUidUnlockLockReason = OpenEnum<
  typeof PutVirtualReferenceNumbersUidUnlockLockReason
>;

/**
 * A value indicating the overall state of this VRN.
 */
export const PutVirtualReferenceNumbersUidUnlockStatus = {
  Active: "active",
  Archived: "archived",
} as const;
/**
 * A value indicating the overall state of this VRN.
 */
export type PutVirtualReferenceNumbersUidUnlockStatus = OpenEnum<
  typeof PutVirtualReferenceNumbersUidUnlockStatus
>;

/**
 * The locked Virtual Reference Number resource is returned
 */
export type PutVirtualReferenceNumbersUidUnlockResponseBody = {
  /**
   * The DateTime at which this VRN was archived. This value will be present if the status is archived. If in another state, the value will be null.
   */
  archivedAt?: string | undefined;
  /**
   * The DateTime at which this VRN was created
   */
  createdAt?: string | undefined;
  /**
   * A unique id referring to the mapped, Custodial Account.
   */
  custodialAccountUid?: string | undefined;
  /**
   * A unique identifier the Client supplies. It must be unique within the resource type. If the same value is given, no new resource will be created.
   *
   * @remarks
   */
  externalUid?: string | undefined;
  /**
   * Registration status with Newline and Fifth Third, for RTP network acceptance.
   */
  instantPaymentRailRegistrationStatus?:
    | PutVirtualReferenceNumbersUidUnlockInstantPaymentRailRegistrationStatus
    | undefined;
  /**
   * The DateTime at which this VRN was locked. This value will be present if the status is locked. If in another state, the value will be null.
   */
  lockedAt?: string | undefined;
  /**
   * Provided reason for locking the VRN.
   */
  lockReason?: PutVirtualReferenceNumbersUidUnlockLockReason | undefined;
  /**
   * A unique name, per pool, to identify the resource.
   */
  name?: string | undefined;
  /**
   * The ABA routing number (if any) associated with this VRN.
   */
  routingNumber?: string | undefined;
  /**
   * A value indicating the overall state of this VRN.
   */
  status?: PutVirtualReferenceNumbersUidUnlockStatus | undefined;
  /**
   * A unique id referring to the mapped, general Synthetic Account.
   */
  syntheticAccountUid?: string | undefined;
  /**
   * Unique identifier for the VRN
   */
  uid?: string | undefined;
  /**
   * Last 4 digits of the VRN
   */
  virtualReferenceNumberLastFour?: string | undefined;
  /**
   * The VRN
   */
  virtualReferenceNumber?: string | undefined;
};

export type PutVirtualReferenceNumbersUidUnlockResponse = {
  headers: { [k: string]: Array<string> };
  result: PutVirtualReferenceNumbersUidUnlockResponseBody;
};

/** @internal */
export type PutVirtualReferenceNumbersUidUnlockRequest$Outbound = {
  uid: string;
};

/** @internal */
export const PutVirtualReferenceNumbersUidUnlockRequest$outboundSchema:
  z.ZodMiniType<
    PutVirtualReferenceNumbersUidUnlockRequest$Outbound,
    PutVirtualReferenceNumbersUidUnlockRequest
  > = z.object({
    uid: z.string(),
  });

export function putVirtualReferenceNumbersUidUnlockRequestToJSON(
  putVirtualReferenceNumbersUidUnlockRequest:
    PutVirtualReferenceNumbersUidUnlockRequest,
): string {
  return JSON.stringify(
    PutVirtualReferenceNumbersUidUnlockRequest$outboundSchema.parse(
      putVirtualReferenceNumbersUidUnlockRequest,
    ),
  );
}

/** @internal */
export const PutVirtualReferenceNumbersUidUnlockUnprocessableEntityError$inboundSchema:
  z.ZodMiniType<
    PutVirtualReferenceNumbersUidUnlockUnprocessableEntityError,
    unknown
  > = z.pipe(
    z.object({
      code: types.optional(types.number()),
      title: types.optional(types.string()),
      detail: types.optional(types.string()),
      occurred_at: types.optional(types.string()),
      extra: types.optional(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "occurred_at": "occurredAt",
      });
    }),
  );

export function putVirtualReferenceNumbersUidUnlockUnprocessableEntityErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  PutVirtualReferenceNumbersUidUnlockUnprocessableEntityError,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PutVirtualReferenceNumbersUidUnlockUnprocessableEntityError$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PutVirtualReferenceNumbersUidUnlockUnprocessableEntityError' from JSON`,
  );
}

/** @internal */
export const PutVirtualReferenceNumbersUidUnlockNotFoundError$inboundSchema:
  z.ZodMiniType<PutVirtualReferenceNumbersUidUnlockNotFoundError, unknown> = z
    .pipe(
      z.object({
        code: types.optional(types.number()),
        title: types.optional(types.string()),
        detail: types.optional(types.string()),
        occurred_at: types.optional(types.string()),
        extra: types.optional(types.string()),
      }),
      z.transform((v) => {
        return remap$(v, {
          "occurred_at": "occurredAt",
        });
      }),
    );

export function putVirtualReferenceNumbersUidUnlockNotFoundErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  PutVirtualReferenceNumbersUidUnlockNotFoundError,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PutVirtualReferenceNumbersUidUnlockNotFoundError$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PutVirtualReferenceNumbersUidUnlockNotFoundError' from JSON`,
  );
}

/** @internal */
export const PutVirtualReferenceNumbersUidUnlockInstantPaymentRailRegistrationStatus$inboundSchema:
  z.ZodMiniType<
    PutVirtualReferenceNumbersUidUnlockInstantPaymentRailRegistrationStatus,
    unknown
  > = openEnums.inboundSchema(
    PutVirtualReferenceNumbersUidUnlockInstantPaymentRailRegistrationStatus,
  );

/** @internal */
export const PutVirtualReferenceNumbersUidUnlockLockReason$inboundSchema:
  z.ZodMiniType<PutVirtualReferenceNumbersUidUnlockLockReason, unknown> =
    openEnums.inboundSchema(PutVirtualReferenceNumbersUidUnlockLockReason);

/** @internal */
export const PutVirtualReferenceNumbersUidUnlockStatus$inboundSchema:
  z.ZodMiniType<PutVirtualReferenceNumbersUidUnlockStatus, unknown> = openEnums
    .inboundSchema(PutVirtualReferenceNumbersUidUnlockStatus);

/** @internal */
export const PutVirtualReferenceNumbersUidUnlockResponseBody$inboundSchema:
  z.ZodMiniType<PutVirtualReferenceNumbersUidUnlockResponseBody, unknown> = z
    .pipe(
      z.object({
        archived_at: types.optional(types.string()),
        created_at: types.optional(types.string()),
        custodial_account_uid: types.optional(types.string()),
        external_uid: types.optional(types.string()),
        instant_payment_rail_registration_status: types.optional(
          PutVirtualReferenceNumbersUidUnlockInstantPaymentRailRegistrationStatus$inboundSchema,
        ),
        locked_at: types.optional(types.string()),
        lock_reason: types.optional(
          PutVirtualReferenceNumbersUidUnlockLockReason$inboundSchema,
        ),
        name: types.optional(types.string()),
        routing_number: types.optional(types.string()),
        status: types.optional(
          PutVirtualReferenceNumbersUidUnlockStatus$inboundSchema,
        ),
        synthetic_account_uid: types.optional(types.string()),
        uid: types.optional(types.string()),
        virtual_reference_number_last_four: types.optional(types.string()),
        virtual_reference_number: types.optional(types.string()),
      }),
      z.transform((v) => {
        return remap$(v, {
          "archived_at": "archivedAt",
          "created_at": "createdAt",
          "custodial_account_uid": "custodialAccountUid",
          "external_uid": "externalUid",
          "instant_payment_rail_registration_status":
            "instantPaymentRailRegistrationStatus",
          "locked_at": "lockedAt",
          "lock_reason": "lockReason",
          "routing_number": "routingNumber",
          "synthetic_account_uid": "syntheticAccountUid",
          "virtual_reference_number_last_four":
            "virtualReferenceNumberLastFour",
          "virtual_reference_number": "virtualReferenceNumber",
        });
      }),
    );

export function putVirtualReferenceNumbersUidUnlockResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  PutVirtualReferenceNumbersUidUnlockResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PutVirtualReferenceNumbersUidUnlockResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PutVirtualReferenceNumbersUidUnlockResponseBody' from JSON`,
  );
}

/** @internal */
export const PutVirtualReferenceNumbersUidUnlockResponse$inboundSchema:
  z.ZodMiniType<PutVirtualReferenceNumbersUidUnlockResponse, unknown> = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: z.lazy(() =>
        PutVirtualReferenceNumbersUidUnlockResponseBody$inboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function putVirtualReferenceNumbersUidUnlockResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PutVirtualReferenceNumbersUidUnlockResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PutVirtualReferenceNumbersUidUnlockResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PutVirtualReferenceNumbersUidUnlockResponse' from JSON`,
  );
}
